// World Service gRPC接口定义，提供地图/实体/视野/移动相关查询与操作。
// 对应design.md 2.2.2.1节接口清单，保留现有接口并新增地形与视野查询接口。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/world/world.proto

package worldpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPositionRequest 查询实体位置请求
type GetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 实体ID，全局唯一（规范8用int64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_proto_world_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{0}
}

func (x *GetPositionRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetPositionRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

// PositionResponse 实体位置响应
type PositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                       // 响应头
	Position      *common.Position       `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`                                   // 实体当前坐标
	MoveStatus    int32                  `protobuf:"varint,3,opt,name=move_status,json=moveStatus,proto3" json:"move_status,omitempty"`            // 移动状态：1=静止 2=移动中 3=已到达 4=已阻挡
	MoveStartTime int64                  `protobuf:"varint,4,opt,name=move_start_time,json=moveStartTime,proto3" json:"move_start_time,omitempty"` // 移动开始时间戳（毫秒），0表示未移动
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResponse) Reset() {
	*x = PositionResponse{}
	mi := &file_proto_world_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResponse) ProtoMessage() {}

func (x *PositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResponse.ProtoReflect.Descriptor instead.
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{1}
}

func (x *PositionResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PositionResponse) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PositionResponse) GetMoveStatus() int32 {
	if x != nil {
		return x.MoveStatus
	}
	return 0
}

func (x *PositionResponse) GetMoveStartTime() int64 {
	if x != nil {
		return x.MoveStartTime
	}
	return 0
}

// MapSnapshotRequest 查询地图快照请求
type MapSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`             // 请求头
	MapId         int64                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"` // 地图ID
	Center        *common.Position       `protobuf:"bytes,3,opt,name=center,proto3" json:"center,omitempty"`             // 视野中心坐标
	Radius        int32                  `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`            // 视野半径（格子数）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapSnapshotRequest) Reset() {
	*x = MapSnapshotRequest{}
	mi := &file_proto_world_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSnapshotRequest) ProtoMessage() {}

func (x *MapSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSnapshotRequest.ProtoReflect.Descriptor instead.
func (*MapSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{2}
}

func (x *MapSnapshotRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MapSnapshotRequest) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapSnapshotRequest) GetCenter() *common.Position {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *MapSnapshotRequest) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

// MapSnapshotResponse 地图快照响应
type MapSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	Cells         []*CellData            `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`   // 视野内格子数据列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapSnapshotResponse) Reset() {
	*x = MapSnapshotResponse{}
	mi := &file_proto_world_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSnapshotResponse) ProtoMessage() {}

func (x *MapSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSnapshotResponse.ProtoReflect.Descriptor instead.
func (*MapSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{3}
}

func (x *MapSnapshotResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MapSnapshotResponse) GetCells() []*CellData {
	if x != nil {
		return x.Cells
	}
	return nil
}

// CellData 单个格子数据
type CellData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *common.Position       `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`                        // 格子坐标
	TerrainId     int32                  `protobuf:"varint,2,opt,name=terrain_id,json=terrainId,proto3" json:"terrain_id,omitempty"`    // 地形类型ID（规范8用int32）
	EntityId      int64                  `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`       // 格子上实体ID，0表示无实体
	EntityType    int32                  `protobuf:"varint,4,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // 实体类型：1=玩家 2=NPC 3=建筑
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellData) Reset() {
	*x = CellData{}
	mi := &file_proto_world_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellData) ProtoMessage() {}

func (x *CellData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellData.ProtoReflect.Descriptor instead.
func (*CellData) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{4}
}

func (x *CellData) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CellData) GetTerrainId() int32 {
	if x != nil {
		return x.TerrainId
	}
	return 0
}

func (x *CellData) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *CellData) GetEntityType() int32 {
	if x != nil {
		return x.EntityType
	}
	return 0
}

// CheckPassableRequest 查询可通行性请求
type CheckPassableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	MapId         int64                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`          // 地图ID
	From          *common.Position       `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`                          // 起点坐标
	To            *common.Position       `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`                              // 终点坐标
	EntityId      int64                  `protobuf:"varint,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 移动实体ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPassableRequest) Reset() {
	*x = CheckPassableRequest{}
	mi := &file_proto_world_world_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPassableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPassableRequest) ProtoMessage() {}

func (x *CheckPassableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPassableRequest.ProtoReflect.Descriptor instead.
func (*CheckPassableRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{5}
}

func (x *CheckPassableRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CheckPassableRequest) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CheckPassableRequest) GetFrom() *common.Position {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CheckPassableRequest) GetTo() *common.Position {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *CheckPassableRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

// CheckPassableResponse 可通行性响应
type CheckPassableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`      // 响应头
	Passable      bool                   `protobuf:"varint,2,opt,name=passable,proto3" json:"passable,omitempty"` // 是否可通行
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPassableResponse) Reset() {
	*x = CheckPassableResponse{}
	mi := &file_proto_world_world_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPassableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPassableResponse) ProtoMessage() {}

func (x *CheckPassableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPassableResponse.ProtoReflect.Descriptor instead.
func (*CheckPassableResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPassableResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CheckPassableResponse) GetPassable() bool {
	if x != nil {
		return x.Passable
	}
	return false
}

// TerrainInfoRequest 查询地形信息请求（新增接口）
type TerrainInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`             // 请求头
	MapId         int64                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"` // 地图ID
	Position      *common.Position       `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`         // 查询坐标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerrainInfoRequest) Reset() {
	*x = TerrainInfoRequest{}
	mi := &file_proto_world_world_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerrainInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerrainInfoRequest) ProtoMessage() {}

func (x *TerrainInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerrainInfoRequest.ProtoReflect.Descriptor instead.
func (*TerrainInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{7}
}

func (x *TerrainInfoRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TerrainInfoRequest) GetMapId() int64 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *TerrainInfoRequest) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// TerrainInfoResponse 地形信息响应（新增接口）
type TerrainInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                  // 响应头
	TerrainId     int32                  `protobuf:"varint,2,opt,name=terrain_id,json=terrainId,proto3" json:"terrain_id,omitempty"`          // 地形类型ID（规范8用int32）
	MoveCost      int64                  `protobuf:"varint,3,opt,name=move_cost,json=moveCost,proto3" json:"move_cost,omitempty"`             // 移动力消耗（规范8用int64）
	DefenseBonus  int64                  `protobuf:"varint,4,opt,name=defense_bonus,json=defenseBonus,proto3" json:"defense_bonus,omitempty"` // 防御加成百分比
	IsBlock       bool                   `protobuf:"varint,5,opt,name=is_block,json=isBlock,proto3" json:"is_block,omitempty"`                // 是否阻挡移动
	IsBuildable   bool                   `protobuf:"varint,6,opt,name=is_buildable,json=isBuildable,proto3" json:"is_buildable,omitempty"`    // 是否可建造
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerrainInfoResponse) Reset() {
	*x = TerrainInfoResponse{}
	mi := &file_proto_world_world_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerrainInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerrainInfoResponse) ProtoMessage() {}

func (x *TerrainInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerrainInfoResponse.ProtoReflect.Descriptor instead.
func (*TerrainInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{8}
}

func (x *TerrainInfoResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TerrainInfoResponse) GetTerrainId() int32 {
	if x != nil {
		return x.TerrainId
	}
	return 0
}

func (x *TerrainInfoResponse) GetMoveCost() int64 {
	if x != nil {
		return x.MoveCost
	}
	return 0
}

func (x *TerrainInfoResponse) GetDefenseBonus() int64 {
	if x != nil {
		return x.DefenseBonus
	}
	return 0
}

func (x *TerrainInfoResponse) GetIsBlock() bool {
	if x != nil {
		return x.IsBlock
	}
	return false
}

func (x *TerrainInfoResponse) GetIsBuildable() bool {
	if x != nil {
		return x.IsBuildable
	}
	return false
}

// VisionRequest 查询视野格子请求（新增接口）
type VisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 实体ID，查询该实体的可见格子
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisionRequest) Reset() {
	*x = VisionRequest{}
	mi := &file_proto_world_world_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisionRequest) ProtoMessage() {}

func (x *VisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisionRequest.ProtoReflect.Descriptor instead.
func (*VisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{9}
}

func (x *VisionRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *VisionRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

// VisionResponse 视野格子响应（新增接口）
type VisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	Cells         []*common.Position     `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`   // 可见格子坐标列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisionResponse) Reset() {
	*x = VisionResponse{}
	mi := &file_proto_world_world_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisionResponse) ProtoMessage() {}

func (x *VisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisionResponse.ProtoReflect.Descriptor instead.
func (*VisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{10}
}

func (x *VisionResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *VisionResponse) GetCells() []*common.Position {
	if x != nil {
		return x.Cells
	}
	return nil
}

var File_proto_world_world_proto protoreflect.FileDescriptor

const file_proto_world_world_proto_rawDesc = "" +
	"\n" +
	"\x17proto/world/world.proto\x12\x11insectworld.world\x1a\x19proto/common/common.proto\"l\n" +
	"\x12GetPositionRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\"\xd1\x01\n" +
	"\x10PositionResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x128\n" +
	"\bposition\x18\x02 \x01(\v2\x1c.insectworld.common.PositionR\bposition\x12\x1f\n" +
	"\vmove_status\x18\x03 \x01(\x05R\n" +
	"moveStatus\x12&\n" +
	"\x0fmove_start_time\x18\x04 \x01(\x03R\rmoveStartTime\"\xb4\x01\n" +
	"\x12MapSnapshotRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x03R\x05mapId\x124\n" +
	"\x06center\x18\x03 \x01(\v2\x1c.insectworld.common.PositionR\x06center\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x05R\x06radius\"\x84\x01\n" +
	"\x13MapSnapshotResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x121\n" +
	"\x05cells\x18\x02 \x03(\v2\x1b.insectworld.world.CellDataR\x05cells\"\xa1\x01\n" +
	"\bCellData\x128\n" +
	"\bposition\x18\x01 \x01(\v2\x1c.insectworld.common.PositionR\bposition\x12\x1d\n" +
	"\n" +
	"terrain_id\x18\x02 \x01(\x05R\tterrainId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x03R\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x04 \x01(\x05R\n" +
	"entityType\"\xe5\x01\n" +
	"\x14CheckPassableRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x03R\x05mapId\x120\n" +
	"\x04from\x18\x03 \x01(\v2\x1c.insectworld.common.PositionR\x04from\x12,\n" +
	"\x02to\x18\x04 \x01(\v2\x1c.insectworld.common.PositionR\x02to\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\x03R\bentityId\"o\n" +
	"\x15CheckPassableResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1a\n" +
	"\bpassable\x18\x02 \x01(\bR\bpassable\"\xa0\x01\n" +
	"\x12TerrainInfoRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x03R\x05mapId\x128\n" +
	"\bposition\x18\x03 \x01(\v2\x1c.insectworld.common.PositionR\bposition\"\xf0\x01\n" +
	"\x13TerrainInfoResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"terrain_id\x18\x02 \x01(\x05R\tterrainId\x12\x1b\n" +
	"\tmove_cost\x18\x03 \x01(\x03R\bmoveCost\x12#\n" +
	"\rdefense_bonus\x18\x04 \x01(\x03R\fdefenseBonus\x12\x19\n" +
	"\bis_block\x18\x05 \x01(\bR\aisBlock\x12!\n" +
	"\fis_buildable\x18\x06 \x01(\bR\visBuildable\"g\n" +
	"\rVisionRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\"\x80\x01\n" +
	"\x0eVisionResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x122\n" +
	"\x05cells\x18\x02 \x03(\v2\x1c.insectworld.common.PositionR\x05cells2\xec\x03\n" +
	"\fWorldService\x12_\n" +
	"\x11GetEntityPosition\x12%.insectworld.world.GetPositionRequest\x1a#.insectworld.world.PositionResponse\x12_\n" +
	"\x0eGetMapSnapshot\x12%.insectworld.world.MapSnapshotRequest\x1a&.insectworld.world.MapSnapshotResponse\x12b\n" +
	"\rCheckPassable\x12'.insectworld.world.CheckPassableRequest\x1a(.insectworld.world.CheckPassableResponse\x12_\n" +
	"\x0eGetTerrainInfo\x12%.insectworld.world.TerrainInfoRequest\x1a&.insectworld.world.TerrainInfoResponse\x12U\n" +
	"\x0eGetVisionCells\x12 .insectworld.world.VisionRequest\x1a!.insectworld.world.VisionResponseB!Z\x1finsectworld/server/shared/proto/world;worldpbb\x06proto3"

var (
	file_proto_world_world_proto_rawDescOnce sync.Once
	file_proto_world_world_proto_rawDescData []byte
)

func file_proto_world_world_proto_rawDescGZIP() []byte {
	file_proto_world_world_proto_rawDescOnce.Do(func() {
		file_proto_world_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_world_world_proto_rawDesc), len(file_proto_world_world_proto_rawDesc)))
	})
	return file_proto_world_world_proto_rawDescData
}

var file_proto_world_world_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_world_world_proto_goTypes = []any{
	(*GetPositionRequest)(nil),    // 0: insectworld.world.GetPositionRequest
	(*PositionResponse)(nil),      // 1: insectworld.world.PositionResponse
	(*MapSnapshotRequest)(nil),    // 2: insectworld.world.MapSnapshotRequest
	(*MapSnapshotResponse)(nil),   // 3: insectworld.world.MapSnapshotResponse
	(*CellData)(nil),              // 4: insectworld.world.CellData
	(*CheckPassableRequest)(nil),  // 5: insectworld.world.CheckPassableRequest
	(*CheckPassableResponse)(nil), // 6: insectworld.world.CheckPassableResponse
	(*TerrainInfoRequest)(nil),    // 7: insectworld.world.TerrainInfoRequest
	(*TerrainInfoResponse)(nil),   // 8: insectworld.world.TerrainInfoResponse
	(*VisionRequest)(nil),         // 9: insectworld.world.VisionRequest
	(*VisionResponse)(nil),        // 10: insectworld.world.VisionResponse
	(*common.RequestHeader)(nil),  // 11: insectworld.common.RequestHeader
	(*common.ResponseHeader)(nil), // 12: insectworld.common.ResponseHeader
	(*common.Position)(nil),       // 13: insectworld.common.Position
}
var file_proto_world_world_proto_depIdxs = []int32{
	11, // 0: insectworld.world.GetPositionRequest.header:type_name -> insectworld.common.RequestHeader
	12, // 1: insectworld.world.PositionResponse.header:type_name -> insectworld.common.ResponseHeader
	13, // 2: insectworld.world.PositionResponse.position:type_name -> insectworld.common.Position
	11, // 3: insectworld.world.MapSnapshotRequest.header:type_name -> insectworld.common.RequestHeader
	13, // 4: insectworld.world.MapSnapshotRequest.center:type_name -> insectworld.common.Position
	12, // 5: insectworld.world.MapSnapshotResponse.header:type_name -> insectworld.common.ResponseHeader
	4,  // 6: insectworld.world.MapSnapshotResponse.cells:type_name -> insectworld.world.CellData
	13, // 7: insectworld.world.CellData.position:type_name -> insectworld.common.Position
	11, // 8: insectworld.world.CheckPassableRequest.header:type_name -> insectworld.common.RequestHeader
	13, // 9: insectworld.world.CheckPassableRequest.from:type_name -> insectworld.common.Position
	13, // 10: insectworld.world.CheckPassableRequest.to:type_name -> insectworld.common.Position
	12, // 11: insectworld.world.CheckPassableResponse.header:type_name -> insectworld.common.ResponseHeader
	11, // 12: insectworld.world.TerrainInfoRequest.header:type_name -> insectworld.common.RequestHeader
	13, // 13: insectworld.world.TerrainInfoRequest.position:type_name -> insectworld.common.Position
	12, // 14: insectworld.world.TerrainInfoResponse.header:type_name -> insectworld.common.ResponseHeader
	11, // 15: insectworld.world.VisionRequest.header:type_name -> insectworld.common.RequestHeader
	12, // 16: insectworld.world.VisionResponse.header:type_name -> insectworld.common.ResponseHeader
	13, // 17: insectworld.world.VisionResponse.cells:type_name -> insectworld.common.Position
	0,  // 18: insectworld.world.WorldService.GetEntityPosition:input_type -> insectworld.world.GetPositionRequest
	2,  // 19: insectworld.world.WorldService.GetMapSnapshot:input_type -> insectworld.world.MapSnapshotRequest
	5,  // 20: insectworld.world.WorldService.CheckPassable:input_type -> insectworld.world.CheckPassableRequest
	7,  // 21: insectworld.world.WorldService.GetTerrainInfo:input_type -> insectworld.world.TerrainInfoRequest
	9,  // 22: insectworld.world.WorldService.GetVisionCells:input_type -> insectworld.world.VisionRequest
	1,  // 23: insectworld.world.WorldService.GetEntityPosition:output_type -> insectworld.world.PositionResponse
	3,  // 24: insectworld.world.WorldService.GetMapSnapshot:output_type -> insectworld.world.MapSnapshotResponse
	6,  // 25: insectworld.world.WorldService.CheckPassable:output_type -> insectworld.world.CheckPassableResponse
	8,  // 26: insectworld.world.WorldService.GetTerrainInfo:output_type -> insectworld.world.TerrainInfoResponse
	10, // 27: insectworld.world.WorldService.GetVisionCells:output_type -> insectworld.world.VisionResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_world_world_proto_init() }
func file_proto_world_world_proto_init() {
	if File_proto_world_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_world_world_proto_rawDesc), len(file_proto_world_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_world_world_proto_goTypes,
		DependencyIndexes: file_proto_world_world_proto_depIdxs,
		MessageInfos:      file_proto_world_world_proto_msgTypes,
	}.Build()
	File_proto_world_world_proto = out.File
	file_proto_world_world_proto_goTypes = nil
	file_proto_world_world_proto_depIdxs = nil
}
