// Inventory Service gRPC接口定义，提供背包道具查询/使用/堆叠拆分合并相关操作。
// 对应《通用SLG框架共性抽离方案_终版》P0-4 背包/道具骨头（#16）与《契约冻结草案》4.3 清单。
// 背包是邮件附件/商店商品/活动奖励的公共底层，item契约最先冻结。
// 契约冻结规则：本包为P3新增包 v1 冻结，字段编号不重用、消息只增不改、服务只加不改。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: proto/inventory/inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	event "insectworld/server/shared/proto/event"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InventoryItem 背包道具堆叠，同一道具配置可存在多个堆叠实例。
type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    int64                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 堆叠实例ID，全局唯一，拆分/合并/使用按实例定位（规范8用int64）
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`             // 道具配置ID，对应items配置表（规范8用int32）
	StackCount    int64                  `protobuf:"varint,3,opt,name=stack_count,json=stackCount,proto3" json:"stack_count,omitempty"` // 堆叠数量，受配置的堆叠上限约束（规范8用int64）
	ExpireTime    int64                  `protobuf:"varint,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间戳（毫秒），0表示永不过期
	Bound         bool                   `protobuf:"varint,5,opt,name=bound,proto3" json:"bound,omitempty"`                             // 是否绑定，绑定道具不可交易/不可丢弃
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryItem) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *InventoryItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *InventoryItem) GetStackCount() int64 {
	if x != nil {
		return x.StackCount
	}
	return 0
}

func (x *InventoryItem) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *InventoryItem) GetBound() bool {
	if x != nil {
		return x.Bound
	}
	return false
}

// GetInventoryRequest 查询背包请求
type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`         // 请求头
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetInventoryRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetInventoryRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// GetInventoryResponse 查询背包响应
type GetInventoryResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Header        *common.ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`         // 响应头
	Items         []*InventoryItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`           // 背包道具堆叠列表
	Pagination    *common.PaginationResult `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetInventoryResponse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetInventoryResponse) GetPagination() *common.PaginationResult {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// UseItemRequest 使用道具请求
type UseItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                            // 请求头
	InstanceId    int64                  `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 堆叠实例ID
	UseCount      int64                  `protobuf:"varint,3,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`       // 使用数量，必须小于等于当前堆叠数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemRequest) Reset() {
	*x = UseItemRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemRequest) ProtoMessage() {}

func (x *UseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemRequest.ProtoReflect.Descriptor instead.
func (*UseItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *UseItemRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UseItemRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *UseItemRequest) GetUseCount() int64 {
	if x != nil {
		return x.UseCount
	}
	return 0
}

// UseItemResponse 使用道具响应
type UseItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	Item          *InventoryItem         `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`     // 使用后的道具堆叠，数量为0时表示已消耗清空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemResponse) Reset() {
	*x = UseItemResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemResponse) ProtoMessage() {}

func (x *UseItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemResponse.ProtoReflect.Descriptor instead.
func (*UseItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *UseItemResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UseItemResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// SplitStackRequest 拆分堆叠请求
type SplitStackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                            // 请求头
	InstanceId    int64                  `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 源堆叠实例ID
	SplitCount    int64                  `protobuf:"varint,3,opt,name=split_count,json=splitCount,proto3" json:"split_count,omitempty"` // 拆分数量，拆出的新堆叠数量，须小于源堆叠数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitStackRequest) Reset() {
	*x = SplitStackRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitStackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitStackRequest) ProtoMessage() {}

func (x *SplitStackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitStackRequest.ProtoReflect.Descriptor instead.
func (*SplitStackRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *SplitStackRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SplitStackRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *SplitStackRequest) GetSplitCount() int64 {
	if x != nil {
		return x.SplitCount
	}
	return 0
}

// SplitStackResponse 拆分堆叠响应
type SplitStackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                     // 响应头
	Original      *InventoryItem         `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`                 // 拆分后的源堆叠
	NewStack      *InventoryItem         `protobuf:"bytes,3,opt,name=new_stack,json=newStack,proto3" json:"new_stack,omitempty"` // 拆分产生的新堆叠
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitStackResponse) Reset() {
	*x = SplitStackResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitStackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitStackResponse) ProtoMessage() {}

func (x *SplitStackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitStackResponse.ProtoReflect.Descriptor instead.
func (*SplitStackResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *SplitStackResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SplitStackResponse) GetOriginal() *InventoryItem {
	if x != nil {
		return x.Original
	}
	return nil
}

func (x *SplitStackResponse) GetNewStack() *InventoryItem {
	if x != nil {
		return x.NewStack
	}
	return nil
}

// MergeStackRequest 合并堆叠请求
type MergeStackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Header         *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                          // 请求头
	FromInstanceId int64                  `protobuf:"varint,2,opt,name=from_instance_id,json=fromInstanceId,proto3" json:"from_instance_id,omitempty"` // 被合并的源堆叠实例ID，合并后清空
	ToInstanceId   int64                  `protobuf:"varint,3,opt,name=to_instance_id,json=toInstanceId,proto3" json:"to_instance_id,omitempty"`       // 合并目标堆叠实例ID，须为同道具配置
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MergeStackRequest) Reset() {
	*x = MergeStackRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeStackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeStackRequest) ProtoMessage() {}

func (x *MergeStackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeStackRequest.ProtoReflect.Descriptor instead.
func (*MergeStackRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *MergeStackRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MergeStackRequest) GetFromInstanceId() int64 {
	if x != nil {
		return x.FromInstanceId
	}
	return 0
}

func (x *MergeStackRequest) GetToInstanceId() int64 {
	if x != nil {
		return x.ToInstanceId
	}
	return 0
}

// MergeStackResponse 合并堆叠响应
type MergeStackResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Header            *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                                   // 响应头
	Merged            *InventoryItem         `protobuf:"bytes,2,opt,name=merged,proto3" json:"merged,omitempty"`                                                   // 合并后的目标堆叠
	RemovedInstanceId int64                  `protobuf:"varint,3,opt,name=removed_instance_id,json=removedInstanceId,proto3" json:"removed_instance_id,omitempty"` // 被合并清空的堆叠实例ID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MergeStackResponse) Reset() {
	*x = MergeStackResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeStackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeStackResponse) ProtoMessage() {}

func (x *MergeStackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeStackResponse.ProtoReflect.Descriptor instead.
func (*MergeStackResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *MergeStackResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MergeStackResponse) GetMerged() *InventoryItem {
	if x != nil {
		return x.Merged
	}
	return nil
}

func (x *MergeStackResponse) GetRemovedInstanceId() int64 {
	if x != nil {
		return x.RemovedInstanceId
	}
	return 0
}

// ItemAddedEvent 道具入包事件，获得道具后发布。
// 主题命名 event.inventory.item_added，订阅方用于背包计数与红点提示。
type ItemAddedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                // 基础事件信息
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`       // 获得道具的玩家ID
	InstanceId    int64                  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 堆叠实例ID
	ItemId        int32                  `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`             // 道具配置ID
	StackCount    int64                  `protobuf:"varint,5,opt,name=stack_count,json=stackCount,proto3" json:"stack_count,omitempty"` // 新增数量
	Reason        int32                  `protobuf:"varint,6,opt,name=reason,proto3" json:"reason,omitempty"`                           // 获得途径：1=掉落 2=奖励 3=购买 4=合成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAddedEvent) Reset() {
	*x = ItemAddedEvent{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAddedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAddedEvent) ProtoMessage() {}

func (x *ItemAddedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAddedEvent.ProtoReflect.Descriptor instead.
func (*ItemAddedEvent) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *ItemAddedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ItemAddedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ItemAddedEvent) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *ItemAddedEvent) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemAddedEvent) GetStackCount() int64 {
	if x != nil {
		return x.StackCount
	}
	return 0
}

func (x *ItemAddedEvent) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// ItemUsedEvent 道具使用事件，道具被使用后发布。
// 主题命名 event.inventory.item_used，订阅方用于道具消耗统计与效果结算。
type ItemUsedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                // 基础事件信息
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`       // 使用道具的玩家ID
	InstanceId    int64                  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 堆叠实例ID
	ItemId        int32                  `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`             // 道具配置ID
	UseCount      int64                  `protobuf:"varint,5,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`       // 使用数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUsedEvent) Reset() {
	*x = ItemUsedEvent{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUsedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUsedEvent) ProtoMessage() {}

func (x *ItemUsedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUsedEvent.ProtoReflect.Descriptor instead.
func (*ItemUsedEvent) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *ItemUsedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ItemUsedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ItemUsedEvent) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *ItemUsedEvent) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemUsedEvent) GetUseCount() int64 {
	if x != nil {
		return x.UseCount
	}
	return 0
}

// ItemExpiredEvent 道具过期事件，到达过期时间的道具被系统清除后发布。
// 主题命名 event.inventory.item_expired，订阅方用于过期清理补偿或统计。
type ItemExpiredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                      // 基础事件信息
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`             // 道具所属玩家ID
	InstanceId    int64                  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`       // 堆叠实例ID
	ItemId        int32                  `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                   // 道具配置ID
	ExpiredCount  int64                  `protobuf:"varint,5,opt,name=expired_count,json=expiredCount,proto3" json:"expired_count,omitempty"` // 过期清除的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemExpiredEvent) Reset() {
	*x = ItemExpiredEvent{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemExpiredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemExpiredEvent) ProtoMessage() {}

func (x *ItemExpiredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemExpiredEvent.ProtoReflect.Descriptor instead.
func (*ItemExpiredEvent) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *ItemExpiredEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ItemExpiredEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ItemExpiredEvent) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *ItemExpiredEvent) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemExpiredEvent) GetExpiredCount() int64 {
	if x != nil {
		return x.ExpiredCount
	}
	return 0
}

// ItemStackChangedEvent 堆叠变更事件，拆分/合并/数量变化后发布。
// 主题命名 event.inventory.stack_changed，订阅方用于背包界面增量刷新。
type ItemStackChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                // 基础事件信息
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`       // 背包所属玩家ID
	InstanceId    int64                  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 发生变更的堆叠实例ID
	ItemId        int32                  `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`             // 道具配置ID
	OldCount      int64                  `protobuf:"varint,5,opt,name=old_count,json=oldCount,proto3" json:"old_count,omitempty"`       // 变更前数量
	NewCount      int64                  `protobuf:"varint,6,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`       // 变更后数量
	ChangeType    int32                  `protobuf:"varint,7,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"` // 变更类型：1=拆分 2=合并 3=消耗
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStackChangedEvent) Reset() {
	*x = ItemStackChangedEvent{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStackChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStackChangedEvent) ProtoMessage() {}

func (x *ItemStackChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStackChangedEvent.ProtoReflect.Descriptor instead.
func (*ItemStackChangedEvent) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *ItemStackChangedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ItemStackChangedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ItemStackChangedEvent) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *ItemStackChangedEvent) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemStackChangedEvent) GetOldCount() int64 {
	if x != nil {
		return x.OldCount
	}
	return 0
}

func (x *ItemStackChangedEvent) GetNewCount() int64 {
	if x != nil {
		return x.NewCount
	}
	return 0
}

func (x *ItemStackChangedEvent) GetChangeType() int32 {
	if x != nil {
		return x.ChangeType
	}
	return 0
}

var File_proto_inventory_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/inventory/inventory.proto\x12\x15insectworld.inventory\x1a\x19proto/common/common.proto\x1a\x1eproto/event/domain_event.proto\"\xa1\x01\n" +
	"\rInventoryItem\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x03R\n" +
	"instanceId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x1f\n" +
	"\vstack_count\x18\x03 \x01(\x03R\n" +
	"stackCount\x12\x1f\n" +
	"\vexpire_time\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x14\n" +
	"\x05bound\x18\x05 \x01(\bR\x05bound\"\x90\x01\n" +
	"\x13GetInventoryRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.insectworld.common.PaginationR\n" +
	"pagination\"\xd4\x01\n" +
	"\x14GetInventoryResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12:\n" +
	"\x05items\x18\x02 \x03(\v2$.insectworld.inventory.InventoryItemR\x05items\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.insectworld.common.PaginationResultR\n" +
	"pagination\"\x89\x01\n" +
	"\x0eUseItemRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\x03R\n" +
	"instanceId\x12\x1b\n" +
	"\tuse_count\x18\x03 \x01(\x03R\buseCount\"\x87\x01\n" +
	"\x0fUseItemResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x128\n" +
	"\x04item\x18\x02 \x01(\v2$.insectworld.inventory.InventoryItemR\x04item\"\x90\x01\n" +
	"\x11SplitStackRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\x03R\n" +
	"instanceId\x12\x1f\n" +
	"\vsplit_count\x18\x03 \x01(\x03R\n" +
	"splitCount\"\xd5\x01\n" +
	"\x12SplitStackResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12@\n" +
	"\boriginal\x18\x02 \x01(\v2$.insectworld.inventory.InventoryItemR\boriginal\x12A\n" +
	"\tnew_stack\x18\x03 \x01(\v2$.insectworld.inventory.InventoryItemR\bnewStack\"\x9e\x01\n" +
	"\x11MergeStackRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12(\n" +
	"\x10from_instance_id\x18\x02 \x01(\x03R\x0efromInstanceId\x12$\n" +
	"\x0eto_instance_id\x18\x03 \x01(\x03R\ftoInstanceId\"\xbe\x01\n" +
	"\x12MergeStackResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12<\n" +
	"\x06merged\x18\x02 \x01(\v2$.insectworld.inventory.InventoryItemR\x06merged\x12.\n" +
	"\x13removed_instance_id\x18\x03 \x01(\x03R\x11removedInstanceId\"\xd4\x01\n" +
	"\x0eItemAddedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\x03R\n" +
	"instanceId\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\x05R\x06itemId\x12\x1f\n" +
	"\vstack_count\x18\x05 \x01(\x03R\n" +
	"stackCount\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\x05R\x06reason\"\xb7\x01\n" +
	"\rItemUsedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\x03R\n" +
	"instanceId\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\x05R\x06itemId\x12\x1b\n" +
	"\tuse_count\x18\x05 \x01(\x03R\buseCount\"\xc2\x01\n" +
	"\x10ItemExpiredEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\x03R\n" +
	"instanceId\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\x05R\x06itemId\x12#\n" +
	"\rexpired_count\x18\x05 \x01(\x03R\fexpiredCount\"\xfd\x01\n" +
	"\x15ItemStackChangedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\x03R\n" +
	"instanceId\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\x05R\x06itemId\x12\x1b\n" +
	"\told_count\x18\x05 \x01(\x03R\boldCount\x12\x1b\n" +
	"\tnew_count\x18\x06 \x01(\x03R\bnewCount\x12\x1f\n" +
	"\vchange_type\x18\a \x01(\x05R\n" +
	"changeType2\x9b\x03\n" +
	"\x10InventoryService\x12g\n" +
	"\fGetInventory\x12*.insectworld.inventory.GetInventoryRequest\x1a+.insectworld.inventory.GetInventoryResponse\x12X\n" +
	"\aUseItem\x12%.insectworld.inventory.UseItemRequest\x1a&.insectworld.inventory.UseItemResponse\x12a\n" +
	"\n" +
	"SplitStack\x12(.insectworld.inventory.SplitStackRequest\x1a).insectworld.inventory.SplitStackResponse\x12a\n" +
	"\n" +
	"MergeStack\x12(.insectworld.inventory.MergeStackRequest\x1a).insectworld.inventory.MergeStackResponseB)Z'insectworld/proto/inventory;inventorypbb\x06proto3"

var (
	file_proto_inventory_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_inventory_proto_rawDescData []byte
)

func file_proto_inventory_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_inventory_proto_rawDesc), len(file_proto_inventory_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_inventory_proto_rawDescData
}

var file_proto_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_inventory_inventory_proto_goTypes = []any{
	(*InventoryItem)(nil),           // 0: insectworld.inventory.InventoryItem
	(*GetInventoryRequest)(nil),     // 1: insectworld.inventory.GetInventoryRequest
	(*GetInventoryResponse)(nil),    // 2: insectworld.inventory.GetInventoryResponse
	(*UseItemRequest)(nil),          // 3: insectworld.inventory.UseItemRequest
	(*UseItemResponse)(nil),         // 4: insectworld.inventory.UseItemResponse
	(*SplitStackRequest)(nil),       // 5: insectworld.inventory.SplitStackRequest
	(*SplitStackResponse)(nil),      // 6: insectworld.inventory.SplitStackResponse
	(*MergeStackRequest)(nil),       // 7: insectworld.inventory.MergeStackRequest
	(*MergeStackResponse)(nil),      // 8: insectworld.inventory.MergeStackResponse
	(*ItemAddedEvent)(nil),          // 9: insectworld.inventory.ItemAddedEvent
	(*ItemUsedEvent)(nil),           // 10: insectworld.inventory.ItemUsedEvent
	(*ItemExpiredEvent)(nil),        // 11: insectworld.inventory.ItemExpiredEvent
	(*ItemStackChangedEvent)(nil),   // 12: insectworld.inventory.ItemStackChangedEvent
	(*common.RequestHeader)(nil),    // 13: insectworld.common.RequestHeader
	(*common.Pagination)(nil),       // 14: insectworld.common.Pagination
	(*common.ResponseHeader)(nil),   // 15: insectworld.common.ResponseHeader
	(*common.PaginationResult)(nil), // 16: insectworld.common.PaginationResult
	(*event.DomainEvent)(nil),       // 17: insectworld.event.DomainEvent
}
var file_proto_inventory_inventory_proto_depIdxs = []int32{
	13, // 0: insectworld.inventory.GetInventoryRequest.header:type_name -> insectworld.common.RequestHeader
	14, // 1: insectworld.inventory.GetInventoryRequest.pagination:type_name -> insectworld.common.Pagination
	15, // 2: insectworld.inventory.GetInventoryResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 3: insectworld.inventory.GetInventoryResponse.items:type_name -> insectworld.inventory.InventoryItem
	16, // 4: insectworld.inventory.GetInventoryResponse.pagination:type_name -> insectworld.common.PaginationResult
	13, // 5: insectworld.inventory.UseItemRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 6: insectworld.inventory.UseItemResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 7: insectworld.inventory.UseItemResponse.item:type_name -> insectworld.inventory.InventoryItem
	13, // 8: insectworld.inventory.SplitStackRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 9: insectworld.inventory.SplitStackResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 10: insectworld.inventory.SplitStackResponse.original:type_name -> insectworld.inventory.InventoryItem
	0,  // 11: insectworld.inventory.SplitStackResponse.new_stack:type_name -> insectworld.inventory.InventoryItem
	13, // 12: insectworld.inventory.MergeStackRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 13: insectworld.inventory.MergeStackResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 14: insectworld.inventory.MergeStackResponse.merged:type_name -> insectworld.inventory.InventoryItem
	17, // 15: insectworld.inventory.ItemAddedEvent.base:type_name -> insectworld.event.DomainEvent
	17, // 16: insectworld.inventory.ItemUsedEvent.base:type_name -> insectworld.event.DomainEvent
	17, // 17: insectworld.inventory.ItemExpiredEvent.base:type_name -> insectworld.event.DomainEvent
	17, // 18: insectworld.inventory.ItemStackChangedEvent.base:type_name -> insectworld.event.DomainEvent
	1,  // 19: insectworld.inventory.InventoryService.GetInventory:input_type -> insectworld.inventory.GetInventoryRequest
	3,  // 20: insectworld.inventory.InventoryService.UseItem:input_type -> insectworld.inventory.UseItemRequest
	5,  // 21: insectworld.inventory.InventoryService.SplitStack:input_type -> insectworld.inventory.SplitStackRequest
	7,  // 22: insectworld.inventory.InventoryService.MergeStack:input_type -> insectworld.inventory.MergeStackRequest
	2,  // 23: insectworld.inventory.InventoryService.GetInventory:output_type -> insectworld.inventory.GetInventoryResponse
	4,  // 24: insectworld.inventory.InventoryService.UseItem:output_type -> insectworld.inventory.UseItemResponse
	6,  // 25: insectworld.inventory.InventoryService.SplitStack:output_type -> insectworld.inventory.SplitStackResponse
	8,  // 26: insectworld.inventory.InventoryService.MergeStack:output_type -> insectworld.inventory.MergeStackResponse
	23, // [23:27] is the sub-list for method output_type
	19, // [19:23] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_inventory_inventory_proto_init() }
func file_proto_inventory_inventory_proto_init() {
	if File_proto_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_inventory_proto_rawDesc), len(file_proto_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_inventory_proto = out.File
	file_proto_inventory_inventory_proto_goTypes = nil
	file_proto_inventory_inventory_proto_depIdxs = nil
}
