// Operation Service gRPC接口定义，提供赛季/排行/事件相关查询与操作。
// 对应design.md 2.2.2.5节接口清单，保留现有接口并新增历史与事件触发接口。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/operation/operation.proto

package operationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetSeasonRequest 查询当前赛季请求
type GetSeasonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 请求头
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeasonRequest) Reset() {
	*x = GetSeasonRequest{}
	mi := &file_proto_operation_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeasonRequest) ProtoMessage() {}

func (x *GetSeasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeasonRequest.ProtoReflect.Descriptor instead.
func (*GetSeasonRequest) Descriptor() ([]byte, []int) {
	return file_proto_operation_operation_proto_rawDescGZIP(), []int{0}
}

func (x *GetSeasonRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

// SeasonResponse 赛季响应
type SeasonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                    // 响应头
	SeasonId      int64                  `protobuf:"varint,2,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`               // 赛季ID（规范8用int64）
	Phase         int32                  `protobuf:"varint,3,opt,name=phase,proto3" json:"phase,omitempty"`                                     // 当前阶段：1=准备 2=战争 3=结算（规范8用int32）
	PhaseEndTime  int64                  `protobuf:"varint,4,opt,name=phase_end_time,json=phaseEndTime,proto3" json:"phase_end_time,omitempty"` // 阶段结束时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeasonResponse) Reset() {
	*x = SeasonResponse{}
	mi := &file_proto_operation_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonResponse) ProtoMessage() {}

func (x *SeasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonResponse.ProtoReflect.Descriptor instead.
func (*SeasonResponse) Descriptor() ([]byte, []int) {
	return file_proto_operation_operation_proto_rawDescGZIP(), []int{1}
}

func (x *SeasonResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SeasonResponse) GetSeasonId() int64 {
	if x != nil {
		return x.SeasonId
	}
	return 0
}

func (x *SeasonResponse) GetPhase() int32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *SeasonResponse) GetPhaseEndTime() int64 {
	if x != nil {
		return x.PhaseEndTime
	}
	return 0
}

// GetRankingRequest 查询排行榜请求
type GetRankingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                               // 请求头
	RankingType   int32                  `protobuf:"varint,2,opt,name=ranking_type,json=rankingType,proto3" json:"ranking_type,omitempty"` // 排行榜类型：1=玩家 2=联盟（规范8用int32）
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`                       // 分页参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingRequest) Reset() {
	*x = GetRankingRequest{}
	mi := &file_proto_operation_operation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingRequest) ProtoMessage() {}

func (x *GetRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_operation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingRequest.ProtoReflect.Descriptor instead.
func (*GetRankingRequest) Descriptor() ([]byte, []int) {
	return file_proto_operation_operation_proto_rawDescGZIP(), []int{2}
}

func (x *GetRankingRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetRankingRequest) GetRankingType() int32 {
	if x != nil {
		return x.RankingType
	}
	return 0
}

func (x *GetRankingRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// RankingResponse 排行榜响应
type RankingResponse struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Header           *common.ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                             // 响应头
	Items            []*RankingItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`                                               // 排行榜条目列表
	PaginationResult *common.PaginationResult `protobuf:"bytes,3,opt,name=pagination_result,json=paginationResult,proto3" json:"pagination_result,omitempty"` // 分页结果
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RankingResponse) Reset() {
	*x = RankingResponse{}
	mi := &file_proto_operation_operation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingResponse) ProtoMessage() {}

func (x *RankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_operation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingResponse.ProtoReflect.Descriptor instead.
func (*RankingResponse) Descriptor() ([]byte, []int) {
	return file_proto_operation_operation_proto_rawDescGZIP(), []int{3}
}

func (x *RankingResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RankingResponse) GetItems() []*RankingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RankingResponse) GetPaginationResult() *common.PaginationResult {
	if x != nil {
		return x.PaginationResult
	}
	return nil
}

// RankingItem 排行榜条目
type RankingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`                              // 排名
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`      // 目标ID（玩家ID或联盟ID）
	TargetName    string                 `protobuf:"bytes,3,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"` // 目标名称
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`                            // 积分（规范8用int64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankingItem) Reset() {
	*x = RankingItem{}
	mi := &file_proto_operation_operation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingItem) ProtoMessage() {}

func (x *RankingItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_operation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingItem.ProtoReflect.Descriptor instead.
func (*RankingItem) Descriptor() ([]byte, []int) {
	return file_proto_operation_operation_proto_rawDescGZIP(), []int{4}
}

func (x *RankingItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankingItem) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *RankingItem) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *RankingItem) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// SeasonHistoryRequest 查询历史赛季请求（新增接口）
type SeasonHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	SeasonId      int64                  `protobuf:"varint,2,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"` // 赛季ID，0表示查询最近赛季
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeasonHistoryRequest) Reset() {
	*x = SeasonHistoryRequest{}
	mi := &file_proto_operation_operation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonHistoryRequest) ProtoMessage() {}

func (x *SeasonHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_operation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonHistoryRequest.ProtoReflect.Descriptor instead.
func (*SeasonHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_operation_operation_proto_rawDescGZIP(), []int{5}
}

func (x *SeasonHistoryRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SeasonHistoryRequest) GetSeasonId() int64 {
	if x != nil {
		return x.SeasonId
	}
	return 0
}

// SeasonHistoryResponse 历史赛季响应（新增接口）
type SeasonHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                 // 响应头
	SeasonId      int64                  `protobuf:"varint,2,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`            // 赛季ID
	FinalPhase    int32                  `protobuf:"varint,3,opt,name=final_phase,json=finalPhase,proto3" json:"final_phase,omitempty"`      // 最终阶段
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`         // 赛季开始时间戳（毫秒）
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`               // 赛季结束时间戳（毫秒）
	Phases        []*PhaseTimeline       `protobuf:"bytes,6,rep,name=phases,proto3" json:"phases,omitempty"`                                 // 各阶段时间线
	FinalRanking  []*RankingItem         `protobuf:"bytes,7,rep,name=final_ranking,json=finalRanking,proto3" json:"final_ranking,omitempty"` // 最终排行榜
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeasonHistoryResponse) Reset() {
	*x = SeasonHistoryResponse{}
	mi := &file_proto_operation_operation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonHistoryResponse) ProtoMessage() {}

func (x *SeasonHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_operation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonHistoryResponse.ProtoReflect.Descriptor instead.
func (*SeasonHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_operation_operation_proto_rawDescGZIP(), []int{6}
}

func (x *SeasonHistoryResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SeasonHistoryResponse) GetSeasonId() int64 {
	if x != nil {
		return x.SeasonId
	}
	return 0
}

func (x *SeasonHistoryResponse) GetFinalPhase() int32 {
	if x != nil {
		return x.FinalPhase
	}
	return 0
}

func (x *SeasonHistoryResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SeasonHistoryResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SeasonHistoryResponse) GetPhases() []*PhaseTimeline {
	if x != nil {
		return x.Phases
	}
	return nil
}

func (x *SeasonHistoryResponse) GetFinalRanking() []*RankingItem {
	if x != nil {
		return x.FinalRanking
	}
	return nil
}

// PhaseTimeline 阶段时间线
type PhaseTimeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         int32                  `protobuf:"varint,1,opt,name=phase,proto3" json:"phase,omitempty"`                          // 阶段
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 阶段开始时间戳（毫秒）
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 阶段结束时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseTimeline) Reset() {
	*x = PhaseTimeline{}
	mi := &file_proto_operation_operation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseTimeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseTimeline) ProtoMessage() {}

func (x *PhaseTimeline) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_operation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseTimeline.ProtoReflect.Descriptor instead.
func (*PhaseTimeline) Descriptor() ([]byte, []int) {
	return file_proto_operation_operation_proto_rawDescGZIP(), []int{7}
}

func (x *PhaseTimeline) GetPhase() int32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *PhaseTimeline) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PhaseTimeline) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// TriggerEventRequest 触发游戏事件请求（新增接口）
type TriggerEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                   // 请求头
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // 事件ID（规范8用int64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEventRequest) Reset() {
	*x = TriggerEventRequest{}
	mi := &file_proto_operation_operation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEventRequest) ProtoMessage() {}

func (x *TriggerEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_operation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEventRequest.ProtoReflect.Descriptor instead.
func (*TriggerEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_operation_operation_proto_rawDescGZIP(), []int{8}
}

func (x *TriggerEventRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TriggerEventRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

// TriggerEventResponse 触发事件响应（新增接口）
type TriggerEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`        // 响应头
	Triggered     bool                   `protobuf:"varint,2,opt,name=triggered,proto3" json:"triggered,omitempty"` // 是否触发成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEventResponse) Reset() {
	*x = TriggerEventResponse{}
	mi := &file_proto_operation_operation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEventResponse) ProtoMessage() {}

func (x *TriggerEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_operation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEventResponse.ProtoReflect.Descriptor instead.
func (*TriggerEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_operation_operation_proto_rawDescGZIP(), []int{9}
}

func (x *TriggerEventResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TriggerEventResponse) GetTriggered() bool {
	if x != nil {
		return x.Triggered
	}
	return false
}

var File_proto_operation_operation_proto protoreflect.FileDescriptor

const file_proto_operation_operation_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/operation/operation.proto\x12\x15insectworld.operation\x1a\x19proto/common/common.proto\"M\n" +
	"\x10GetSeasonRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\"\xa5\x01\n" +
	"\x0eSeasonResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1b\n" +
	"\tseason_id\x18\x02 \x01(\x03R\bseasonId\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\x05R\x05phase\x12$\n" +
	"\x0ephase_end_time\x18\x04 \x01(\x03R\fphaseEndTime\"\xb1\x01\n" +
	"\x11GetRankingRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12!\n" +
	"\franking_type\x18\x02 \x01(\x05R\vrankingType\x12>\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1e.insectworld.common.PaginationR\n" +
	"pagination\"\xda\x01\n" +
	"\x0fRankingResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x128\n" +
	"\x05items\x18\x02 \x03(\v2\".insectworld.operation.RankingItemR\x05items\x12Q\n" +
	"\x11pagination_result\x18\x03 \x01(\v2$.insectworld.common.PaginationResultR\x10paginationResult\"u\n" +
	"\vRankingItem\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x1f\n" +
	"\vtarget_name\x18\x03 \x01(\tR\n" +
	"targetName\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\"n\n" +
	"\x14SeasonHistoryRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1b\n" +
	"\tseason_id\x18\x02 \x01(\x03R\bseasonId\"\xd2\x02\n" +
	"\x15SeasonHistoryResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1b\n" +
	"\tseason_id\x18\x02 \x01(\x03R\bseasonId\x12\x1f\n" +
	"\vfinal_phase\x18\x03 \x01(\x05R\n" +
	"finalPhase\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12<\n" +
	"\x06phases\x18\x06 \x03(\v2$.insectworld.operation.PhaseTimelineR\x06phases\x12G\n" +
	"\rfinal_ranking\x18\a \x03(\v2\".insectworld.operation.RankingItemR\ffinalRanking\"_\n" +
	"\rPhaseTimeline\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\x05R\x05phase\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\"k\n" +
	"\x13TriggerEventRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\"p\n" +
	"\x14TriggerEventResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1c\n" +
	"\ttriggered\x18\x02 \x01(\bR\ttriggered2\xb2\x03\n" +
	"\x10OperationService\x12b\n" +
	"\x10GetCurrentSeason\x12'.insectworld.operation.GetSeasonRequest\x1a%.insectworld.operation.SeasonResponse\x12^\n" +
	"\n" +
	"GetRanking\x12(.insectworld.operation.GetRankingRequest\x1a&.insectworld.operation.RankingResponse\x12m\n" +
	"\x10GetSeasonHistory\x12+.insectworld.operation.SeasonHistoryRequest\x1a,.insectworld.operation.SeasonHistoryResponse\x12k\n" +
	"\x10TriggerGameEvent\x12*.insectworld.operation.TriggerEventRequest\x1a+.insectworld.operation.TriggerEventResponseB)Z'insectworld/proto/operation;operationpbb\x06proto3"

var (
	file_proto_operation_operation_proto_rawDescOnce sync.Once
	file_proto_operation_operation_proto_rawDescData []byte
)

func file_proto_operation_operation_proto_rawDescGZIP() []byte {
	file_proto_operation_operation_proto_rawDescOnce.Do(func() {
		file_proto_operation_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_operation_operation_proto_rawDesc), len(file_proto_operation_operation_proto_rawDesc)))
	})
	return file_proto_operation_operation_proto_rawDescData
}

var file_proto_operation_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_operation_operation_proto_goTypes = []any{
	(*GetSeasonRequest)(nil),        // 0: insectworld.operation.GetSeasonRequest
	(*SeasonResponse)(nil),          // 1: insectworld.operation.SeasonResponse
	(*GetRankingRequest)(nil),       // 2: insectworld.operation.GetRankingRequest
	(*RankingResponse)(nil),         // 3: insectworld.operation.RankingResponse
	(*RankingItem)(nil),             // 4: insectworld.operation.RankingItem
	(*SeasonHistoryRequest)(nil),    // 5: insectworld.operation.SeasonHistoryRequest
	(*SeasonHistoryResponse)(nil),   // 6: insectworld.operation.SeasonHistoryResponse
	(*PhaseTimeline)(nil),           // 7: insectworld.operation.PhaseTimeline
	(*TriggerEventRequest)(nil),     // 8: insectworld.operation.TriggerEventRequest
	(*TriggerEventResponse)(nil),    // 9: insectworld.operation.TriggerEventResponse
	(*common.RequestHeader)(nil),    // 10: insectworld.common.RequestHeader
	(*common.ResponseHeader)(nil),   // 11: insectworld.common.ResponseHeader
	(*common.Pagination)(nil),       // 12: insectworld.common.Pagination
	(*common.PaginationResult)(nil), // 13: insectworld.common.PaginationResult
}
var file_proto_operation_operation_proto_depIdxs = []int32{
	10, // 0: insectworld.operation.GetSeasonRequest.header:type_name -> insectworld.common.RequestHeader
	11, // 1: insectworld.operation.SeasonResponse.header:type_name -> insectworld.common.ResponseHeader
	10, // 2: insectworld.operation.GetRankingRequest.header:type_name -> insectworld.common.RequestHeader
	12, // 3: insectworld.operation.GetRankingRequest.pagination:type_name -> insectworld.common.Pagination
	11, // 4: insectworld.operation.RankingResponse.header:type_name -> insectworld.common.ResponseHeader
	4,  // 5: insectworld.operation.RankingResponse.items:type_name -> insectworld.operation.RankingItem
	13, // 6: insectworld.operation.RankingResponse.pagination_result:type_name -> insectworld.common.PaginationResult
	10, // 7: insectworld.operation.SeasonHistoryRequest.header:type_name -> insectworld.common.RequestHeader
	11, // 8: insectworld.operation.SeasonHistoryResponse.header:type_name -> insectworld.common.ResponseHeader
	7,  // 9: insectworld.operation.SeasonHistoryResponse.phases:type_name -> insectworld.operation.PhaseTimeline
	4,  // 10: insectworld.operation.SeasonHistoryResponse.final_ranking:type_name -> insectworld.operation.RankingItem
	10, // 11: insectworld.operation.TriggerEventRequest.header:type_name -> insectworld.common.RequestHeader
	11, // 12: insectworld.operation.TriggerEventResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 13: insectworld.operation.OperationService.GetCurrentSeason:input_type -> insectworld.operation.GetSeasonRequest
	2,  // 14: insectworld.operation.OperationService.GetRanking:input_type -> insectworld.operation.GetRankingRequest
	5,  // 15: insectworld.operation.OperationService.GetSeasonHistory:input_type -> insectworld.operation.SeasonHistoryRequest
	8,  // 16: insectworld.operation.OperationService.TriggerGameEvent:input_type -> insectworld.operation.TriggerEventRequest
	1,  // 17: insectworld.operation.OperationService.GetCurrentSeason:output_type -> insectworld.operation.SeasonResponse
	3,  // 18: insectworld.operation.OperationService.GetRanking:output_type -> insectworld.operation.RankingResponse
	6,  // 19: insectworld.operation.OperationService.GetSeasonHistory:output_type -> insectworld.operation.SeasonHistoryResponse
	9,  // 20: insectworld.operation.OperationService.TriggerGameEvent:output_type -> insectworld.operation.TriggerEventResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_operation_operation_proto_init() }
func file_proto_operation_operation_proto_init() {
	if File_proto_operation_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_operation_operation_proto_rawDesc), len(file_proto_operation_operation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_operation_operation_proto_goTypes,
		DependencyIndexes: file_proto_operation_operation_proto_depIdxs,
		MessageInfos:      file_proto_operation_operation_proto_msgTypes,
	}.Build()
	File_proto_operation_operation_proto = out.File
	file_proto_operation_operation_proto_goTypes = nil
	file_proto_operation_operation_proto_depIdxs = nil
}
