// Operation Service gRPC接口定义，提供赛季/排行/事件相关查询与操作。
// 对应design.md 2.2.2.5节接口清单，保留现有接口并新增历史与事件触发接口。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/operation/operation.proto

package operationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperationService_GetCurrentSeason_FullMethodName = "/insectworld.operation.OperationService/GetCurrentSeason"
	OperationService_GetRanking_FullMethodName       = "/insectworld.operation.OperationService/GetRanking"
	OperationService_GetSeasonHistory_FullMethodName = "/insectworld.operation.OperationService/GetSeasonHistory"
	OperationService_TriggerGameEvent_FullMethodName = "/insectworld.operation.OperationService/TriggerGameEvent"
)

// OperationServiceClient is the client API for OperationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OperationService Operation服务gRPC接口，提供运营相关查询。
type OperationServiceClient interface {
	// 现有接口
	GetCurrentSeason(ctx context.Context, in *GetSeasonRequest, opts ...grpc.CallOption) (*SeasonResponse, error)
	GetRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*RankingResponse, error)
	// 新增接口
	GetSeasonHistory(ctx context.Context, in *SeasonHistoryRequest, opts ...grpc.CallOption) (*SeasonHistoryResponse, error)
	TriggerGameEvent(ctx context.Context, in *TriggerEventRequest, opts ...grpc.CallOption) (*TriggerEventResponse, error)
}

type operationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationServiceClient(cc grpc.ClientConnInterface) OperationServiceClient {
	return &operationServiceClient{cc}
}

func (c *operationServiceClient) GetCurrentSeason(ctx context.Context, in *GetSeasonRequest, opts ...grpc.CallOption) (*SeasonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeasonResponse)
	err := c.cc.Invoke(ctx, OperationService_GetCurrentSeason_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) GetRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*RankingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankingResponse)
	err := c.cc.Invoke(ctx, OperationService_GetRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) GetSeasonHistory(ctx context.Context, in *SeasonHistoryRequest, opts ...grpc.CallOption) (*SeasonHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeasonHistoryResponse)
	err := c.cc.Invoke(ctx, OperationService_GetSeasonHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) TriggerGameEvent(ctx context.Context, in *TriggerEventRequest, opts ...grpc.CallOption) (*TriggerEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerEventResponse)
	err := c.cc.Invoke(ctx, OperationService_TriggerGameEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationServiceServer is the server API for OperationService service.
// All implementations must embed UnimplementedOperationServiceServer
// for forward compatibility.
//
// OperationService Operation服务gRPC接口，提供运营相关查询。
type OperationServiceServer interface {
	// 现有接口
	GetCurrentSeason(context.Context, *GetSeasonRequest) (*SeasonResponse, error)
	GetRanking(context.Context, *GetRankingRequest) (*RankingResponse, error)
	// 新增接口
	GetSeasonHistory(context.Context, *SeasonHistoryRequest) (*SeasonHistoryResponse, error)
	TriggerGameEvent(context.Context, *TriggerEventRequest) (*TriggerEventResponse, error)
	mustEmbedUnimplementedOperationServiceServer()
}

// UnimplementedOperationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationServiceServer struct{}

func (UnimplementedOperationServiceServer) GetCurrentSeason(context.Context, *GetSeasonRequest) (*SeasonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentSeason not implemented")
}
func (UnimplementedOperationServiceServer) GetRanking(context.Context, *GetRankingRequest) (*RankingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRanking not implemented")
}
func (UnimplementedOperationServiceServer) GetSeasonHistory(context.Context, *SeasonHistoryRequest) (*SeasonHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeasonHistory not implemented")
}
func (UnimplementedOperationServiceServer) TriggerGameEvent(context.Context, *TriggerEventRequest) (*TriggerEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerGameEvent not implemented")
}
func (UnimplementedOperationServiceServer) mustEmbedUnimplementedOperationServiceServer() {}
func (UnimplementedOperationServiceServer) testEmbeddedByValue()                          {}

// UnsafeOperationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationServiceServer will
// result in compilation errors.
type UnsafeOperationServiceServer interface {
	mustEmbedUnimplementedOperationServiceServer()
}

func RegisterOperationServiceServer(s grpc.ServiceRegistrar, srv OperationServiceServer) {
	// If the following call panics, it indicates UnimplementedOperationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationService_ServiceDesc, srv)
}

func _OperationService_GetCurrentSeason_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeasonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).GetCurrentSeason(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_GetCurrentSeason_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).GetCurrentSeason(ctx, req.(*GetSeasonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_GetRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).GetRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_GetRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).GetRanking(ctx, req.(*GetRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_GetSeasonHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeasonHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).GetSeasonHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_GetSeasonHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).GetSeasonHistory(ctx, req.(*SeasonHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_TriggerGameEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).TriggerGameEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationService_TriggerGameEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).TriggerGameEvent(ctx, req.(*TriggerEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperationService_ServiceDesc is the grpc.ServiceDesc for OperationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insectworld.operation.OperationService",
	HandlerType: (*OperationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentSeason",
			Handler:    _OperationService_GetCurrentSeason_Handler,
		},
		{
			MethodName: "GetRanking",
			Handler:    _OperationService_GetRanking_Handler,
		},
		{
			MethodName: "GetSeasonHistory",
			Handler:    _OperationService_GetSeasonHistory_Handler,
		},
		{
			MethodName: "TriggerGameEvent",
			Handler:    _OperationService_TriggerGameEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/operation/operation.proto",
}
