// Technology Service gRPC接口定义，提供个人科技研究/科技树/前置条件相关操作。
// 对应《通用SLG框架共性抽离方案_终版》P0-6 个人科技骨头（#18）与《契约冻结草案》4.3 清单。
// 与联盟科技互补，主城成长线；科技树/解锁条件留配置层（techs 配置）。
// 契约冻结规则：本包为P3新增包 v1 冻结，字段编号不重用、消息只增不改、服务只加不改。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: proto/technology/technology.proto

package technologypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	event "insectworld/server/shared/proto/event"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResearchTask 研究队列任务。
type ResearchTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                // 研究任务ID，全局唯一，由雪花算法生成（规范8用int64）
	TechId        int32                  `protobuf:"varint,2,opt,name=tech_id,json=techId,proto3" json:"tech_id,omitempty"`                // 科技配置ID，对应techs配置表（规范8用int32）
	TargetLevel   int32                  `protobuf:"varint,3,opt,name=target_level,json=targetLevel,proto3" json:"target_level,omitempty"` // 研究目标等级，从1级开始
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`       // 任务开始时间戳（毫秒）
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`             // 任务结束时间戳（毫秒），0表示尚未排定
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                              // 任务状态：1=等待 2=研究中 3=已完成 4=已取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResearchTask) Reset() {
	*x = ResearchTask{}
	mi := &file_proto_technology_technology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchTask) ProtoMessage() {}

func (x *ResearchTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchTask.ProtoReflect.Descriptor instead.
func (*ResearchTask) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{0}
}

func (x *ResearchTask) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ResearchTask) GetTechId() int32 {
	if x != nil {
		return x.TechId
	}
	return 0
}

func (x *ResearchTask) GetTargetLevel() int32 {
	if x != nil {
		return x.TargetLevel
	}
	return 0
}

func (x *ResearchTask) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ResearchTask) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ResearchTask) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// TechNode 科技树节点，科技与其等级状态的组合视图。
type TechNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TechId        int32                  `protobuf:"varint,1,opt,name=tech_id,json=techId,proto3" json:"tech_id,omitempty"`                   // 科技配置ID
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`                                   // 当前研究等级，0表示未研究
	Prerequisites []int32                `protobuf:"varint,3,rep,packed,name=prerequisites,proto3" json:"prerequisites,omitempty"`            // 前置科技配置ID列表，全部满足才可研究
	ResearchTime  int64                  `protobuf:"varint,4,opt,name=research_time,json=researchTime,proto3" json:"research_time,omitempty"` // 单级研究时长（毫秒），数值来自techs配置
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                                 // 科技状态：1=未解锁 2=可研究 3=研究中 4=已研究
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TechNode) Reset() {
	*x = TechNode{}
	mi := &file_proto_technology_technology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TechNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechNode) ProtoMessage() {}

func (x *TechNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechNode.ProtoReflect.Descriptor instead.
func (*TechNode) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{1}
}

func (x *TechNode) GetTechId() int32 {
	if x != nil {
		return x.TechId
	}
	return 0
}

func (x *TechNode) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *TechNode) GetPrerequisites() []int32 {
	if x != nil {
		return x.Prerequisites
	}
	return nil
}

func (x *TechNode) GetResearchTime() int64 {
	if x != nil {
		return x.ResearchTime
	}
	return 0
}

func (x *TechNode) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// StartResearchRequest 发起研究请求
type StartResearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                // 请求头
	TechId        int32                  `protobuf:"varint,2,opt,name=tech_id,json=techId,proto3" json:"tech_id,omitempty"` // 科技配置ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResearchRequest) Reset() {
	*x = StartResearchRequest{}
	mi := &file_proto_technology_technology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResearchRequest) ProtoMessage() {}

func (x *StartResearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResearchRequest.ProtoReflect.Descriptor instead.
func (*StartResearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{2}
}

func (x *StartResearchRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StartResearchRequest) GetTechId() int32 {
	if x != nil {
		return x.TechId
	}
	return 0
}

// StartResearchResponse 发起研究响应
type StartResearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	Task          *ResearchTask          `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`     // 已入队的研究任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResearchResponse) Reset() {
	*x = StartResearchResponse{}
	mi := &file_proto_technology_technology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResearchResponse) ProtoMessage() {}

func (x *StartResearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResearchResponse.ProtoReflect.Descriptor instead.
func (*StartResearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{3}
}

func (x *StartResearchResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StartResearchResponse) GetTask() *ResearchTask {
	if x != nil {
		return x.Task
	}
	return nil
}

// GetTechTreeRequest 查询科技树请求
type GetTechTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 请求头
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTechTreeRequest) Reset() {
	*x = GetTechTreeRequest{}
	mi := &file_proto_technology_technology_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTechTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechTreeRequest) ProtoMessage() {}

func (x *GetTechTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechTreeRequest.ProtoReflect.Descriptor instead.
func (*GetTechTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{4}
}

func (x *GetTechTreeRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

// GetTechTreeResponse 查询科技树响应
type GetTechTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	Nodes         []*TechNode            `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`   // 全部科技节点列表
	Tasks         []*ResearchTask        `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`   // 当前研究队列任务列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTechTreeResponse) Reset() {
	*x = GetTechTreeResponse{}
	mi := &file_proto_technology_technology_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTechTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechTreeResponse) ProtoMessage() {}

func (x *GetTechTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechTreeResponse.ProtoReflect.Descriptor instead.
func (*GetTechTreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{5}
}

func (x *GetTechTreeResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetTechTreeResponse) GetNodes() []*TechNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetTechTreeResponse) GetTasks() []*ResearchTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// CheckPrerequisitesRequest 校验前置条件请求
type CheckPrerequisitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                // 请求头
	TechId        int32                  `protobuf:"varint,2,opt,name=tech_id,json=techId,proto3" json:"tech_id,omitempty"` // 科技配置ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPrerequisitesRequest) Reset() {
	*x = CheckPrerequisitesRequest{}
	mi := &file_proto_technology_technology_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPrerequisitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPrerequisitesRequest) ProtoMessage() {}

func (x *CheckPrerequisitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPrerequisitesRequest.ProtoReflect.Descriptor instead.
func (*CheckPrerequisitesRequest) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPrerequisitesRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CheckPrerequisitesRequest) GetTechId() int32 {
	if x != nil {
		return x.TechId
	}
	return 0
}

// CheckPrerequisitesResponse 校验前置条件响应
type CheckPrerequisitesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Header         *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                                 // 响应头
	Satisfied      bool                   `protobuf:"varint,2,opt,name=satisfied,proto3" json:"satisfied,omitempty"`                                          // 是否满足全部前置条件
	MissingTechIds []int32                `protobuf:"varint,3,rep,packed,name=missing_tech_ids,json=missingTechIds,proto3" json:"missing_tech_ids,omitempty"` // 未满足的前置科技配置ID列表，satisfied为true时为空
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckPrerequisitesResponse) Reset() {
	*x = CheckPrerequisitesResponse{}
	mi := &file_proto_technology_technology_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPrerequisitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPrerequisitesResponse) ProtoMessage() {}

func (x *CheckPrerequisitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPrerequisitesResponse.ProtoReflect.Descriptor instead.
func (*CheckPrerequisitesResponse) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{7}
}

func (x *CheckPrerequisitesResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CheckPrerequisitesResponse) GetSatisfied() bool {
	if x != nil {
		return x.Satisfied
	}
	return false
}

func (x *CheckPrerequisitesResponse) GetMissingTechIds() []int32 {
	if x != nil {
		return x.MissingTechIds
	}
	return nil
}

// ResearchStartedEvent 研究开始事件，研究任务入队开始后发布。
// 主题命名 event.technology.research_started，订阅方用于记录研究行为与队列占用。
type ResearchStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                   // 基础事件信息
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`          // 发起研究的玩家ID
	TaskId        int64                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                // 研究任务ID
	TechId        int32                  `protobuf:"varint,4,opt,name=tech_id,json=techId,proto3" json:"tech_id,omitempty"`                // 科技配置ID
	TargetLevel   int32                  `protobuf:"varint,5,opt,name=target_level,json=targetLevel,proto3" json:"target_level,omitempty"` // 研究目标等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResearchStartedEvent) Reset() {
	*x = ResearchStartedEvent{}
	mi := &file_proto_technology_technology_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchStartedEvent) ProtoMessage() {}

func (x *ResearchStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchStartedEvent.ProtoReflect.Descriptor instead.
func (*ResearchStartedEvent) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{8}
}

func (x *ResearchStartedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ResearchStartedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ResearchStartedEvent) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ResearchStartedEvent) GetTechId() int32 {
	if x != nil {
		return x.TechId
	}
	return 0
}

func (x *ResearchStartedEvent) GetTargetLevel() int32 {
	if x != nil {
		return x.TargetLevel
	}
	return 0
}

// ResearchCompletedEvent 研究完成事件，研究任务完成后发布。
// 主题命名 event.technology.research_completed，订阅方用于解锁科技效果与刷新科技树。
type ResearchCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                          // 基础事件信息
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 研究完成的玩家ID
	TaskId        int64                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`       // 研究任务ID
	TechId        int32                  `protobuf:"varint,4,opt,name=tech_id,json=techId,proto3" json:"tech_id,omitempty"`       // 科技配置ID
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`                       // 完成后的科技等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResearchCompletedEvent) Reset() {
	*x = ResearchCompletedEvent{}
	mi := &file_proto_technology_technology_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchCompletedEvent) ProtoMessage() {}

func (x *ResearchCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchCompletedEvent.ProtoReflect.Descriptor instead.
func (*ResearchCompletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{9}
}

func (x *ResearchCompletedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ResearchCompletedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ResearchCompletedEvent) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ResearchCompletedEvent) GetTechId() int32 {
	if x != nil {
		return x.TechId
	}
	return 0
}

func (x *ResearchCompletedEvent) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// ResearchCancelledEvent 研究取消事件，取消研究任务后发布。
// 主题命名 event.technology.research_cancelled，订阅方用于退还占用的队列与部分资源。
type ResearchCancelledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                          // 基础事件信息
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 取消研究的玩家ID
	TaskId        int64                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`       // 研究任务ID
	TechId        int32                  `protobuf:"varint,4,opt,name=tech_id,json=techId,proto3" json:"tech_id,omitempty"`       // 科技配置ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResearchCancelledEvent) Reset() {
	*x = ResearchCancelledEvent{}
	mi := &file_proto_technology_technology_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchCancelledEvent) ProtoMessage() {}

func (x *ResearchCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_technology_technology_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchCancelledEvent.ProtoReflect.Descriptor instead.
func (*ResearchCancelledEvent) Descriptor() ([]byte, []int) {
	return file_proto_technology_technology_proto_rawDescGZIP(), []int{10}
}

func (x *ResearchCancelledEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ResearchCancelledEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ResearchCancelledEvent) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ResearchCancelledEvent) GetTechId() int32 {
	if x != nil {
		return x.TechId
	}
	return 0
}

var File_proto_technology_technology_proto protoreflect.FileDescriptor

const file_proto_technology_technology_proto_rawDesc = "" +
	"\n" +
	"!proto/technology/technology.proto\x12\x16insectworld.technology\x1a\x19proto/common/common.proto\x1a\x1eproto/event/domain_event.proto\"\xb5\x01\n" +
	"\fResearchTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x17\n" +
	"\atech_id\x18\x02 \x01(\x05R\x06techId\x12!\n" +
	"\ftarget_level\x18\x03 \x01(\x05R\vtargetLevel\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"\x9c\x01\n" +
	"\bTechNode\x12\x17\n" +
	"\atech_id\x18\x01 \x01(\x05R\x06techId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12$\n" +
	"\rprerequisites\x18\x03 \x03(\x05R\rprerequisites\x12#\n" +
	"\rresearch_time\x18\x04 \x01(\x03R\fresearchTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"j\n" +
	"\x14StartResearchRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x17\n" +
	"\atech_id\x18\x02 \x01(\x05R\x06techId\"\x8d\x01\n" +
	"\x15StartResearchResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x128\n" +
	"\x04task\x18\x02 \x01(\v2$.insectworld.technology.ResearchTaskR\x04task\"O\n" +
	"\x12GetTechTreeRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\"\xc5\x01\n" +
	"\x13GetTechTreeResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x126\n" +
	"\x05nodes\x18\x02 \x03(\v2 .insectworld.technology.TechNodeR\x05nodes\x12:\n" +
	"\x05tasks\x18\x03 \x03(\v2$.insectworld.technology.ResearchTaskR\x05tasks\"o\n" +
	"\x19CheckPrerequisitesRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x17\n" +
	"\atech_id\x18\x02 \x01(\x05R\x06techId\"\xa0\x01\n" +
	"\x1aCheckPrerequisitesResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1c\n" +
	"\tsatisfied\x18\x02 \x01(\bR\tsatisfied\x12(\n" +
	"\x10missing_tech_ids\x18\x03 \x03(\x05R\x0emissingTechIds\"\xbc\x01\n" +
	"\x14ResearchStartedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x03R\x06taskId\x12\x17\n" +
	"\atech_id\x18\x04 \x01(\x05R\x06techId\x12!\n" +
	"\ftarget_level\x18\x05 \x01(\x05R\vtargetLevel\"\xb1\x01\n" +
	"\x16ResearchCompletedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x03R\x06taskId\x12\x17\n" +
	"\atech_id\x18\x04 \x01(\x05R\x06techId\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\"\x9b\x01\n" +
	"\x16ResearchCancelledEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x03R\x06taskId\x12\x17\n" +
	"\atech_id\x18\x04 \x01(\x05R\x06techId2\xe6\x02\n" +
	"\x11TechnologyService\x12l\n" +
	"\rStartResearch\x12,.insectworld.technology.StartResearchRequest\x1a-.insectworld.technology.StartResearchResponse\x12f\n" +
	"\vGetTechTree\x12*.insectworld.technology.GetTechTreeRequest\x1a+.insectworld.technology.GetTechTreeResponse\x12{\n" +
	"\x12CheckPrerequisites\x121.insectworld.technology.CheckPrerequisitesRequest\x1a2.insectworld.technology.CheckPrerequisitesResponseB+Z)insectworld/proto/technology;technologypbb\x06proto3"

var (
	file_proto_technology_technology_proto_rawDescOnce sync.Once
	file_proto_technology_technology_proto_rawDescData []byte
)

func file_proto_technology_technology_proto_rawDescGZIP() []byte {
	file_proto_technology_technology_proto_rawDescOnce.Do(func() {
		file_proto_technology_technology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_technology_technology_proto_rawDesc), len(file_proto_technology_technology_proto_rawDesc)))
	})
	return file_proto_technology_technology_proto_rawDescData
}

var file_proto_technology_technology_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_technology_technology_proto_goTypes = []any{
	(*ResearchTask)(nil),               // 0: insectworld.technology.ResearchTask
	(*TechNode)(nil),                   // 1: insectworld.technology.TechNode
	(*StartResearchRequest)(nil),       // 2: insectworld.technology.StartResearchRequest
	(*StartResearchResponse)(nil),      // 3: insectworld.technology.StartResearchResponse
	(*GetTechTreeRequest)(nil),         // 4: insectworld.technology.GetTechTreeRequest
	(*GetTechTreeResponse)(nil),        // 5: insectworld.technology.GetTechTreeResponse
	(*CheckPrerequisitesRequest)(nil),  // 6: insectworld.technology.CheckPrerequisitesRequest
	(*CheckPrerequisitesResponse)(nil), // 7: insectworld.technology.CheckPrerequisitesResponse
	(*ResearchStartedEvent)(nil),       // 8: insectworld.technology.ResearchStartedEvent
	(*ResearchCompletedEvent)(nil),     // 9: insectworld.technology.ResearchCompletedEvent
	(*ResearchCancelledEvent)(nil),     // 10: insectworld.technology.ResearchCancelledEvent
	(*common.RequestHeader)(nil),       // 11: insectworld.common.RequestHeader
	(*common.ResponseHeader)(nil),      // 12: insectworld.common.ResponseHeader
	(*event.DomainEvent)(nil),          // 13: insectworld.event.DomainEvent
}
var file_proto_technology_technology_proto_depIdxs = []int32{
	11, // 0: insectworld.technology.StartResearchRequest.header:type_name -> insectworld.common.RequestHeader
	12, // 1: insectworld.technology.StartResearchResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 2: insectworld.technology.StartResearchResponse.task:type_name -> insectworld.technology.ResearchTask
	11, // 3: insectworld.technology.GetTechTreeRequest.header:type_name -> insectworld.common.RequestHeader
	12, // 4: insectworld.technology.GetTechTreeResponse.header:type_name -> insectworld.common.ResponseHeader
	1,  // 5: insectworld.technology.GetTechTreeResponse.nodes:type_name -> insectworld.technology.TechNode
	0,  // 6: insectworld.technology.GetTechTreeResponse.tasks:type_name -> insectworld.technology.ResearchTask
	11, // 7: insectworld.technology.CheckPrerequisitesRequest.header:type_name -> insectworld.common.RequestHeader
	12, // 8: insectworld.technology.CheckPrerequisitesResponse.header:type_name -> insectworld.common.ResponseHeader
	13, // 9: insectworld.technology.ResearchStartedEvent.base:type_name -> insectworld.event.DomainEvent
	13, // 10: insectworld.technology.ResearchCompletedEvent.base:type_name -> insectworld.event.DomainEvent
	13, // 11: insectworld.technology.ResearchCancelledEvent.base:type_name -> insectworld.event.DomainEvent
	2,  // 12: insectworld.technology.TechnologyService.StartResearch:input_type -> insectworld.technology.StartResearchRequest
	4,  // 13: insectworld.technology.TechnologyService.GetTechTree:input_type -> insectworld.technology.GetTechTreeRequest
	6,  // 14: insectworld.technology.TechnologyService.CheckPrerequisites:input_type -> insectworld.technology.CheckPrerequisitesRequest
	3,  // 15: insectworld.technology.TechnologyService.StartResearch:output_type -> insectworld.technology.StartResearchResponse
	5,  // 16: insectworld.technology.TechnologyService.GetTechTree:output_type -> insectworld.technology.GetTechTreeResponse
	7,  // 17: insectworld.technology.TechnologyService.CheckPrerequisites:output_type -> insectworld.technology.CheckPrerequisitesResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_technology_technology_proto_init() }
func file_proto_technology_technology_proto_init() {
	if File_proto_technology_technology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_technology_technology_proto_rawDesc), len(file_proto_technology_technology_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_technology_technology_proto_goTypes,
		DependencyIndexes: file_proto_technology_technology_proto_depIdxs,
		MessageInfos:      file_proto_technology_technology_proto_msgTypes,
	}.Build()
	File_proto_technology_technology_proto = out.File
	file_proto_technology_technology_proto_goTypes = nil
	file_proto_technology_technology_proto_depIdxs = nil
}
