// Technology Service gRPC接口定义，提供个人科技研究/科技树/前置条件相关操作。
// 对应《通用SLG框架共性抽离方案_终版》P0-6 个人科技骨头（#18）与《契约冻结草案》4.3 清单。
// 与联盟科技互补，主城成长线；科技树/解锁条件留配置层（techs 配置）。
// 契约冻结规则：本包为P3新增包 v1 冻结，字段编号不重用、消息只增不改、服务只加不改。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/technology/technology.proto

package technologypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TechnologyService_StartResearch_FullMethodName      = "/insectworld.technology.TechnologyService/StartResearch"
	TechnologyService_GetTechTree_FullMethodName        = "/insectworld.technology.TechnologyService/GetTechTree"
	TechnologyService_CheckPrerequisites_FullMethodName = "/insectworld.technology.TechnologyService/CheckPrerequisites"
)

// TechnologyServiceClient is the client API for TechnologyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TechnologyService 个人科技服务gRPC接口，提供研究队列、科技树与前置条件校验。
type TechnologyServiceClient interface {
	// 发起研究，校验前置条件与资源消耗后进入研究队列
	StartResearch(ctx context.Context, in *StartResearchRequest, opts ...grpc.CallOption) (*StartResearchResponse, error)
	// 查询科技树，返回全部科技节点与当前研究任务
	GetTechTree(ctx context.Context, in *GetTechTreeRequest, opts ...grpc.CallOption) (*GetTechTreeResponse, error)
	// 校验科技前置条件是否满足
	CheckPrerequisites(ctx context.Context, in *CheckPrerequisitesRequest, opts ...grpc.CallOption) (*CheckPrerequisitesResponse, error)
}

type technologyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTechnologyServiceClient(cc grpc.ClientConnInterface) TechnologyServiceClient {
	return &technologyServiceClient{cc}
}

func (c *technologyServiceClient) StartResearch(ctx context.Context, in *StartResearchRequest, opts ...grpc.CallOption) (*StartResearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResearchResponse)
	err := c.cc.Invoke(ctx, TechnologyService_StartResearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technologyServiceClient) GetTechTree(ctx context.Context, in *GetTechTreeRequest, opts ...grpc.CallOption) (*GetTechTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTechTreeResponse)
	err := c.cc.Invoke(ctx, TechnologyService_GetTechTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technologyServiceClient) CheckPrerequisites(ctx context.Context, in *CheckPrerequisitesRequest, opts ...grpc.CallOption) (*CheckPrerequisitesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPrerequisitesResponse)
	err := c.cc.Invoke(ctx, TechnologyService_CheckPrerequisites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TechnologyServiceServer is the server API for TechnologyService service.
// All implementations must embed UnimplementedTechnologyServiceServer
// for forward compatibility.
//
// TechnologyService 个人科技服务gRPC接口，提供研究队列、科技树与前置条件校验。
type TechnologyServiceServer interface {
	// 发起研究，校验前置条件与资源消耗后进入研究队列
	StartResearch(context.Context, *StartResearchRequest) (*StartResearchResponse, error)
	// 查询科技树，返回全部科技节点与当前研究任务
	GetTechTree(context.Context, *GetTechTreeRequest) (*GetTechTreeResponse, error)
	// 校验科技前置条件是否满足
	CheckPrerequisites(context.Context, *CheckPrerequisitesRequest) (*CheckPrerequisitesResponse, error)
	mustEmbedUnimplementedTechnologyServiceServer()
}

// UnimplementedTechnologyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTechnologyServiceServer struct{}

func (UnimplementedTechnologyServiceServer) StartResearch(context.Context, *StartResearchRequest) (*StartResearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartResearch not implemented")
}
func (UnimplementedTechnologyServiceServer) GetTechTree(context.Context, *GetTechTreeRequest) (*GetTechTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTechTree not implemented")
}
func (UnimplementedTechnologyServiceServer) CheckPrerequisites(context.Context, *CheckPrerequisitesRequest) (*CheckPrerequisitesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPrerequisites not implemented")
}
func (UnimplementedTechnologyServiceServer) mustEmbedUnimplementedTechnologyServiceServer() {}
func (UnimplementedTechnologyServiceServer) testEmbeddedByValue()                           {}

// UnsafeTechnologyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TechnologyServiceServer will
// result in compilation errors.
type UnsafeTechnologyServiceServer interface {
	mustEmbedUnimplementedTechnologyServiceServer()
}

func RegisterTechnologyServiceServer(s grpc.ServiceRegistrar, srv TechnologyServiceServer) {
	// If the following call panics, it indicates UnimplementedTechnologyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TechnologyService_ServiceDesc, srv)
}

func _TechnologyService_StartResearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartResearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnologyServiceServer).StartResearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnologyService_StartResearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnologyServiceServer).StartResearch(ctx, req.(*StartResearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnologyService_GetTechTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTechTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnologyServiceServer).GetTechTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnologyService_GetTechTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnologyServiceServer).GetTechTree(ctx, req.(*GetTechTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnologyService_CheckPrerequisites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPrerequisitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnologyServiceServer).CheckPrerequisites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnologyService_CheckPrerequisites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnologyServiceServer).CheckPrerequisites(ctx, req.(*CheckPrerequisitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TechnologyService_ServiceDesc is the grpc.ServiceDesc for TechnologyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TechnologyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insectworld.technology.TechnologyService",
	HandlerType: (*TechnologyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartResearch",
			Handler:    _TechnologyService_StartResearch_Handler,
		},
		{
			MethodName: "GetTechTree",
			Handler:    _TechnologyService_GetTechTree_Handler,
		},
		{
			MethodName: "CheckPrerequisites",
			Handler:    _TechnologyService_CheckPrerequisites_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/technology/technology.proto",
}
