// AdminService gRPC接口定义，运营管理操作协议。
// 对应design.md 2.2.2.7节，提供配置热更/赛季管理/事件触发/玩家管理/公告发布能力。
// 所有管理操作必须经过运营管理员鉴权+审计日志记录（安全设计.md）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/admin/admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReloadConfigRequest 触发配置热更请求
type ReloadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                     // 请求头
	AdminToken    string                 `protobuf:"bytes,2,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`           // 运营管理员Token，鉴权用
	ConfigVersion int64                  `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // 目标配置版本号，0表示最新版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() {
	*x = ReloadConfigRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigRequest) ProtoMessage() {}

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ReloadConfigRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReloadConfigRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *ReloadConfigRequest) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// ReloadConfigResponse 配置热更响应
type ReloadConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Header         *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                        // 响应头
	AppliedVersion int64                  `protobuf:"varint,2,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"` // 已生效的配置版本号
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReloadConfigResponse) Reset() {
	*x = ReloadConfigResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigResponse) ProtoMessage() {}

func (x *ReloadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ReloadConfigResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReloadConfigResponse) GetAppliedVersion() int64 {
	if x != nil {
		return x.AppliedVersion
	}
	return 0
}

// RollbackConfigRequest 回滚配置请求
type RollbackConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                     // 请求头
	AdminToken    string                 `protobuf:"bytes,2,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`           // 运营管理员Token，鉴权用
	TargetVersion int64                  `protobuf:"varint,3,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"` // 目标回滚版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackConfigRequest) Reset() {
	*x = RollbackConfigRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackConfigRequest) ProtoMessage() {}

func (x *RollbackConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackConfigRequest.ProtoReflect.Descriptor instead.
func (*RollbackConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackConfigRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RollbackConfigRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *RollbackConfigRequest) GetTargetVersion() int64 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

// RollbackConfigResponse 回滚配置响应
type RollbackConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Header         *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                        // 响应头
	CurrentVersion int64                  `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // 回滚后的当前版本号
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackConfigResponse) Reset() {
	*x = RollbackConfigResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackConfigResponse) ProtoMessage() {}

func (x *RollbackConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackConfigResponse.ProtoReflect.Descriptor instead.
func (*RollbackConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackConfigResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RollbackConfigResponse) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

// ForceTransitionRequest 强制切换赛季阶段请求
type ForceTransitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                               // 请求头
	AdminToken    string                 `protobuf:"bytes,2,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`     // 运营管理员Token，鉴权用
	SeasonId      int64                  `protobuf:"varint,3,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`          // 赛季ID（规范8用int64）
	TargetPhase   int32                  `protobuf:"varint,4,opt,name=target_phase,json=targetPhase,proto3" json:"target_phase,omitempty"` // 目标阶段：1=准备 2=战争 3=结算（规范8用int32）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceTransitionRequest) Reset() {
	*x = ForceTransitionRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceTransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceTransitionRequest) ProtoMessage() {}

func (x *ForceTransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceTransitionRequest.ProtoReflect.Descriptor instead.
func (*ForceTransitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ForceTransitionRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ForceTransitionRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *ForceTransitionRequest) GetSeasonId() int64 {
	if x != nil {
		return x.SeasonId
	}
	return 0
}

func (x *ForceTransitionRequest) GetTargetPhase() int32 {
	if x != nil {
		return x.TargetPhase
	}
	return 0
}

// ForceTransitionResponse 强制切换阶段响应
type ForceTransitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                     // 响应头
	PreviousPhase int32                  `protobuf:"varint,2,opt,name=previous_phase,json=previousPhase,proto3" json:"previous_phase,omitempty"` // 切换前的阶段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceTransitionResponse) Reset() {
	*x = ForceTransitionResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceTransitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceTransitionResponse) ProtoMessage() {}

func (x *ForceTransitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceTransitionResponse.ProtoReflect.Descriptor instead.
func (*ForceTransitionResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ForceTransitionResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ForceTransitionResponse) GetPreviousPhase() int32 {
	if x != nil {
		return x.PreviousPhase
	}
	return 0
}

// ForceResetRequest 强制重置赛季请求
type ForceResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                           // 请求头
	AdminToken    string                 `protobuf:"bytes,2,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"` // 运营管理员Token，鉴权用
	SeasonId      int64                  `protobuf:"varint,3,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`      // 赛季ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceResetRequest) Reset() {
	*x = ForceResetRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceResetRequest) ProtoMessage() {}

func (x *ForceResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceResetRequest.ProtoReflect.Descriptor instead.
func (*ForceResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ForceResetRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ForceResetRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *ForceResetRequest) GetSeasonId() int64 {
	if x != nil {
		return x.SeasonId
	}
	return 0
}

// ForceResetResponse 强制重置赛季响应
type ForceResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	Reset_        bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`  // 是否重置成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceResetResponse) Reset() {
	*x = ForceResetResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceResetResponse) ProtoMessage() {}

func (x *ForceResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceResetResponse.ProtoReflect.Descriptor instead.
func (*ForceResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ForceResetResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ForceResetResponse) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

// ManualTriggerRequest 手动触发游戏事件请求
type ManualTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                           // 请求头
	AdminToken    string                 `protobuf:"bytes,2,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"` // 运营管理员Token，鉴权用
	EventId       int64                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`         // 事件ID（规范8用int64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualTriggerRequest) Reset() {
	*x = ManualTriggerRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualTriggerRequest) ProtoMessage() {}

func (x *ManualTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualTriggerRequest.ProtoReflect.Descriptor instead.
func (*ManualTriggerRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ManualTriggerRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ManualTriggerRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *ManualTriggerRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

// ManualTriggerResponse 手动触发事件响应
type ManualTriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`        // 响应头
	Triggered     bool                   `protobuf:"varint,2,opt,name=triggered,proto3" json:"triggered,omitempty"` // 是否触发成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualTriggerResponse) Reset() {
	*x = ManualTriggerResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualTriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualTriggerResponse) ProtoMessage() {}

func (x *ManualTriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualTriggerResponse.ProtoReflect.Descriptor instead.
func (*ManualTriggerResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ManualTriggerResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ManualTriggerResponse) GetTriggered() bool {
	if x != nil {
		return x.Triggered
	}
	return false
}

// BanPlayerRequest 封禁玩家请求
type BanPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                            // 请求头
	AdminToken    string                 `protobuf:"bytes,2,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`  // 运营管理员Token，鉴权用
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`       // 玩家ID（规范8用int64）
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // 封禁时长（毫秒），0表示永久封禁
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                            // 封禁原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPlayerRequest) Reset() {
	*x = BanPlayerRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPlayerRequest) ProtoMessage() {}

func (x *BanPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPlayerRequest.ProtoReflect.Descriptor instead.
func (*BanPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{10}
}

func (x *BanPlayerRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BanPlayerRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *BanPlayerRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *BanPlayerRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *BanPlayerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// BanPlayerResponse 封禁玩家响应
type BanPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`  // 响应头
	Banned        bool                   `protobuf:"varint,2,opt,name=banned,proto3" json:"banned,omitempty"` // 是否封禁成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPlayerResponse) Reset() {
	*x = BanPlayerResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPlayerResponse) ProtoMessage() {}

func (x *BanPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPlayerResponse.ProtoReflect.Descriptor instead.
func (*BanPlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{11}
}

func (x *BanPlayerResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BanPlayerResponse) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

// UnbanPlayerRequest 解封玩家请求
type UnbanPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                           // 请求头
	AdminToken    string                 `protobuf:"bytes,2,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"` // 运营管理员Token，鉴权用
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`      // 玩家ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanPlayerRequest) Reset() {
	*x = UnbanPlayerRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPlayerRequest) ProtoMessage() {}

func (x *UnbanPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPlayerRequest.ProtoReflect.Descriptor instead.
func (*UnbanPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{12}
}

func (x *UnbanPlayerRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UnbanPlayerRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *UnbanPlayerRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// UnbanPlayerResponse 解封玩家响应
type UnbanPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`      // 响应头
	Unbanned      bool                   `protobuf:"varint,2,opt,name=unbanned,proto3" json:"unbanned,omitempty"` // 是否解封成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanPlayerResponse) Reset() {
	*x = UnbanPlayerResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPlayerResponse) ProtoMessage() {}

func (x *UnbanPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPlayerResponse.ProtoReflect.Descriptor instead.
func (*UnbanPlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{13}
}

func (x *UnbanPlayerResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UnbanPlayerResponse) GetUnbanned() bool {
	if x != nil {
		return x.Unbanned
	}
	return false
}

// PublishNoticeRequest 发布公告请求
type PublishNoticeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                // 请求头
	AdminToken    string                 `protobuf:"bytes,2,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`      // 运营管理员Token，鉴权用
	NoticeType    int32                  `protobuf:"varint,3,opt,name=notice_type,json=noticeType,proto3" json:"notice_type,omitempty"`     // 公告类型：1=全服 2=指定玩家 3=指定联盟（规范8用int32）
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                              // 公告内容
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`     // 公告展示时长（毫秒）
	TargetIds     []int64                `protobuf:"varint,6,rep,packed,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"` // 目标ID列表，notice_type=2时为玩家ID，=3时为联盟ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishNoticeRequest) Reset() {
	*x = PublishNoticeRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishNoticeRequest) ProtoMessage() {}

func (x *PublishNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishNoticeRequest.ProtoReflect.Descriptor instead.
func (*PublishNoticeRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{14}
}

func (x *PublishNoticeRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PublishNoticeRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *PublishNoticeRequest) GetNoticeType() int32 {
	if x != nil {
		return x.NoticeType
	}
	return 0
}

func (x *PublishNoticeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PublishNoticeRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *PublishNoticeRequest) GetTargetIds() []int64 {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

// PublishNoticeResponse 发布公告响应
type PublishNoticeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 响应头
	NoticeId      int64                  `protobuf:"varint,2,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"` // 公告ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishNoticeResponse) Reset() {
	*x = PublishNoticeResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishNoticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishNoticeResponse) ProtoMessage() {}

func (x *PublishNoticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishNoticeResponse.ProtoReflect.Descriptor instead.
func (*PublishNoticeResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{15}
}

func (x *PublishNoticeResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PublishNoticeResponse) GetNoticeId() int64 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

var File_proto_admin_admin_proto protoreflect.FileDescriptor

const file_proto_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x17proto/admin/admin.proto\x12\x11insectworld.admin\x1a\x19proto/common/common.proto\"\x98\x01\n" +
	"\x13ReloadConfigRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vadmin_token\x18\x02 \x01(\tR\n" +
	"adminToken\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x03R\rconfigVersion\"{\n" +
	"\x14ReloadConfigResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12'\n" +
	"\x0fapplied_version\x18\x02 \x01(\x03R\x0eappliedVersion\"\x9a\x01\n" +
	"\x15RollbackConfigRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vadmin_token\x18\x02 \x01(\tR\n" +
	"adminToken\x12%\n" +
	"\x0etarget_version\x18\x03 \x01(\x03R\rtargetVersion\"}\n" +
	"\x16RollbackConfigResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x03R\x0ecurrentVersion\"\xb4\x01\n" +
	"\x16ForceTransitionRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vadmin_token\x18\x02 \x01(\tR\n" +
	"adminToken\x12\x1b\n" +
	"\tseason_id\x18\x03 \x01(\x03R\bseasonId\x12!\n" +
	"\ftarget_phase\x18\x04 \x01(\x05R\vtargetPhase\"|\n" +
	"\x17ForceTransitionResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12%\n" +
	"\x0eprevious_phase\x18\x02 \x01(\x05R\rpreviousPhase\"\x8c\x01\n" +
	"\x11ForceResetRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vadmin_token\x18\x02 \x01(\tR\n" +
	"adminToken\x12\x1b\n" +
	"\tseason_id\x18\x03 \x01(\x03R\bseasonId\"f\n" +
	"\x12ForceResetResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\"\x8d\x01\n" +
	"\x14ManualTriggerRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vadmin_token\x18\x02 \x01(\tR\n" +
	"adminToken\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\"q\n" +
	"\x15ManualTriggerResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1c\n" +
	"\ttriggered\x18\x02 \x01(\bR\ttriggered\"\xc4\x01\n" +
	"\x10BanPlayerRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vadmin_token\x18\x02 \x01(\tR\n" +
	"adminToken\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"g\n" +
	"\x11BanPlayerResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x16\n" +
	"\x06banned\x18\x02 \x01(\bR\x06banned\"\x8d\x01\n" +
	"\x12UnbanPlayerRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vadmin_token\x18\x02 \x01(\tR\n" +
	"adminToken\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\"m\n" +
	"\x13UnbanPlayerResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1a\n" +
	"\bunbanned\x18\x02 \x01(\bR\bunbanned\"\xed\x01\n" +
	"\x14PublishNoticeRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vadmin_token\x18\x02 \x01(\tR\n" +
	"adminToken\x12\x1f\n" +
	"\vnotice_type\x18\x03 \x01(\x05R\n" +
	"noticeType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x06 \x03(\x03R\ttargetIds\"p\n" +
	"\x15PublishNoticeResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1b\n" +
	"\tnotice_id\x18\x02 \x01(\x03R\bnoticeId2\xa9\x06\n" +
	"\fAdminService\x12_\n" +
	"\fReloadConfig\x12&.insectworld.admin.ReloadConfigRequest\x1a'.insectworld.admin.ReloadConfigResponse\x12e\n" +
	"\x0eRollbackConfig\x12(.insectworld.admin.RollbackConfigRequest\x1a).insectworld.admin.RollbackConfigResponse\x12m\n" +
	"\x14ForceTransitionPhase\x12).insectworld.admin.ForceTransitionRequest\x1a*.insectworld.admin.ForceTransitionResponse\x12_\n" +
	"\x10ForceResetSeason\x12$.insectworld.admin.ForceResetRequest\x1a%.insectworld.admin.ForceResetResponse\x12g\n" +
	"\x12ManualTriggerEvent\x12'.insectworld.admin.ManualTriggerRequest\x1a(.insectworld.admin.ManualTriggerResponse\x12V\n" +
	"\tBanPlayer\x12#.insectworld.admin.BanPlayerRequest\x1a$.insectworld.admin.BanPlayerResponse\x12\\\n" +
	"\vUnbanPlayer\x12%.insectworld.admin.UnbanPlayerRequest\x1a&.insectworld.admin.UnbanPlayerResponse\x12b\n" +
	"\rPublishNotice\x12'.insectworld.admin.PublishNoticeRequest\x1a(.insectworld.admin.PublishNoticeResponseB!Z\x1finsectworld/proto/admin;adminpbb\x06proto3"

var (
	file_proto_admin_admin_proto_rawDescOnce sync.Once
	file_proto_admin_admin_proto_rawDescData []byte
)

func file_proto_admin_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_admin_proto_rawDesc), len(file_proto_admin_admin_proto_rawDesc)))
	})
	return file_proto_admin_admin_proto_rawDescData
}

var file_proto_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_admin_admin_proto_goTypes = []any{
	(*ReloadConfigRequest)(nil),     // 0: insectworld.admin.ReloadConfigRequest
	(*ReloadConfigResponse)(nil),    // 1: insectworld.admin.ReloadConfigResponse
	(*RollbackConfigRequest)(nil),   // 2: insectworld.admin.RollbackConfigRequest
	(*RollbackConfigResponse)(nil),  // 3: insectworld.admin.RollbackConfigResponse
	(*ForceTransitionRequest)(nil),  // 4: insectworld.admin.ForceTransitionRequest
	(*ForceTransitionResponse)(nil), // 5: insectworld.admin.ForceTransitionResponse
	(*ForceResetRequest)(nil),       // 6: insectworld.admin.ForceResetRequest
	(*ForceResetResponse)(nil),      // 7: insectworld.admin.ForceResetResponse
	(*ManualTriggerRequest)(nil),    // 8: insectworld.admin.ManualTriggerRequest
	(*ManualTriggerResponse)(nil),   // 9: insectworld.admin.ManualTriggerResponse
	(*BanPlayerRequest)(nil),        // 10: insectworld.admin.BanPlayerRequest
	(*BanPlayerResponse)(nil),       // 11: insectworld.admin.BanPlayerResponse
	(*UnbanPlayerRequest)(nil),      // 12: insectworld.admin.UnbanPlayerRequest
	(*UnbanPlayerResponse)(nil),     // 13: insectworld.admin.UnbanPlayerResponse
	(*PublishNoticeRequest)(nil),    // 14: insectworld.admin.PublishNoticeRequest
	(*PublishNoticeResponse)(nil),   // 15: insectworld.admin.PublishNoticeResponse
	(*common.RequestHeader)(nil),    // 16: insectworld.common.RequestHeader
	(*common.ResponseHeader)(nil),   // 17: insectworld.common.ResponseHeader
}
var file_proto_admin_admin_proto_depIdxs = []int32{
	16, // 0: insectworld.admin.ReloadConfigRequest.header:type_name -> insectworld.common.RequestHeader
	17, // 1: insectworld.admin.ReloadConfigResponse.header:type_name -> insectworld.common.ResponseHeader
	16, // 2: insectworld.admin.RollbackConfigRequest.header:type_name -> insectworld.common.RequestHeader
	17, // 3: insectworld.admin.RollbackConfigResponse.header:type_name -> insectworld.common.ResponseHeader
	16, // 4: insectworld.admin.ForceTransitionRequest.header:type_name -> insectworld.common.RequestHeader
	17, // 5: insectworld.admin.ForceTransitionResponse.header:type_name -> insectworld.common.ResponseHeader
	16, // 6: insectworld.admin.ForceResetRequest.header:type_name -> insectworld.common.RequestHeader
	17, // 7: insectworld.admin.ForceResetResponse.header:type_name -> insectworld.common.ResponseHeader
	16, // 8: insectworld.admin.ManualTriggerRequest.header:type_name -> insectworld.common.RequestHeader
	17, // 9: insectworld.admin.ManualTriggerResponse.header:type_name -> insectworld.common.ResponseHeader
	16, // 10: insectworld.admin.BanPlayerRequest.header:type_name -> insectworld.common.RequestHeader
	17, // 11: insectworld.admin.BanPlayerResponse.header:type_name -> insectworld.common.ResponseHeader
	16, // 12: insectworld.admin.UnbanPlayerRequest.header:type_name -> insectworld.common.RequestHeader
	17, // 13: insectworld.admin.UnbanPlayerResponse.header:type_name -> insectworld.common.ResponseHeader
	16, // 14: insectworld.admin.PublishNoticeRequest.header:type_name -> insectworld.common.RequestHeader
	17, // 15: insectworld.admin.PublishNoticeResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 16: insectworld.admin.AdminService.ReloadConfig:input_type -> insectworld.admin.ReloadConfigRequest
	2,  // 17: insectworld.admin.AdminService.RollbackConfig:input_type -> insectworld.admin.RollbackConfigRequest
	4,  // 18: insectworld.admin.AdminService.ForceTransitionPhase:input_type -> insectworld.admin.ForceTransitionRequest
	6,  // 19: insectworld.admin.AdminService.ForceResetSeason:input_type -> insectworld.admin.ForceResetRequest
	8,  // 20: insectworld.admin.AdminService.ManualTriggerEvent:input_type -> insectworld.admin.ManualTriggerRequest
	10, // 21: insectworld.admin.AdminService.BanPlayer:input_type -> insectworld.admin.BanPlayerRequest
	12, // 22: insectworld.admin.AdminService.UnbanPlayer:input_type -> insectworld.admin.UnbanPlayerRequest
	14, // 23: insectworld.admin.AdminService.PublishNotice:input_type -> insectworld.admin.PublishNoticeRequest
	1,  // 24: insectworld.admin.AdminService.ReloadConfig:output_type -> insectworld.admin.ReloadConfigResponse
	3,  // 25: insectworld.admin.AdminService.RollbackConfig:output_type -> insectworld.admin.RollbackConfigResponse
	5,  // 26: insectworld.admin.AdminService.ForceTransitionPhase:output_type -> insectworld.admin.ForceTransitionResponse
	7,  // 27: insectworld.admin.AdminService.ForceResetSeason:output_type -> insectworld.admin.ForceResetResponse
	9,  // 28: insectworld.admin.AdminService.ManualTriggerEvent:output_type -> insectworld.admin.ManualTriggerResponse
	11, // 29: insectworld.admin.AdminService.BanPlayer:output_type -> insectworld.admin.BanPlayerResponse
	13, // 30: insectworld.admin.AdminService.UnbanPlayer:output_type -> insectworld.admin.UnbanPlayerResponse
	15, // 31: insectworld.admin.AdminService.PublishNotice:output_type -> insectworld.admin.PublishNoticeResponse
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_admin_admin_proto_init() }
func file_proto_admin_admin_proto_init() {
	if File_proto_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_admin_proto_rawDesc), len(file_proto_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_admin_proto = out.File
	file_proto_admin_admin_proto_goTypes = nil
	file_proto_admin_admin_proto_depIdxs = nil
}
