// AdminService gRPC接口定义，运营管理操作协议。
// 对应design.md 2.2.2.7节，提供配置热更/赛季管理/事件触发/玩家管理/公告发布能力。
// 所有管理操作必须经过运营管理员鉴权+审计日志记录（安全设计.md）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/admin/admin.proto

package adminpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_ReloadConfig_FullMethodName         = "/insectworld.admin.AdminService/ReloadConfig"
	AdminService_RollbackConfig_FullMethodName       = "/insectworld.admin.AdminService/RollbackConfig"
	AdminService_ForceTransitionPhase_FullMethodName = "/insectworld.admin.AdminService/ForceTransitionPhase"
	AdminService_ForceResetSeason_FullMethodName     = "/insectworld.admin.AdminService/ForceResetSeason"
	AdminService_ManualTriggerEvent_FullMethodName   = "/insectworld.admin.AdminService/ManualTriggerEvent"
	AdminService_BanPlayer_FullMethodName            = "/insectworld.admin.AdminService/BanPlayer"
	AdminService_UnbanPlayer_FullMethodName          = "/insectworld.admin.AdminService/UnbanPlayer"
	AdminService_PublishNotice_FullMethodName        = "/insectworld.admin.AdminService/PublishNotice"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService 运营管理服务gRPC接口，提供运营管理操作。
type AdminServiceClient interface {
	// 配置管理
	ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error)
	RollbackConfig(ctx context.Context, in *RollbackConfigRequest, opts ...grpc.CallOption) (*RollbackConfigResponse, error)
	// 赛季管理
	ForceTransitionPhase(ctx context.Context, in *ForceTransitionRequest, opts ...grpc.CallOption) (*ForceTransitionResponse, error)
	ForceResetSeason(ctx context.Context, in *ForceResetRequest, opts ...grpc.CallOption) (*ForceResetResponse, error)
	// 事件管理
	ManualTriggerEvent(ctx context.Context, in *ManualTriggerRequest, opts ...grpc.CallOption) (*ManualTriggerResponse, error)
	// 玩家管理
	BanPlayer(ctx context.Context, in *BanPlayerRequest, opts ...grpc.CallOption) (*BanPlayerResponse, error)
	UnbanPlayer(ctx context.Context, in *UnbanPlayerRequest, opts ...grpc.CallOption) (*UnbanPlayerResponse, error)
	// 公告管理
	PublishNotice(ctx context.Context, in *PublishNoticeRequest, opts ...grpc.CallOption) (*PublishNoticeResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadConfigResponse)
	err := c.cc.Invoke(ctx, AdminService_ReloadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RollbackConfig(ctx context.Context, in *RollbackConfigRequest, opts ...grpc.CallOption) (*RollbackConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackConfigResponse)
	err := c.cc.Invoke(ctx, AdminService_RollbackConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ForceTransitionPhase(ctx context.Context, in *ForceTransitionRequest, opts ...grpc.CallOption) (*ForceTransitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceTransitionResponse)
	err := c.cc.Invoke(ctx, AdminService_ForceTransitionPhase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ForceResetSeason(ctx context.Context, in *ForceResetRequest, opts ...grpc.CallOption) (*ForceResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceResetResponse)
	err := c.cc.Invoke(ctx, AdminService_ForceResetSeason_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ManualTriggerEvent(ctx context.Context, in *ManualTriggerRequest, opts ...grpc.CallOption) (*ManualTriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManualTriggerResponse)
	err := c.cc.Invoke(ctx, AdminService_ManualTriggerEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) BanPlayer(ctx context.Context, in *BanPlayerRequest, opts ...grpc.CallOption) (*BanPlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanPlayerResponse)
	err := c.cc.Invoke(ctx, AdminService_BanPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UnbanPlayer(ctx context.Context, in *UnbanPlayerRequest, opts ...grpc.CallOption) (*UnbanPlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbanPlayerResponse)
	err := c.cc.Invoke(ctx, AdminService_UnbanPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PublishNotice(ctx context.Context, in *PublishNoticeRequest, opts ...grpc.CallOption) (*PublishNoticeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishNoticeResponse)
	err := c.cc.Invoke(ctx, AdminService_PublishNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService 运营管理服务gRPC接口，提供运营管理操作。
type AdminServiceServer interface {
	// 配置管理
	ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error)
	RollbackConfig(context.Context, *RollbackConfigRequest) (*RollbackConfigResponse, error)
	// 赛季管理
	ForceTransitionPhase(context.Context, *ForceTransitionRequest) (*ForceTransitionResponse, error)
	ForceResetSeason(context.Context, *ForceResetRequest) (*ForceResetResponse, error)
	// 事件管理
	ManualTriggerEvent(context.Context, *ManualTriggerRequest) (*ManualTriggerResponse, error)
	// 玩家管理
	BanPlayer(context.Context, *BanPlayerRequest) (*BanPlayerResponse, error)
	UnbanPlayer(context.Context, *UnbanPlayerRequest) (*UnbanPlayerResponse, error)
	// 公告管理
	PublishNotice(context.Context, *PublishNoticeRequest) (*PublishNoticeResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedAdminServiceServer) RollbackConfig(context.Context, *RollbackConfigRequest) (*RollbackConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackConfig not implemented")
}
func (UnimplementedAdminServiceServer) ForceTransitionPhase(context.Context, *ForceTransitionRequest) (*ForceTransitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceTransitionPhase not implemented")
}
func (UnimplementedAdminServiceServer) ForceResetSeason(context.Context, *ForceResetRequest) (*ForceResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceResetSeason not implemented")
}
func (UnimplementedAdminServiceServer) ManualTriggerEvent(context.Context, *ManualTriggerRequest) (*ManualTriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ManualTriggerEvent not implemented")
}
func (UnimplementedAdminServiceServer) BanPlayer(context.Context, *BanPlayerRequest) (*BanPlayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BanPlayer not implemented")
}
func (UnimplementedAdminServiceServer) UnbanPlayer(context.Context, *UnbanPlayerRequest) (*UnbanPlayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbanPlayer not implemented")
}
func (UnimplementedAdminServiceServer) PublishNotice(context.Context, *PublishNoticeRequest) (*PublishNoticeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishNotice not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ReloadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ReloadConfig(ctx, req.(*ReloadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RollbackConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RollbackConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RollbackConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RollbackConfig(ctx, req.(*RollbackConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ForceTransitionPhase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ForceTransitionPhase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ForceTransitionPhase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ForceTransitionPhase(ctx, req.(*ForceTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ForceResetSeason_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ForceResetSeason(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ForceResetSeason_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ForceResetSeason(ctx, req.(*ForceResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ManualTriggerEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManualTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ManualTriggerEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ManualTriggerEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ManualTriggerEvent(ctx, req.(*ManualTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_BanPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).BanPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_BanPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).BanPlayer(ctx, req.(*BanPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UnbanPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbanPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UnbanPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UnbanPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UnbanPlayer(ctx, req.(*UnbanPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PublishNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishNoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PublishNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PublishNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PublishNotice(ctx, req.(*PublishNoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insectworld.admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReloadConfig",
			Handler:    _AdminService_ReloadConfig_Handler,
		},
		{
			MethodName: "RollbackConfig",
			Handler:    _AdminService_RollbackConfig_Handler,
		},
		{
			MethodName: "ForceTransitionPhase",
			Handler:    _AdminService_ForceTransitionPhase_Handler,
		},
		{
			MethodName: "ForceResetSeason",
			Handler:    _AdminService_ForceResetSeason_Handler,
		},
		{
			MethodName: "ManualTriggerEvent",
			Handler:    _AdminService_ManualTriggerEvent_Handler,
		},
		{
			MethodName: "BanPlayer",
			Handler:    _AdminService_BanPlayer_Handler,
		},
		{
			MethodName: "UnbanPlayer",
			Handler:    _AdminService_UnbanPlayer_Handler,
		},
		{
			MethodName: "PublishNotice",
			Handler:    _AdminService_PublishNotice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin/admin.proto",
}
