// Building Service gRPC接口定义，提供建筑建造/升级/取消/加速相关操作。
// 对应《通用SLG框架共性抽离方案_终版》P0-2 建筑升级骨头（#14）与《契约冻结草案》4.3 清单。
// 契约冻结规则：本包为P3新增包 v1 冻结，字段编号不重用、消息只增不改、服务只加不改。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/building/building.proto

package buildingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuildingService_StartBuilding_FullMethodName      = "/insectworld.building.BuildingService/StartBuilding"
	BuildingService_UpgradeBuilding_FullMethodName    = "/insectworld.building.BuildingService/UpgradeBuilding"
	BuildingService_CancelBuilding_FullMethodName     = "/insectworld.building.BuildingService/CancelBuilding"
	BuildingService_AccelerateBuilding_FullMethodName = "/insectworld.building.BuildingService/AccelerateBuilding"
)

// BuildingServiceClient is the client API for BuildingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BuildingService 建筑服务gRPC接口，提供建造/升级状态机、升级队列、打断与加速操作。
// 建筑数值/升级规则/前置依赖留配置层（buildings 配置），本契约只承载机制指令与状态回传。
type BuildingServiceClient interface {
	// 发起建造，校验地块可建造性与前置依赖后进入建造队列
	StartBuilding(ctx context.Context, in *StartBuildingRequest, opts ...grpc.CallOption) (*StartBuildingResponse, error)
	// 升级建筑，校验等级上限与资源消耗后进入升级队列
	UpgradeBuilding(ctx context.Context, in *UpgradeBuildingRequest, opts ...grpc.CallOption) (*UpgradeBuildingResponse, error)
	// 取消建造/升级，已消耗资源按配置比例返还
	CancelBuilding(ctx context.Context, in *CancelBuildingRequest, opts ...grpc.CallOption) (*CancelBuildingResponse, error)
	// 加速建造/升级，消耗道具或资源立即完成当前任务
	AccelerateBuilding(ctx context.Context, in *AccelerateBuildingRequest, opts ...grpc.CallOption) (*AccelerateBuildingResponse, error)
}

type buildingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildingServiceClient(cc grpc.ClientConnInterface) BuildingServiceClient {
	return &buildingServiceClient{cc}
}

func (c *buildingServiceClient) StartBuilding(ctx context.Context, in *StartBuildingRequest, opts ...grpc.CallOption) (*StartBuildingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBuildingResponse)
	err := c.cc.Invoke(ctx, BuildingService_StartBuilding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildingServiceClient) UpgradeBuilding(ctx context.Context, in *UpgradeBuildingRequest, opts ...grpc.CallOption) (*UpgradeBuildingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeBuildingResponse)
	err := c.cc.Invoke(ctx, BuildingService_UpgradeBuilding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildingServiceClient) CancelBuilding(ctx context.Context, in *CancelBuildingRequest, opts ...grpc.CallOption) (*CancelBuildingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelBuildingResponse)
	err := c.cc.Invoke(ctx, BuildingService_CancelBuilding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildingServiceClient) AccelerateBuilding(ctx context.Context, in *AccelerateBuildingRequest, opts ...grpc.CallOption) (*AccelerateBuildingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccelerateBuildingResponse)
	err := c.cc.Invoke(ctx, BuildingService_AccelerateBuilding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildingServiceServer is the server API for BuildingService service.
// All implementations must embed UnimplementedBuildingServiceServer
// for forward compatibility.
//
// BuildingService 建筑服务gRPC接口，提供建造/升级状态机、升级队列、打断与加速操作。
// 建筑数值/升级规则/前置依赖留配置层（buildings 配置），本契约只承载机制指令与状态回传。
type BuildingServiceServer interface {
	// 发起建造，校验地块可建造性与前置依赖后进入建造队列
	StartBuilding(context.Context, *StartBuildingRequest) (*StartBuildingResponse, error)
	// 升级建筑，校验等级上限与资源消耗后进入升级队列
	UpgradeBuilding(context.Context, *UpgradeBuildingRequest) (*UpgradeBuildingResponse, error)
	// 取消建造/升级，已消耗资源按配置比例返还
	CancelBuilding(context.Context, *CancelBuildingRequest) (*CancelBuildingResponse, error)
	// 加速建造/升级，消耗道具或资源立即完成当前任务
	AccelerateBuilding(context.Context, *AccelerateBuildingRequest) (*AccelerateBuildingResponse, error)
	mustEmbedUnimplementedBuildingServiceServer()
}

// UnimplementedBuildingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildingServiceServer struct{}

func (UnimplementedBuildingServiceServer) StartBuilding(context.Context, *StartBuildingRequest) (*StartBuildingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBuilding not implemented")
}
func (UnimplementedBuildingServiceServer) UpgradeBuilding(context.Context, *UpgradeBuildingRequest) (*UpgradeBuildingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradeBuilding not implemented")
}
func (UnimplementedBuildingServiceServer) CancelBuilding(context.Context, *CancelBuildingRequest) (*CancelBuildingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBuilding not implemented")
}
func (UnimplementedBuildingServiceServer) AccelerateBuilding(context.Context, *AccelerateBuildingRequest) (*AccelerateBuildingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AccelerateBuilding not implemented")
}
func (UnimplementedBuildingServiceServer) mustEmbedUnimplementedBuildingServiceServer() {}
func (UnimplementedBuildingServiceServer) testEmbeddedByValue()                         {}

// UnsafeBuildingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildingServiceServer will
// result in compilation errors.
type UnsafeBuildingServiceServer interface {
	mustEmbedUnimplementedBuildingServiceServer()
}

func RegisterBuildingServiceServer(s grpc.ServiceRegistrar, srv BuildingServiceServer) {
	// If the following call panics, it indicates UnimplementedBuildingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildingService_ServiceDesc, srv)
}

func _BuildingService_StartBuilding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBuildingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildingServiceServer).StartBuilding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildingService_StartBuilding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildingServiceServer).StartBuilding(ctx, req.(*StartBuildingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildingService_UpgradeBuilding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeBuildingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildingServiceServer).UpgradeBuilding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildingService_UpgradeBuilding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildingServiceServer).UpgradeBuilding(ctx, req.(*UpgradeBuildingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildingService_CancelBuilding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBuildingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildingServiceServer).CancelBuilding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildingService_CancelBuilding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildingServiceServer).CancelBuilding(ctx, req.(*CancelBuildingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildingService_AccelerateBuilding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccelerateBuildingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildingServiceServer).AccelerateBuilding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildingService_AccelerateBuilding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildingServiceServer).AccelerateBuilding(ctx, req.(*AccelerateBuildingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildingService_ServiceDesc is the grpc.ServiceDesc for BuildingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insectworld.building.BuildingService",
	HandlerType: (*BuildingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartBuilding",
			Handler:    _BuildingService_StartBuilding_Handler,
		},
		{
			MethodName: "UpgradeBuilding",
			Handler:    _BuildingService_UpgradeBuilding_Handler,
		},
		{
			MethodName: "CancelBuilding",
			Handler:    _BuildingService_CancelBuilding_Handler,
		},
		{
			MethodName: "AccelerateBuilding",
			Handler:    _BuildingService_AccelerateBuilding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/building/building.proto",
}
