// Building Service gRPC接口定义，提供建筑建造/升级/取消/加速相关操作。
// 对应《通用SLG框架共性抽离方案_终版》P0-2 建筑升级骨头（#14）与《契约冻结草案》4.3 清单。
// 契约冻结规则：本包为P3新增包 v1 冻结，字段编号不重用、消息只增不改、服务只加不改。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: proto/building/building.proto

package buildingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	event "insectworld/server/shared/proto/event"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuildingState 建筑状态，建筑的当前快照。
type BuildingState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BuildingId     int64                  `protobuf:"varint,1,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`               // 建筑实例ID，全局唯一，由雪花算法生成（规范8用int64）
	BuildingTypeId int32                  `protobuf:"varint,2,opt,name=building_type_id,json=buildingTypeId,proto3" json:"building_type_id,omitempty"` // 建筑配置ID，对应buildings配置表（规范8用int32）
	Level          int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                                           // 当前等级，1级起（规范8用int32）
	Position       *common.Position       `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`                                      // 建筑所在地图坐标
	Status         int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                                         // 建筑状态：1=建造中 2=正常 3=升级中 4=已拆除
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildingState) Reset() {
	*x = BuildingState{}
	mi := &file_proto_building_building_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingState) ProtoMessage() {}

func (x *BuildingState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingState.ProtoReflect.Descriptor instead.
func (*BuildingState) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{0}
}

func (x *BuildingState) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

func (x *BuildingState) GetBuildingTypeId() int32 {
	if x != nil {
		return x.BuildingTypeId
	}
	return 0
}

func (x *BuildingState) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BuildingState) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BuildingState) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// BuildingUpgradeTask 建筑升级队列任务，升级/建造共用队列。
type BuildingUpgradeTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BuildingId     int64                  `protobuf:"varint,1,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`               // 建筑实例ID
	BuildingTypeId int32                  `protobuf:"varint,2,opt,name=building_type_id,json=buildingTypeId,proto3" json:"building_type_id,omitempty"` // 建筑配置ID
	TargetLevel    int32                  `protobuf:"varint,3,opt,name=target_level,json=targetLevel,proto3" json:"target_level,omitempty"`            // 目标等级，建造任务为1
	QueuePos       int32                  `protobuf:"varint,4,opt,name=queue_pos,json=queuePos,proto3" json:"queue_pos,omitempty"`                     // 队列位置，1为正在执行的任务
	StartTime      int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                  // 任务开始时间戳（毫秒）
	EndTime        int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                        // 任务结束时间戳（毫秒），0表示尚未排定
	Status         int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                         // 任务状态：1=等待 2=进行中 3=已完成 4=已取消
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildingUpgradeTask) Reset() {
	*x = BuildingUpgradeTask{}
	mi := &file_proto_building_building_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingUpgradeTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingUpgradeTask) ProtoMessage() {}

func (x *BuildingUpgradeTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingUpgradeTask.ProtoReflect.Descriptor instead.
func (*BuildingUpgradeTask) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{1}
}

func (x *BuildingUpgradeTask) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

func (x *BuildingUpgradeTask) GetBuildingTypeId() int32 {
	if x != nil {
		return x.BuildingTypeId
	}
	return 0
}

func (x *BuildingUpgradeTask) GetTargetLevel() int32 {
	if x != nil {
		return x.TargetLevel
	}
	return 0
}

func (x *BuildingUpgradeTask) GetQueuePos() int32 {
	if x != nil {
		return x.QueuePos
	}
	return 0
}

func (x *BuildingUpgradeTask) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BuildingUpgradeTask) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BuildingUpgradeTask) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// StartBuildingRequest 建造请求
type StartBuildingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Header         *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                          // 请求头
	BuildingTypeId int32                  `protobuf:"varint,2,opt,name=building_type_id,json=buildingTypeId,proto3" json:"building_type_id,omitempty"` // 建筑配置ID
	Position       *common.Position       `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`                                      // 建造坐标，需通过世界服务校验可建造性
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartBuildingRequest) Reset() {
	*x = StartBuildingRequest{}
	mi := &file_proto_building_building_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBuildingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBuildingRequest) ProtoMessage() {}

func (x *StartBuildingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBuildingRequest.ProtoReflect.Descriptor instead.
func (*StartBuildingRequest) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{2}
}

func (x *StartBuildingRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StartBuildingRequest) GetBuildingTypeId() int32 {
	if x != nil {
		return x.BuildingTypeId
	}
	return 0
}

func (x *StartBuildingRequest) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// StartBuildingResponse 建造响应
type StartBuildingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	Task          *BuildingUpgradeTask   `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`     // 已入队的建造任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBuildingResponse) Reset() {
	*x = StartBuildingResponse{}
	mi := &file_proto_building_building_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBuildingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBuildingResponse) ProtoMessage() {}

func (x *StartBuildingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBuildingResponse.ProtoReflect.Descriptor instead.
func (*StartBuildingResponse) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{3}
}

func (x *StartBuildingResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StartBuildingResponse) GetTask() *BuildingUpgradeTask {
	if x != nil {
		return x.Task
	}
	return nil
}

// UpgradeBuildingRequest 升级请求
type UpgradeBuildingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                            // 请求头
	BuildingId    int64                  `protobuf:"varint,2,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"` // 建筑实例ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeBuildingRequest) Reset() {
	*x = UpgradeBuildingRequest{}
	mi := &file_proto_building_building_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeBuildingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeBuildingRequest) ProtoMessage() {}

func (x *UpgradeBuildingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeBuildingRequest.ProtoReflect.Descriptor instead.
func (*UpgradeBuildingRequest) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{4}
}

func (x *UpgradeBuildingRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpgradeBuildingRequest) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

// UpgradeBuildingResponse 升级响应
type UpgradeBuildingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	Task          *BuildingUpgradeTask   `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`     // 已入队的升级任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeBuildingResponse) Reset() {
	*x = UpgradeBuildingResponse{}
	mi := &file_proto_building_building_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeBuildingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeBuildingResponse) ProtoMessage() {}

func (x *UpgradeBuildingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeBuildingResponse.ProtoReflect.Descriptor instead.
func (*UpgradeBuildingResponse) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{5}
}

func (x *UpgradeBuildingResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpgradeBuildingResponse) GetTask() *BuildingUpgradeTask {
	if x != nil {
		return x.Task
	}
	return nil
}

// CancelBuildingRequest 取消请求
type CancelBuildingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                            // 请求头
	BuildingId    int64                  `protobuf:"varint,2,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"` // 建筑实例ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBuildingRequest) Reset() {
	*x = CancelBuildingRequest{}
	mi := &file_proto_building_building_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBuildingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBuildingRequest) ProtoMessage() {}

func (x *CancelBuildingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBuildingRequest.ProtoReflect.Descriptor instead.
func (*CancelBuildingRequest) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{6}
}

func (x *CancelBuildingRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CancelBuildingRequest) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

// CancelBuildingResponse 取消响应
type CancelBuildingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`     // 响应头
	Building      *BuildingState         `protobuf:"bytes,2,opt,name=building,proto3" json:"building,omitempty"` // 取消后的建筑状态快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBuildingResponse) Reset() {
	*x = CancelBuildingResponse{}
	mi := &file_proto_building_building_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBuildingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBuildingResponse) ProtoMessage() {}

func (x *CancelBuildingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBuildingResponse.ProtoReflect.Descriptor instead.
func (*CancelBuildingResponse) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{7}
}

func (x *CancelBuildingResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CancelBuildingResponse) GetBuilding() *BuildingState {
	if x != nil {
		return x.Building
	}
	return nil
}

// AccelerateBuildingRequest 加速请求
type AccelerateBuildingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                            // 请求头
	BuildingId    int64                  `protobuf:"varint,2,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"` // 建筑实例ID
	CostType      int32                  `protobuf:"varint,3,opt,name=cost_type,json=costType,proto3" json:"cost_type,omitempty"`       // 消耗类型：1=道具 2=资源 3=金币
	CostAmount    int64                  `protobuf:"varint,4,opt,name=cost_amount,json=costAmount,proto3" json:"cost_amount,omitempty"` // 消耗数量，服务端按剩余时间与配置单价校验
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccelerateBuildingRequest) Reset() {
	*x = AccelerateBuildingRequest{}
	mi := &file_proto_building_building_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccelerateBuildingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccelerateBuildingRequest) ProtoMessage() {}

func (x *AccelerateBuildingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccelerateBuildingRequest.ProtoReflect.Descriptor instead.
func (*AccelerateBuildingRequest) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{8}
}

func (x *AccelerateBuildingRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AccelerateBuildingRequest) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

func (x *AccelerateBuildingRequest) GetCostType() int32 {
	if x != nil {
		return x.CostType
	}
	return 0
}

func (x *AccelerateBuildingRequest) GetCostAmount() int64 {
	if x != nil {
		return x.CostAmount
	}
	return 0
}

// AccelerateBuildingResponse 加速响应
type AccelerateBuildingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	Task          *BuildingUpgradeTask   `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`     // 加速后的任务，完成时任务状态为已完成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccelerateBuildingResponse) Reset() {
	*x = AccelerateBuildingResponse{}
	mi := &file_proto_building_building_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccelerateBuildingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccelerateBuildingResponse) ProtoMessage() {}

func (x *AccelerateBuildingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccelerateBuildingResponse.ProtoReflect.Descriptor instead.
func (*AccelerateBuildingResponse) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{9}
}

func (x *AccelerateBuildingResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AccelerateBuildingResponse) GetTask() *BuildingUpgradeTask {
	if x != nil {
		return x.Task
	}
	return nil
}

// BuildingConstructedEvent 建筑建造完成事件，建造任务完成后发布。
// 主题命名 event.building.constructed，订阅方用于刷新地图实体与建筑功能开放。
type BuildingConstructedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Base           *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                              // 基础事件信息
	BuildingId     int64                  `protobuf:"varint,2,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`               // 建筑实例ID
	BuildingTypeId int32                  `protobuf:"varint,3,opt,name=building_type_id,json=buildingTypeId,proto3" json:"building_type_id,omitempty"` // 建筑配置ID
	Position       *common.Position       `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`                                      // 建筑坐标
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildingConstructedEvent) Reset() {
	*x = BuildingConstructedEvent{}
	mi := &file_proto_building_building_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingConstructedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingConstructedEvent) ProtoMessage() {}

func (x *BuildingConstructedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingConstructedEvent.ProtoReflect.Descriptor instead.
func (*BuildingConstructedEvent) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{10}
}

func (x *BuildingConstructedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *BuildingConstructedEvent) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

func (x *BuildingConstructedEvent) GetBuildingTypeId() int32 {
	if x != nil {
		return x.BuildingTypeId
	}
	return 0
}

func (x *BuildingConstructedEvent) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// BuildingUpgradedEvent 建筑升级完成事件，升级任务完成后发布。
// 主题命名 event.building.upgraded，订阅方用于刷新建筑等级与功能解锁。
type BuildingUpgradedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Base           *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                              // 基础事件信息
	BuildingId     int64                  `protobuf:"varint,2,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`               // 建筑实例ID
	BuildingTypeId int32                  `protobuf:"varint,3,opt,name=building_type_id,json=buildingTypeId,proto3" json:"building_type_id,omitempty"` // 建筑配置ID
	OldLevel       int32                  `protobuf:"varint,4,opt,name=old_level,json=oldLevel,proto3" json:"old_level,omitempty"`                     // 升级前等级
	NewLevel       int32                  `protobuf:"varint,5,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`                     // 升级后等级
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildingUpgradedEvent) Reset() {
	*x = BuildingUpgradedEvent{}
	mi := &file_proto_building_building_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingUpgradedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingUpgradedEvent) ProtoMessage() {}

func (x *BuildingUpgradedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingUpgradedEvent.ProtoReflect.Descriptor instead.
func (*BuildingUpgradedEvent) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{11}
}

func (x *BuildingUpgradedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *BuildingUpgradedEvent) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

func (x *BuildingUpgradedEvent) GetBuildingTypeId() int32 {
	if x != nil {
		return x.BuildingTypeId
	}
	return 0
}

func (x *BuildingUpgradedEvent) GetOldLevel() int32 {
	if x != nil {
		return x.OldLevel
	}
	return 0
}

func (x *BuildingUpgradedEvent) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

// BuildingUpgradeCancelledEvent 建筑升级取消事件，取消建造/升级后发布。
// 主题命名 event.building.upgrade_cancelled，订阅方用于退还占用的队列与部分资源。
type BuildingUpgradeCancelledEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Base           *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                              // 基础事件信息
	BuildingId     int64                  `protobuf:"varint,2,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`               // 建筑实例ID
	BuildingTypeId int32                  `protobuf:"varint,3,opt,name=building_type_id,json=buildingTypeId,proto3" json:"building_type_id,omitempty"` // 建筑配置ID
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                                           // 取消时的建筑等级
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildingUpgradeCancelledEvent) Reset() {
	*x = BuildingUpgradeCancelledEvent{}
	mi := &file_proto_building_building_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingUpgradeCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingUpgradeCancelledEvent) ProtoMessage() {}

func (x *BuildingUpgradeCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_building_building_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingUpgradeCancelledEvent.ProtoReflect.Descriptor instead.
func (*BuildingUpgradeCancelledEvent) Descriptor() ([]byte, []int) {
	return file_proto_building_building_proto_rawDescGZIP(), []int{12}
}

func (x *BuildingUpgradeCancelledEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *BuildingUpgradeCancelledEvent) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

func (x *BuildingUpgradeCancelledEvent) GetBuildingTypeId() int32 {
	if x != nil {
		return x.BuildingTypeId
	}
	return 0
}

func (x *BuildingUpgradeCancelledEvent) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_proto_building_building_proto protoreflect.FileDescriptor

const file_proto_building_building_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/building/building.proto\x12\x14insectworld.building\x1a\x19proto/common/common.proto\x1a\x1eproto/event/domain_event.proto\"\xc2\x01\n" +
	"\rBuildingState\x12\x1f\n" +
	"\vbuilding_id\x18\x01 \x01(\x03R\n" +
	"buildingId\x12(\n" +
	"\x10building_type_id\x18\x02 \x01(\x05R\x0ebuildingTypeId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x128\n" +
	"\bposition\x18\x04 \x01(\v2\x1c.insectworld.common.PositionR\bposition\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"\xf2\x01\n" +
	"\x13BuildingUpgradeTask\x12\x1f\n" +
	"\vbuilding_id\x18\x01 \x01(\x03R\n" +
	"buildingId\x12(\n" +
	"\x10building_type_id\x18\x02 \x01(\x05R\x0ebuildingTypeId\x12!\n" +
	"\ftarget_level\x18\x03 \x01(\x05R\vtargetLevel\x12\x1b\n" +
	"\tqueue_pos\x18\x04 \x01(\x05R\bqueuePos\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"\xb5\x01\n" +
	"\x14StartBuildingRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12(\n" +
	"\x10building_type_id\x18\x02 \x01(\x05R\x0ebuildingTypeId\x128\n" +
	"\bposition\x18\x03 \x01(\v2\x1c.insectworld.common.PositionR\bposition\"\x92\x01\n" +
	"\x15StartBuildingResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12=\n" +
	"\x04task\x18\x02 \x01(\v2).insectworld.building.BuildingUpgradeTaskR\x04task\"t\n" +
	"\x16UpgradeBuildingRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vbuilding_id\x18\x02 \x01(\x03R\n" +
	"buildingId\"\x94\x01\n" +
	"\x17UpgradeBuildingResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12=\n" +
	"\x04task\x18\x02 \x01(\v2).insectworld.building.BuildingUpgradeTaskR\x04task\"s\n" +
	"\x15CancelBuildingRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vbuilding_id\x18\x02 \x01(\x03R\n" +
	"buildingId\"\x95\x01\n" +
	"\x16CancelBuildingResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12?\n" +
	"\bbuilding\x18\x02 \x01(\v2#.insectworld.building.BuildingStateR\bbuilding\"\xb5\x01\n" +
	"\x19AccelerateBuildingRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1f\n" +
	"\vbuilding_id\x18\x02 \x01(\x03R\n" +
	"buildingId\x12\x1b\n" +
	"\tcost_type\x18\x03 \x01(\x05R\bcostType\x12\x1f\n" +
	"\vcost_amount\x18\x04 \x01(\x03R\n" +
	"costAmount\"\x97\x01\n" +
	"\x1aAccelerateBuildingResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12=\n" +
	"\x04task\x18\x02 \x01(\v2).insectworld.building.BuildingUpgradeTaskR\x04task\"\xd3\x01\n" +
	"\x18BuildingConstructedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1f\n" +
	"\vbuilding_id\x18\x02 \x01(\x03R\n" +
	"buildingId\x12(\n" +
	"\x10building_type_id\x18\x03 \x01(\x05R\x0ebuildingTypeId\x128\n" +
	"\bposition\x18\x04 \x01(\v2\x1c.insectworld.common.PositionR\bposition\"\xd0\x01\n" +
	"\x15BuildingUpgradedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1f\n" +
	"\vbuilding_id\x18\x02 \x01(\x03R\n" +
	"buildingId\x12(\n" +
	"\x10building_type_id\x18\x03 \x01(\x05R\x0ebuildingTypeId\x12\x1b\n" +
	"\told_level\x18\x04 \x01(\x05R\boldLevel\x12\x1b\n" +
	"\tnew_level\x18\x05 \x01(\x05R\bnewLevel\"\xb4\x01\n" +
	"\x1dBuildingUpgradeCancelledEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1f\n" +
	"\vbuilding_id\x18\x02 \x01(\x03R\n" +
	"buildingId\x12(\n" +
	"\x10building_type_id\x18\x03 \x01(\x05R\x0ebuildingTypeId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level2\xd1\x03\n" +
	"\x0fBuildingService\x12h\n" +
	"\rStartBuilding\x12*.insectworld.building.StartBuildingRequest\x1a+.insectworld.building.StartBuildingResponse\x12n\n" +
	"\x0fUpgradeBuilding\x12,.insectworld.building.UpgradeBuildingRequest\x1a-.insectworld.building.UpgradeBuildingResponse\x12k\n" +
	"\x0eCancelBuilding\x12+.insectworld.building.CancelBuildingRequest\x1a,.insectworld.building.CancelBuildingResponse\x12w\n" +
	"\x12AccelerateBuilding\x12/.insectworld.building.AccelerateBuildingRequest\x1a0.insectworld.building.AccelerateBuildingResponseB'Z%insectworld/proto/building;buildingpbb\x06proto3"

var (
	file_proto_building_building_proto_rawDescOnce sync.Once
	file_proto_building_building_proto_rawDescData []byte
)

func file_proto_building_building_proto_rawDescGZIP() []byte {
	file_proto_building_building_proto_rawDescOnce.Do(func() {
		file_proto_building_building_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_building_building_proto_rawDesc), len(file_proto_building_building_proto_rawDesc)))
	})
	return file_proto_building_building_proto_rawDescData
}

var file_proto_building_building_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_building_building_proto_goTypes = []any{
	(*BuildingState)(nil),                 // 0: insectworld.building.BuildingState
	(*BuildingUpgradeTask)(nil),           // 1: insectworld.building.BuildingUpgradeTask
	(*StartBuildingRequest)(nil),          // 2: insectworld.building.StartBuildingRequest
	(*StartBuildingResponse)(nil),         // 3: insectworld.building.StartBuildingResponse
	(*UpgradeBuildingRequest)(nil),        // 4: insectworld.building.UpgradeBuildingRequest
	(*UpgradeBuildingResponse)(nil),       // 5: insectworld.building.UpgradeBuildingResponse
	(*CancelBuildingRequest)(nil),         // 6: insectworld.building.CancelBuildingRequest
	(*CancelBuildingResponse)(nil),        // 7: insectworld.building.CancelBuildingResponse
	(*AccelerateBuildingRequest)(nil),     // 8: insectworld.building.AccelerateBuildingRequest
	(*AccelerateBuildingResponse)(nil),    // 9: insectworld.building.AccelerateBuildingResponse
	(*BuildingConstructedEvent)(nil),      // 10: insectworld.building.BuildingConstructedEvent
	(*BuildingUpgradedEvent)(nil),         // 11: insectworld.building.BuildingUpgradedEvent
	(*BuildingUpgradeCancelledEvent)(nil), // 12: insectworld.building.BuildingUpgradeCancelledEvent
	(*common.Position)(nil),               // 13: insectworld.common.Position
	(*common.RequestHeader)(nil),          // 14: insectworld.common.RequestHeader
	(*common.ResponseHeader)(nil),         // 15: insectworld.common.ResponseHeader
	(*event.DomainEvent)(nil),             // 16: insectworld.event.DomainEvent
}
var file_proto_building_building_proto_depIdxs = []int32{
	13, // 0: insectworld.building.BuildingState.position:type_name -> insectworld.common.Position
	14, // 1: insectworld.building.StartBuildingRequest.header:type_name -> insectworld.common.RequestHeader
	13, // 2: insectworld.building.StartBuildingRequest.position:type_name -> insectworld.common.Position
	15, // 3: insectworld.building.StartBuildingResponse.header:type_name -> insectworld.common.ResponseHeader
	1,  // 4: insectworld.building.StartBuildingResponse.task:type_name -> insectworld.building.BuildingUpgradeTask
	14, // 5: insectworld.building.UpgradeBuildingRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 6: insectworld.building.UpgradeBuildingResponse.header:type_name -> insectworld.common.ResponseHeader
	1,  // 7: insectworld.building.UpgradeBuildingResponse.task:type_name -> insectworld.building.BuildingUpgradeTask
	14, // 8: insectworld.building.CancelBuildingRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 9: insectworld.building.CancelBuildingResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 10: insectworld.building.CancelBuildingResponse.building:type_name -> insectworld.building.BuildingState
	14, // 11: insectworld.building.AccelerateBuildingRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 12: insectworld.building.AccelerateBuildingResponse.header:type_name -> insectworld.common.ResponseHeader
	1,  // 13: insectworld.building.AccelerateBuildingResponse.task:type_name -> insectworld.building.BuildingUpgradeTask
	16, // 14: insectworld.building.BuildingConstructedEvent.base:type_name -> insectworld.event.DomainEvent
	13, // 15: insectworld.building.BuildingConstructedEvent.position:type_name -> insectworld.common.Position
	16, // 16: insectworld.building.BuildingUpgradedEvent.base:type_name -> insectworld.event.DomainEvent
	16, // 17: insectworld.building.BuildingUpgradeCancelledEvent.base:type_name -> insectworld.event.DomainEvent
	2,  // 18: insectworld.building.BuildingService.StartBuilding:input_type -> insectworld.building.StartBuildingRequest
	4,  // 19: insectworld.building.BuildingService.UpgradeBuilding:input_type -> insectworld.building.UpgradeBuildingRequest
	6,  // 20: insectworld.building.BuildingService.CancelBuilding:input_type -> insectworld.building.CancelBuildingRequest
	8,  // 21: insectworld.building.BuildingService.AccelerateBuilding:input_type -> insectworld.building.AccelerateBuildingRequest
	3,  // 22: insectworld.building.BuildingService.StartBuilding:output_type -> insectworld.building.StartBuildingResponse
	5,  // 23: insectworld.building.BuildingService.UpgradeBuilding:output_type -> insectworld.building.UpgradeBuildingResponse
	7,  // 24: insectworld.building.BuildingService.CancelBuilding:output_type -> insectworld.building.CancelBuildingResponse
	9,  // 25: insectworld.building.BuildingService.AccelerateBuilding:output_type -> insectworld.building.AccelerateBuildingResponse
	22, // [22:26] is the sub-list for method output_type
	18, // [18:22] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_building_building_proto_init() }
func file_proto_building_building_proto_init() {
	if File_proto_building_building_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_building_building_proto_rawDesc), len(file_proto_building_building_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_building_building_proto_goTypes,
		DependencyIndexes: file_proto_building_building_proto_depIdxs,
		MessageInfos:      file_proto_building_building_proto_msgTypes,
	}.Build()
	File_proto_building_building_proto = out.File
	file_proto_building_building_proto_goTypes = nil
	file_proto_building_building_proto_depIdxs = nil
}
