// Player Profile Service gRPC接口定义，提供玩家档案/注册登录/等级经验/昵称相关操作。
// 对应《通用SLG框架共性抽离方案_终版》P0-1 玩家档案骨头（#13）与《契约冻结草案》4.3 清单。
// 契约冻结规则：本包为P3新增包 v1 冻结，字段编号不重用、消息只增不改、服务只加不改。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/player/player.proto

package playerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayerProfileService_Register_FullMethodName       = "/insectworld.player.PlayerProfileService/Register"
	PlayerProfileService_Login_FullMethodName          = "/insectworld.player.PlayerProfileService/Login"
	PlayerProfileService_GetProfile_FullMethodName     = "/insectworld.player.PlayerProfileService/GetProfile"
	PlayerProfileService_UpdateNickname_FullMethodName = "/insectworld.player.PlayerProfileService/UpdateNickname"
	PlayerProfileService_AddExperience_FullMethodName  = "/insectworld.player.PlayerProfileService/AddExperience"
)

// PlayerProfileServiceClient is the client API for PlayerProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlayerProfileService 玩家档案服务gRPC接口，提供注册/登录/资料/昵称/经验操作。
// 玩家档案是全部玩法系统的owner基础，其他骨头（建筑/背包/科技）均以 player_id 归属。
type PlayerProfileServiceClient interface {
	// 注册新玩家账号，成功返回档案快照
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 玩家登录，返回会话令牌与档案快照
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// 查询玩家档案，player_id 传 0 时使用请求头中的玩家ID
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	// 修改玩家昵称，昵称需满足配置的合法字符与长度校验
	UpdateNickname(ctx context.Context, in *UpdateNicknameRequest, opts ...grpc.CallOption) (*UpdateNicknameResponse, error)
	// 增加玩家经验值，经验达到升级阈值时自动升级并发布 PlayerLevelUpEvent
	AddExperience(ctx context.Context, in *AddExperienceRequest, opts ...grpc.CallOption) (*AddExperienceResponse, error)
}

type playerProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerProfileServiceClient(cc grpc.ClientConnInterface) PlayerProfileServiceClient {
	return &playerProfileServiceClient{cc}
}

func (c *playerProfileServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, PlayerProfileService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerProfileServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, PlayerProfileService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerProfileServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, PlayerProfileService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerProfileServiceClient) UpdateNickname(ctx context.Context, in *UpdateNicknameRequest, opts ...grpc.CallOption) (*UpdateNicknameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNicknameResponse)
	err := c.cc.Invoke(ctx, PlayerProfileService_UpdateNickname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerProfileServiceClient) AddExperience(ctx context.Context, in *AddExperienceRequest, opts ...grpc.CallOption) (*AddExperienceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddExperienceResponse)
	err := c.cc.Invoke(ctx, PlayerProfileService_AddExperience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerProfileServiceServer is the server API for PlayerProfileService service.
// All implementations must embed UnimplementedPlayerProfileServiceServer
// for forward compatibility.
//
// PlayerProfileService 玩家档案服务gRPC接口，提供注册/登录/资料/昵称/经验操作。
// 玩家档案是全部玩法系统的owner基础，其他骨头（建筑/背包/科技）均以 player_id 归属。
type PlayerProfileServiceServer interface {
	// 注册新玩家账号，成功返回档案快照
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 玩家登录，返回会话令牌与档案快照
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// 查询玩家档案，player_id 传 0 时使用请求头中的玩家ID
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	// 修改玩家昵称，昵称需满足配置的合法字符与长度校验
	UpdateNickname(context.Context, *UpdateNicknameRequest) (*UpdateNicknameResponse, error)
	// 增加玩家经验值，经验达到升级阈值时自动升级并发布 PlayerLevelUpEvent
	AddExperience(context.Context, *AddExperienceRequest) (*AddExperienceResponse, error)
	mustEmbedUnimplementedPlayerProfileServiceServer()
}

// UnimplementedPlayerProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerProfileServiceServer struct{}

func (UnimplementedPlayerProfileServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPlayerProfileServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedPlayerProfileServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedPlayerProfileServiceServer) UpdateNickname(context.Context, *UpdateNicknameRequest) (*UpdateNicknameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNickname not implemented")
}
func (UnimplementedPlayerProfileServiceServer) AddExperience(context.Context, *AddExperienceRequest) (*AddExperienceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddExperience not implemented")
}
func (UnimplementedPlayerProfileServiceServer) mustEmbedUnimplementedPlayerProfileServiceServer() {}
func (UnimplementedPlayerProfileServiceServer) testEmbeddedByValue()                              {}

// UnsafePlayerProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerProfileServiceServer will
// result in compilation errors.
type UnsafePlayerProfileServiceServer interface {
	mustEmbedUnimplementedPlayerProfileServiceServer()
}

func RegisterPlayerProfileServiceServer(s grpc.ServiceRegistrar, srv PlayerProfileServiceServer) {
	// If the following call panics, it indicates UnimplementedPlayerProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerProfileService_ServiceDesc, srv)
}

func _PlayerProfileService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerProfileServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerProfileService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerProfileServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerProfileService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerProfileServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerProfileService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerProfileServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerProfileService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerProfileServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerProfileService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerProfileServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerProfileService_UpdateNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNicknameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerProfileServiceServer).UpdateNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerProfileService_UpdateNickname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerProfileServiceServer).UpdateNickname(ctx, req.(*UpdateNicknameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerProfileService_AddExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerProfileServiceServer).AddExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerProfileService_AddExperience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerProfileServiceServer).AddExperience(ctx, req.(*AddExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerProfileService_ServiceDesc is the grpc.ServiceDesc for PlayerProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insectworld.player.PlayerProfileService",
	HandlerType: (*PlayerProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PlayerProfileService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _PlayerProfileService_Login_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _PlayerProfileService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateNickname",
			Handler:    _PlayerProfileService_UpdateNickname_Handler,
		},
		{
			MethodName: "AddExperience",
			Handler:    _PlayerProfileService_AddExperience_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/player/player.proto",
}
