// Player Profile Service gRPC接口定义，提供玩家档案/注册登录/等级经验/昵称相关操作。
// 对应《通用SLG框架共性抽离方案_终版》P0-1 玩家档案骨头（#13）与《契约冻结草案》4.3 清单。
// 契约冻结规则：本包为P3新增包 v1 冻结，字段编号不重用、消息只增不改、服务只加不改。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: proto/player/player.proto

package playerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	event "insectworld/server/shared/proto/event"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlayerProfile 玩家档案，玩家在各玩法系统中的归属主数据。
type PlayerProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`    // 玩家ID，全局唯一，由雪花算法生成（规范8用int64）
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                     // 玩家昵称，展示名，由玩家自行修改
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                          // 玩家等级，经验达到阈值后升级（规范8用int32）
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`                              // 当前经验值，累计经验值，升级不清零（规范8用int64）
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 注册时间戳（毫秒），创建档案时写入
	Avatar        int32                  `protobuf:"varint,6,opt,name=avatar,proto3" json:"avatar,omitempty"`                        // 头像配置ID，对应配置表，0表示使用默认头像（规范8用int32）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfile) Reset() {
	*x = PlayerProfile{}
	mi := &file_proto_player_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfile) ProtoMessage() {}

func (x *PlayerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfile.ProtoReflect.Descriptor instead.
func (*PlayerProfile) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerProfile) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerProfile) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerProfile) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerProfile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PlayerProfile) GetAvatar() int32 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

// RegisterRequest 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`     // 请求头
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`   // 玩家账号，登录唯一标识，字符串类型（账号非离散量，不走整型规范）
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // 登录密码，服务端必须哈希存储，禁止明文落库与写日志
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"` // 初始昵称，可为空时由服务端生成默认昵称
	Avatar        int32                  `protobuf:"varint,5,opt,name=avatar,proto3" json:"avatar,omitempty"`    // 初始头像配置ID，0表示使用默认头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_player_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RegisterRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterRequest) GetAvatar() int32 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

// RegisterResponse 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`   // 响应头
	Profile       *PlayerProfile         `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"` // 注册成功后的玩家档案快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_player_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RegisterResponse) GetProfile() *PlayerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// LoginRequest 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`     // 请求头
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`   // 玩家账号
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // 登录密码，传输层加密，服务端比对哈希
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_player_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse 登录响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`   // 响应头
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`     // 会话令牌，后续请求通过鉴权中间件校验，令牌为不透明字符串由认证协议强制
	Profile       *PlayerProfile         `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"` // 登录成功后的玩家档案快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_player_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetProfile() *PlayerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// GetProfileRequest 查询玩家档案请求
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家ID，0表示使用请求头中的玩家ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_player_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetProfileRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// GetProfileResponse 查询玩家档案响应
type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`   // 响应头
	Profile       *PlayerProfile         `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"` // 玩家档案
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_proto_player_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfileResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetProfileResponse) GetProfile() *PlayerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// UpdateNicknameRequest 修改昵称请求
type UpdateNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                              // 请求头
	NewNickname   string                 `protobuf:"bytes,2,opt,name=new_nickname,json=newNickname,proto3" json:"new_nickname,omitempty"` // 新昵称，需满足配置的长度与字符校验规则
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNicknameRequest) Reset() {
	*x = UpdateNicknameRequest{}
	mi := &file_proto_player_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNicknameRequest) ProtoMessage() {}

func (x *UpdateNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNicknameRequest.ProtoReflect.Descriptor instead.
func (*UpdateNicknameRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNicknameRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpdateNicknameRequest) GetNewNickname() string {
	if x != nil {
		return x.NewNickname
	}
	return ""
}

// UpdateNicknameResponse 修改昵称响应
type UpdateNicknameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`   // 响应头
	Profile       *PlayerProfile         `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"` // 更新后的玩家档案快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNicknameResponse) Reset() {
	*x = UpdateNicknameResponse{}
	mi := &file_proto_player_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNicknameResponse) ProtoMessage() {}

func (x *UpdateNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNicknameResponse.ProtoReflect.Descriptor instead.
func (*UpdateNicknameResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNicknameResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpdateNicknameResponse) GetProfile() *PlayerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// AddExperienceRequest 增加经验请求
type AddExperienceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`  // 请求头
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // 经验增量，正数增加，负数表示扣减（防刷校验由服务端完成）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExperienceRequest) Reset() {
	*x = AddExperienceRequest{}
	mi := &file_proto_player_player_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExperienceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExperienceRequest) ProtoMessage() {}

func (x *AddExperienceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExperienceRequest.ProtoReflect.Descriptor instead.
func (*AddExperienceRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{9}
}

func (x *AddExperienceRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AddExperienceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// AddExperienceResponse 增加经验响应
type AddExperienceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                         // 响应头
	Profile       *PlayerProfile         `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`                       // 更新后的玩家档案快照
	LeveledUp     bool                   `protobuf:"varint,3,opt,name=leveled_up,json=leveledUp,proto3" json:"leveled_up,omitempty"` // 本次是否触发升级，客户端据此播放升级表现
	NewLevel      int32                  `protobuf:"varint,4,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`    // 升级后的等级，未升级时为原等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExperienceResponse) Reset() {
	*x = AddExperienceResponse{}
	mi := &file_proto_player_player_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExperienceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExperienceResponse) ProtoMessage() {}

func (x *AddExperienceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExperienceResponse.ProtoReflect.Descriptor instead.
func (*AddExperienceResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{10}
}

func (x *AddExperienceResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AddExperienceResponse) GetProfile() *PlayerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *AddExperienceResponse) GetLeveledUp() bool {
	if x != nil {
		return x.LeveledUp
	}
	return false
}

func (x *AddExperienceResponse) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

// PlayerRegisteredEvent 玩家注册事件，注册成功后发布。
// 主题命名 event.player.registered，订阅方用于初始化玩家在各系统的档案。
type PlayerRegisteredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                          // 基础事件信息，复用event包版本机制
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 新注册玩家ID
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`                    // 玩家账号
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`                  // 初始昵称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRegisteredEvent) Reset() {
	*x = PlayerRegisteredEvent{}
	mi := &file_proto_player_player_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRegisteredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRegisteredEvent) ProtoMessage() {}

func (x *PlayerRegisteredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRegisteredEvent.ProtoReflect.Descriptor instead.
func (*PlayerRegisteredEvent) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerRegisteredEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PlayerRegisteredEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerRegisteredEvent) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PlayerRegisteredEvent) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// PlayerLevelUpEvent 玩家升级事件，经验达到升级阈值后发布。
// 主题命名 event.player.level_up，订阅方用于解锁玩法或刷新成长线。
type PlayerLevelUpEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                          // 基础事件信息
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 升级玩家ID
	OldLevel      int32                  `protobuf:"varint,3,opt,name=old_level,json=oldLevel,proto3" json:"old_level,omitempty"` // 升级前等级
	NewLevel      int32                  `protobuf:"varint,4,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"` // 升级后等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLevelUpEvent) Reset() {
	*x = PlayerLevelUpEvent{}
	mi := &file_proto_player_player_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLevelUpEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLevelUpEvent) ProtoMessage() {}

func (x *PlayerLevelUpEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLevelUpEvent.ProtoReflect.Descriptor instead.
func (*PlayerLevelUpEvent) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerLevelUpEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PlayerLevelUpEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerLevelUpEvent) GetOldLevel() int32 {
	if x != nil {
		return x.OldLevel
	}
	return 0
}

func (x *PlayerLevelUpEvent) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

// PlayerProfileUpdatedEvent 玩家档案更新事件，昵称/头像等展示信息变更后发布。
// 主题命名 event.player.profile_updated，订阅方用于同步社交展示数据。
type PlayerProfileUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                          // 基础事件信息
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 档案被更新的玩家ID
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`                  // 更新后的昵称
	Avatar        int32                  `protobuf:"varint,4,opt,name=avatar,proto3" json:"avatar,omitempty"`                     // 更新后的头像配置ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfileUpdatedEvent) Reset() {
	*x = PlayerProfileUpdatedEvent{}
	mi := &file_proto_player_player_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfileUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfileUpdatedEvent) ProtoMessage() {}

func (x *PlayerProfileUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfileUpdatedEvent.ProtoReflect.Descriptor instead.
func (*PlayerProfileUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerProfileUpdatedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PlayerProfileUpdatedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerProfileUpdatedEvent) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerProfileUpdatedEvent) GetAvatar() int32 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

var File_proto_player_player_proto protoreflect.FileDescriptor

const file_proto_player_player_proto_rawDesc = "" +
	"\n" +
	"\x19proto/player/player.proto\x12\x12insectworld.player\x1a\x19proto/common/common.proto\x1a\x1eproto/event/domain_event.proto\"\xa7\x01\n" +
	"\rPlayerProfile\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\x05R\x06avatar\"\xb6\x01\n" +
	"\x0fRegisterRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\x05R\x06avatar\"\x8b\x01\n" +
	"\x10RegisterResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12;\n" +
	"\aprofile\x18\x02 \x01(\v2!.insectworld.player.PlayerProfileR\aprofile\"\x7f\n" +
	"\fLoginRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x9e\x01\n" +
	"\rLoginResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12;\n" +
	"\aprofile\x18\x03 \x01(\v2!.insectworld.player.PlayerProfileR\aprofile\"k\n" +
	"\x11GetProfileRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\"\x8d\x01\n" +
	"\x12GetProfileResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12;\n" +
	"\aprofile\x18\x02 \x01(\v2!.insectworld.player.PlayerProfileR\aprofile\"u\n" +
	"\x15UpdateNicknameRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12!\n" +
	"\fnew_nickname\x18\x02 \x01(\tR\vnewNickname\"\x91\x01\n" +
	"\x16UpdateNicknameResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12;\n" +
	"\aprofile\x18\x02 \x01(\v2!.insectworld.player.PlayerProfileR\aprofile\"i\n" +
	"\x14AddExperienceRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\xcc\x01\n" +
	"\x15AddExperienceResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12;\n" +
	"\aprofile\x18\x02 \x01(\v2!.insectworld.player.PlayerProfileR\aprofile\x12\x1d\n" +
	"\n" +
	"leveled_up\x18\x03 \x01(\bR\tleveledUp\x12\x1b\n" +
	"\tnew_level\x18\x04 \x01(\x05R\bnewLevel\"\x9e\x01\n" +
	"\x15PlayerRegisteredEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"\x9f\x01\n" +
	"\x12PlayerLevelUpEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1b\n" +
	"\told_level\x18\x03 \x01(\x05R\boldLevel\x12\x1b\n" +
	"\tnew_level\x18\x04 \x01(\x05R\bnewLevel\"\xa0\x01\n" +
	"\x19PlayerProfileUpdatedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\x05R\x06avatar2\xe7\x03\n" +
	"\x14PlayerProfileService\x12U\n" +
	"\bRegister\x12#.insectworld.player.RegisterRequest\x1a$.insectworld.player.RegisterResponse\x12L\n" +
	"\x05Login\x12 .insectworld.player.LoginRequest\x1a!.insectworld.player.LoginResponse\x12[\n" +
	"\n" +
	"GetProfile\x12%.insectworld.player.GetProfileRequest\x1a&.insectworld.player.GetProfileResponse\x12g\n" +
	"\x0eUpdateNickname\x12).insectworld.player.UpdateNicknameRequest\x1a*.insectworld.player.UpdateNicknameResponse\x12d\n" +
	"\rAddExperience\x12(.insectworld.player.AddExperienceRequest\x1a).insectworld.player.AddExperienceResponseB#Z!insectworld/proto/player;playerpbb\x06proto3"

var (
	file_proto_player_player_proto_rawDescOnce sync.Once
	file_proto_player_player_proto_rawDescData []byte
)

func file_proto_player_player_proto_rawDescGZIP() []byte {
	file_proto_player_player_proto_rawDescOnce.Do(func() {
		file_proto_player_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_player_player_proto_rawDesc), len(file_proto_player_player_proto_rawDesc)))
	})
	return file_proto_player_player_proto_rawDescData
}

var file_proto_player_player_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_player_player_proto_goTypes = []any{
	(*PlayerProfile)(nil),             // 0: insectworld.player.PlayerProfile
	(*RegisterRequest)(nil),           // 1: insectworld.player.RegisterRequest
	(*RegisterResponse)(nil),          // 2: insectworld.player.RegisterResponse
	(*LoginRequest)(nil),              // 3: insectworld.player.LoginRequest
	(*LoginResponse)(nil),             // 4: insectworld.player.LoginResponse
	(*GetProfileRequest)(nil),         // 5: insectworld.player.GetProfileRequest
	(*GetProfileResponse)(nil),        // 6: insectworld.player.GetProfileResponse
	(*UpdateNicknameRequest)(nil),     // 7: insectworld.player.UpdateNicknameRequest
	(*UpdateNicknameResponse)(nil),    // 8: insectworld.player.UpdateNicknameResponse
	(*AddExperienceRequest)(nil),      // 9: insectworld.player.AddExperienceRequest
	(*AddExperienceResponse)(nil),     // 10: insectworld.player.AddExperienceResponse
	(*PlayerRegisteredEvent)(nil),     // 11: insectworld.player.PlayerRegisteredEvent
	(*PlayerLevelUpEvent)(nil),        // 12: insectworld.player.PlayerLevelUpEvent
	(*PlayerProfileUpdatedEvent)(nil), // 13: insectworld.player.PlayerProfileUpdatedEvent
	(*common.RequestHeader)(nil),      // 14: insectworld.common.RequestHeader
	(*common.ResponseHeader)(nil),     // 15: insectworld.common.ResponseHeader
	(*event.DomainEvent)(nil),         // 16: insectworld.event.DomainEvent
}
var file_proto_player_player_proto_depIdxs = []int32{
	14, // 0: insectworld.player.RegisterRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 1: insectworld.player.RegisterResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 2: insectworld.player.RegisterResponse.profile:type_name -> insectworld.player.PlayerProfile
	14, // 3: insectworld.player.LoginRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 4: insectworld.player.LoginResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 5: insectworld.player.LoginResponse.profile:type_name -> insectworld.player.PlayerProfile
	14, // 6: insectworld.player.GetProfileRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 7: insectworld.player.GetProfileResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 8: insectworld.player.GetProfileResponse.profile:type_name -> insectworld.player.PlayerProfile
	14, // 9: insectworld.player.UpdateNicknameRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 10: insectworld.player.UpdateNicknameResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 11: insectworld.player.UpdateNicknameResponse.profile:type_name -> insectworld.player.PlayerProfile
	14, // 12: insectworld.player.AddExperienceRequest.header:type_name -> insectworld.common.RequestHeader
	15, // 13: insectworld.player.AddExperienceResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 14: insectworld.player.AddExperienceResponse.profile:type_name -> insectworld.player.PlayerProfile
	16, // 15: insectworld.player.PlayerRegisteredEvent.base:type_name -> insectworld.event.DomainEvent
	16, // 16: insectworld.player.PlayerLevelUpEvent.base:type_name -> insectworld.event.DomainEvent
	16, // 17: insectworld.player.PlayerProfileUpdatedEvent.base:type_name -> insectworld.event.DomainEvent
	1,  // 18: insectworld.player.PlayerProfileService.Register:input_type -> insectworld.player.RegisterRequest
	3,  // 19: insectworld.player.PlayerProfileService.Login:input_type -> insectworld.player.LoginRequest
	5,  // 20: insectworld.player.PlayerProfileService.GetProfile:input_type -> insectworld.player.GetProfileRequest
	7,  // 21: insectworld.player.PlayerProfileService.UpdateNickname:input_type -> insectworld.player.UpdateNicknameRequest
	9,  // 22: insectworld.player.PlayerProfileService.AddExperience:input_type -> insectworld.player.AddExperienceRequest
	2,  // 23: insectworld.player.PlayerProfileService.Register:output_type -> insectworld.player.RegisterResponse
	4,  // 24: insectworld.player.PlayerProfileService.Login:output_type -> insectworld.player.LoginResponse
	6,  // 25: insectworld.player.PlayerProfileService.GetProfile:output_type -> insectworld.player.GetProfileResponse
	8,  // 26: insectworld.player.PlayerProfileService.UpdateNickname:output_type -> insectworld.player.UpdateNicknameResponse
	10, // 27: insectworld.player.PlayerProfileService.AddExperience:output_type -> insectworld.player.AddExperienceResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_player_player_proto_init() }
func file_proto_player_player_proto_init() {
	if File_proto_player_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_player_player_proto_rawDesc), len(file_proto_player_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_player_player_proto_goTypes,
		DependencyIndexes: file_proto_player_player_proto_depIdxs,
		MessageInfos:      file_proto_player_player_proto_msgTypes,
	}.Build()
	File_proto_player_player_proto = out.File
	file_proto_player_player_proto_goTypes = nil
	file_proto_player_player_proto_depIdxs = nil
}
