// Social Service gRPC接口定义，提供玩家/联盟/外交相关查询与操作。
// 对应design.md 2.2.2.4节接口清单，保留现有接口并新增联盟领土查询接口。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/social/social.proto

package socialpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPlayerInfoRequest 查询玩家信息请求
type GetPlayerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家ID（规范8用int64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoRequest) Reset() {
	*x = GetPlayerInfoRequest{}
	mi := &file_proto_social_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoRequest) ProtoMessage() {}

func (x *GetPlayerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayerInfoRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetPlayerInfoRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// PlayerInfoResponse 玩家信息响应
type PlayerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                  // 响应头
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`             // 玩家ID
	PlayerName    string                 `protobuf:"bytes,3,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`        // 玩家名称
	AllianceId    int64                  `protobuf:"varint,4,opt,name=alliance_id,json=allianceId,proto3" json:"alliance_id,omitempty"`       // 所属联盟ID，0表示无联盟
	AllianceRole  int32                  `protobuf:"varint,5,opt,name=alliance_role,json=allianceRole,proto3" json:"alliance_role,omitempty"` // 联盟职位（规范8用int32枚举）
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`                                   // 玩家等级
	Online        bool                   `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`                                 // 是否在线
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfoResponse) Reset() {
	*x = PlayerInfoResponse{}
	mi := &file_proto_social_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoResponse) ProtoMessage() {}

func (x *PlayerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoResponse.ProtoReflect.Descriptor instead.
func (*PlayerInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfoResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PlayerInfoResponse) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInfoResponse) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerInfoResponse) GetAllianceId() int64 {
	if x != nil {
		return x.AllianceId
	}
	return 0
}

func (x *PlayerInfoResponse) GetAllianceRole() int32 {
	if x != nil {
		return x.AllianceRole
	}
	return 0
}

func (x *PlayerInfoResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerInfoResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// GetDiplomacyRequest 查询外交状态请求
type GetDiplomacyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                 // 请求头
	AllianceIdA   int64                  `protobuf:"varint,2,opt,name=alliance_id_a,json=allianceIdA,proto3" json:"alliance_id_a,omitempty"` // 联盟A ID
	AllianceIdB   int64                  `protobuf:"varint,3,opt,name=alliance_id_b,json=allianceIdB,proto3" json:"alliance_id_b,omitempty"` // 联盟B ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiplomacyRequest) Reset() {
	*x = GetDiplomacyRequest{}
	mi := &file_proto_social_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiplomacyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiplomacyRequest) ProtoMessage() {}

func (x *GetDiplomacyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiplomacyRequest.ProtoReflect.Descriptor instead.
func (*GetDiplomacyRequest) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{2}
}

func (x *GetDiplomacyRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetDiplomacyRequest) GetAllianceIdA() int64 {
	if x != nil {
		return x.AllianceIdA
	}
	return 0
}

func (x *GetDiplomacyRequest) GetAllianceIdB() int64 {
	if x != nil {
		return x.AllianceIdB
	}
	return 0
}

// DiplomacyResponse 外交状态响应
type DiplomacyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                           // 响应头
	DiplomacyStatus int32                  `protobuf:"varint,2,opt,name=diplomacy_status,json=diplomacyStatus,proto3" json:"diplomacy_status,omitempty"` // 外交状态：1=和平 2=同盟 3=战争 4=停战（规范8用int32）
	ExpireTime      int64                  `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`                // 外交状态过期时间戳（毫秒），0表示永久
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiplomacyResponse) Reset() {
	*x = DiplomacyResponse{}
	mi := &file_proto_social_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiplomacyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiplomacyResponse) ProtoMessage() {}

func (x *DiplomacyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiplomacyResponse.ProtoReflect.Descriptor instead.
func (*DiplomacyResponse) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{3}
}

func (x *DiplomacyResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DiplomacyResponse) GetDiplomacyStatus() int32 {
	if x != nil {
		return x.DiplomacyStatus
	}
	return 0
}

func (x *DiplomacyResponse) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

// CheckPermissionRequest 校验权限请求
type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家ID
	Action        int32                  `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`                     // 操作类型（规范8用int32枚举）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_proto_social_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{4}
}

func (x *CheckPermissionRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CheckPermissionRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CheckPermissionRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// PermissionResponse 权限校验响应
type PermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`    // 响应头
	Allowed       bool                   `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed,omitempty"` // 是否允许
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResponse) Reset() {
	*x = PermissionResponse{}
	mi := &file_proto_social_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResponse) ProtoMessage() {}

func (x *PermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResponse.ProtoReflect.Descriptor instead.
func (*PermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{5}
}

func (x *PermissionResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

// GetTerritoryRequest 查询联盟领土请求（新增接口）
type GetTerritoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家ID，查询其所在联盟的领土
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerritoryRequest) Reset() {
	*x = GetTerritoryRequest{}
	mi := &file_proto_social_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerritoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerritoryRequest) ProtoMessage() {}

func (x *GetTerritoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerritoryRequest.ProtoReflect.Descriptor instead.
func (*GetTerritoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{6}
}

func (x *GetTerritoryRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetTerritoryRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// TerritoryResponse 联盟领土响应（新增接口）
type TerritoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                            // 响应头
	AllianceId    int64                  `protobuf:"varint,2,opt,name=alliance_id,json=allianceId,proto3" json:"alliance_id,omitempty"` // 联盟ID
	Territories   []*TerritoryCell       `protobuf:"bytes,3,rep,name=territories,proto3" json:"territories,omitempty"`                  // 领土格子列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerritoryResponse) Reset() {
	*x = TerritoryResponse{}
	mi := &file_proto_social_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerritoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerritoryResponse) ProtoMessage() {}

func (x *TerritoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerritoryResponse.ProtoReflect.Descriptor instead.
func (*TerritoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{7}
}

func (x *TerritoryResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TerritoryResponse) GetAllianceId() int64 {
	if x != nil {
		return x.AllianceId
	}
	return 0
}

func (x *TerritoryResponse) GetTerritories() []*TerritoryCell {
	if x != nil {
		return x.Territories
	}
	return nil
}

// TerritoryCell 单个领土格子
type TerritoryCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *common.Position       `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`                                 // 领土格子坐标
	TerritoryType int32                  `protobuf:"varint,2,opt,name=territory_type,json=territoryType,proto3" json:"territory_type,omitempty"` // 领土类型：1=核心 2=普通 3=争议（规范8用int32）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerritoryCell) Reset() {
	*x = TerritoryCell{}
	mi := &file_proto_social_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerritoryCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerritoryCell) ProtoMessage() {}

func (x *TerritoryCell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerritoryCell.ProtoReflect.Descriptor instead.
func (*TerritoryCell) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{8}
}

func (x *TerritoryCell) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *TerritoryCell) GetTerritoryType() int32 {
	if x != nil {
		return x.TerritoryType
	}
	return 0
}

var File_proto_social_social_proto protoreflect.FileDescriptor

const file_proto_social_social_proto_rawDesc = "" +
	"\n" +
	"\x19proto/social/social.proto\x12\x12insectworld.social\x1a\x19proto/common/common.proto\"n\n" +
	"\x14GetPlayerInfoRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\"\x82\x02\n" +
	"\x12PlayerInfoResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x03 \x01(\tR\n" +
	"playerName\x12\x1f\n" +
	"\valliance_id\x18\x04 \x01(\x03R\n" +
	"allianceId\x12#\n" +
	"\ralliance_role\x18\x05 \x01(\x05R\fallianceRole\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x16\n" +
	"\x06online\x18\a \x01(\bR\x06online\"\x98\x01\n" +
	"\x13GetDiplomacyRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\"\n" +
	"\ralliance_id_a\x18\x02 \x01(\x03R\vallianceIdA\x12\"\n" +
	"\ralliance_id_b\x18\x03 \x01(\x03R\vallianceIdB\"\x9b\x01\n" +
	"\x11DiplomacyResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12)\n" +
	"\x10diplomacy_status\x18\x02 \x01(\x05R\x0fdiplomacyStatus\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\x03R\n" +
	"expireTime\"\x88\x01\n" +
	"\x16CheckPermissionRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\x05R\x06action\"j\n" +
	"\x12PermissionResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x18\n" +
	"\aallowed\x18\x02 \x01(\bR\aallowed\"m\n" +
	"\x13GetTerritoryRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\"\xb5\x01\n" +
	"\x11TerritoryResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1f\n" +
	"\valliance_id\x18\x02 \x01(\x03R\n" +
	"allianceId\x12C\n" +
	"\vterritories\x18\x03 \x03(\v2!.insectworld.social.TerritoryCellR\vterritories\"p\n" +
	"\rTerritoryCell\x128\n" +
	"\bposition\x18\x01 \x01(\v2\x1c.insectworld.common.PositionR\bposition\x12%\n" +
	"\x0eterritory_type\x18\x02 \x01(\x05R\rterritoryType2\xb5\x03\n" +
	"\rSocialService\x12a\n" +
	"\rGetPlayerInfo\x12(.insectworld.social.GetPlayerInfoRequest\x1a&.insectworld.social.PlayerInfoResponse\x12d\n" +
	"\x12GetDiplomacyStatus\x12'.insectworld.social.GetDiplomacyRequest\x1a%.insectworld.social.DiplomacyResponse\x12m\n" +
	"\x17CheckAlliancePermission\x12*.insectworld.social.CheckPermissionRequest\x1a&.insectworld.social.PermissionResponse\x12l\n" +
	"\x1aGetPlayerAllianceTerritory\x12'.insectworld.social.GetTerritoryRequest\x1a%.insectworld.social.TerritoryResponseB#Z!insectworld/server/shared/proto/social;socialpbb\x06proto3"

var (
	file_proto_social_social_proto_rawDescOnce sync.Once
	file_proto_social_social_proto_rawDescData []byte
)

func file_proto_social_social_proto_rawDescGZIP() []byte {
	file_proto_social_social_proto_rawDescOnce.Do(func() {
		file_proto_social_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_social_social_proto_rawDesc), len(file_proto_social_social_proto_rawDesc)))
	})
	return file_proto_social_social_proto_rawDescData
}

var file_proto_social_social_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_social_social_proto_goTypes = []any{
	(*GetPlayerInfoRequest)(nil),   // 0: insectworld.social.GetPlayerInfoRequest
	(*PlayerInfoResponse)(nil),     // 1: insectworld.social.PlayerInfoResponse
	(*GetDiplomacyRequest)(nil),    // 2: insectworld.social.GetDiplomacyRequest
	(*DiplomacyResponse)(nil),      // 3: insectworld.social.DiplomacyResponse
	(*CheckPermissionRequest)(nil), // 4: insectworld.social.CheckPermissionRequest
	(*PermissionResponse)(nil),     // 5: insectworld.social.PermissionResponse
	(*GetTerritoryRequest)(nil),    // 6: insectworld.social.GetTerritoryRequest
	(*TerritoryResponse)(nil),      // 7: insectworld.social.TerritoryResponse
	(*TerritoryCell)(nil),          // 8: insectworld.social.TerritoryCell
	(*common.RequestHeader)(nil),   // 9: insectworld.common.RequestHeader
	(*common.ResponseHeader)(nil),  // 10: insectworld.common.ResponseHeader
	(*common.Position)(nil),        // 11: insectworld.common.Position
}
var file_proto_social_social_proto_depIdxs = []int32{
	9,  // 0: insectworld.social.GetPlayerInfoRequest.header:type_name -> insectworld.common.RequestHeader
	10, // 1: insectworld.social.PlayerInfoResponse.header:type_name -> insectworld.common.ResponseHeader
	9,  // 2: insectworld.social.GetDiplomacyRequest.header:type_name -> insectworld.common.RequestHeader
	10, // 3: insectworld.social.DiplomacyResponse.header:type_name -> insectworld.common.ResponseHeader
	9,  // 4: insectworld.social.CheckPermissionRequest.header:type_name -> insectworld.common.RequestHeader
	10, // 5: insectworld.social.PermissionResponse.header:type_name -> insectworld.common.ResponseHeader
	9,  // 6: insectworld.social.GetTerritoryRequest.header:type_name -> insectworld.common.RequestHeader
	10, // 7: insectworld.social.TerritoryResponse.header:type_name -> insectworld.common.ResponseHeader
	8,  // 8: insectworld.social.TerritoryResponse.territories:type_name -> insectworld.social.TerritoryCell
	11, // 9: insectworld.social.TerritoryCell.position:type_name -> insectworld.common.Position
	0,  // 10: insectworld.social.SocialService.GetPlayerInfo:input_type -> insectworld.social.GetPlayerInfoRequest
	2,  // 11: insectworld.social.SocialService.GetDiplomacyStatus:input_type -> insectworld.social.GetDiplomacyRequest
	4,  // 12: insectworld.social.SocialService.CheckAlliancePermission:input_type -> insectworld.social.CheckPermissionRequest
	6,  // 13: insectworld.social.SocialService.GetPlayerAllianceTerritory:input_type -> insectworld.social.GetTerritoryRequest
	1,  // 14: insectworld.social.SocialService.GetPlayerInfo:output_type -> insectworld.social.PlayerInfoResponse
	3,  // 15: insectworld.social.SocialService.GetDiplomacyStatus:output_type -> insectworld.social.DiplomacyResponse
	5,  // 16: insectworld.social.SocialService.CheckAlliancePermission:output_type -> insectworld.social.PermissionResponse
	7,  // 17: insectworld.social.SocialService.GetPlayerAllianceTerritory:output_type -> insectworld.social.TerritoryResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_social_social_proto_init() }
func file_proto_social_social_proto_init() {
	if File_proto_social_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_social_social_proto_rawDesc), len(file_proto_social_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_social_social_proto_goTypes,
		DependencyIndexes: file_proto_social_social_proto_depIdxs,
		MessageInfos:      file_proto_social_social_proto_msgTypes,
	}.Build()
	File_proto_social_social_proto = out.File
	file_proto_social_social_proto_goTypes = nil
	file_proto_social_social_proto_depIdxs = nil
}
