// Social Service gRPC接口定义，提供玩家/联盟/外交相关查询与操作。
// 对应design.md 2.2.2.4节接口清单，保留现有接口并新增联盟领土查询接口。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/social/social.proto

package socialpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocialService_GetPlayerInfo_FullMethodName              = "/insectworld.social.SocialService/GetPlayerInfo"
	SocialService_GetDiplomacyStatus_FullMethodName         = "/insectworld.social.SocialService/GetDiplomacyStatus"
	SocialService_CheckAlliancePermission_FullMethodName    = "/insectworld.social.SocialService/CheckAlliancePermission"
	SocialService_GetPlayerAllianceTerritory_FullMethodName = "/insectworld.social.SocialService/GetPlayerAllianceTerritory"
)

// SocialServiceClient is the client API for SocialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SocialService Social服务gRPC接口，提供社交相关查询。
type SocialServiceClient interface {
	// 现有接口
	GetPlayerInfo(ctx context.Context, in *GetPlayerInfoRequest, opts ...grpc.CallOption) (*PlayerInfoResponse, error)
	GetDiplomacyStatus(ctx context.Context, in *GetDiplomacyRequest, opts ...grpc.CallOption) (*DiplomacyResponse, error)
	CheckAlliancePermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*PermissionResponse, error)
	// 新增接口
	GetPlayerAllianceTerritory(ctx context.Context, in *GetTerritoryRequest, opts ...grpc.CallOption) (*TerritoryResponse, error)
}

type socialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialServiceClient(cc grpc.ClientConnInterface) SocialServiceClient {
	return &socialServiceClient{cc}
}

func (c *socialServiceClient) GetPlayerInfo(ctx context.Context, in *GetPlayerInfoRequest, opts ...grpc.CallOption) (*PlayerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerInfoResponse)
	err := c.cc.Invoke(ctx, SocialService_GetPlayerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetDiplomacyStatus(ctx context.Context, in *GetDiplomacyRequest, opts ...grpc.CallOption) (*DiplomacyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiplomacyResponse)
	err := c.cc.Invoke(ctx, SocialService_GetDiplomacyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) CheckAlliancePermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*PermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionResponse)
	err := c.cc.Invoke(ctx, SocialService_CheckAlliancePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetPlayerAllianceTerritory(ctx context.Context, in *GetTerritoryRequest, opts ...grpc.CallOption) (*TerritoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerritoryResponse)
	err := c.cc.Invoke(ctx, SocialService_GetPlayerAllianceTerritory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServiceServer is the server API for SocialService service.
// All implementations must embed UnimplementedSocialServiceServer
// for forward compatibility.
//
// SocialService Social服务gRPC接口，提供社交相关查询。
type SocialServiceServer interface {
	// 现有接口
	GetPlayerInfo(context.Context, *GetPlayerInfoRequest) (*PlayerInfoResponse, error)
	GetDiplomacyStatus(context.Context, *GetDiplomacyRequest) (*DiplomacyResponse, error)
	CheckAlliancePermission(context.Context, *CheckPermissionRequest) (*PermissionResponse, error)
	// 新增接口
	GetPlayerAllianceTerritory(context.Context, *GetTerritoryRequest) (*TerritoryResponse, error)
	mustEmbedUnimplementedSocialServiceServer()
}

// UnimplementedSocialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServiceServer struct{}

func (UnimplementedSocialServiceServer) GetPlayerInfo(context.Context, *GetPlayerInfoRequest) (*PlayerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerInfo not implemented")
}
func (UnimplementedSocialServiceServer) GetDiplomacyStatus(context.Context, *GetDiplomacyRequest) (*DiplomacyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiplomacyStatus not implemented")
}
func (UnimplementedSocialServiceServer) CheckAlliancePermission(context.Context, *CheckPermissionRequest) (*PermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAlliancePermission not implemented")
}
func (UnimplementedSocialServiceServer) GetPlayerAllianceTerritory(context.Context, *GetTerritoryRequest) (*TerritoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerAllianceTerritory not implemented")
}
func (UnimplementedSocialServiceServer) mustEmbedUnimplementedSocialServiceServer() {}
func (UnimplementedSocialServiceServer) testEmbeddedByValue()                       {}

// UnsafeSocialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServiceServer will
// result in compilation errors.
type UnsafeSocialServiceServer interface {
	mustEmbedUnimplementedSocialServiceServer()
}

func RegisterSocialServiceServer(s grpc.ServiceRegistrar, srv SocialServiceServer) {
	// If the following call panics, it indicates UnimplementedSocialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialService_ServiceDesc, srv)
}

func _SocialService_GetPlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetPlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetPlayerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetPlayerInfo(ctx, req.(*GetPlayerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetDiplomacyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiplomacyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetDiplomacyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetDiplomacyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetDiplomacyStatus(ctx, req.(*GetDiplomacyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_CheckAlliancePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).CheckAlliancePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_CheckAlliancePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).CheckAlliancePermission(ctx, req.(*CheckPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetPlayerAllianceTerritory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTerritoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetPlayerAllianceTerritory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetPlayerAllianceTerritory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetPlayerAllianceTerritory(ctx, req.(*GetTerritoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialService_ServiceDesc is the grpc.ServiceDesc for SocialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insectworld.social.SocialService",
	HandlerType: (*SocialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerInfo",
			Handler:    _SocialService_GetPlayerInfo_Handler,
		},
		{
			MethodName: "GetDiplomacyStatus",
			Handler:    _SocialService_GetDiplomacyStatus_Handler,
		},
		{
			MethodName: "CheckAlliancePermission",
			Handler:    _SocialService_CheckAlliancePermission_Handler,
		},
		{
			MethodName: "GetPlayerAllianceTerritory",
			Handler:    _SocialService_GetPlayerAllianceTerritory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/social/social.proto",
}
