// Combat Service gRPC接口定义，提供战斗/属性/战报相关查询与操作。
// 对应design.md 2.2.2.2节接口清单，保留现有接口并新增战报查询接口。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/combat/combat.proto

package combatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CombatService_GetEntityAttributes_FullMethodName = "/insectworld.combat.CombatService/GetEntityAttributes"
	CombatService_GetCombatState_FullMethodName      = "/insectworld.combat.CombatService/GetCombatState"
	CombatService_GetCombatReport_FullMethodName     = "/insectworld.combat.CombatService/GetCombatReport"
)

// CombatServiceClient is the client API for CombatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CombatService Combat服务gRPC接口，提供战斗相关查询。
type CombatServiceClient interface {
	// 现有接口
	GetEntityAttributes(ctx context.Context, in *GetAttributesRequest, opts ...grpc.CallOption) (*AttributesResponse, error)
	GetCombatState(ctx context.Context, in *GetCombatStateRequest, opts ...grpc.CallOption) (*CombatStateResponse, error)
	// 新增接口
	GetCombatReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type combatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCombatServiceClient(cc grpc.ClientConnInterface) CombatServiceClient {
	return &combatServiceClient{cc}
}

func (c *combatServiceClient) GetEntityAttributes(ctx context.Context, in *GetAttributesRequest, opts ...grpc.CallOption) (*AttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributesResponse)
	err := c.cc.Invoke(ctx, CombatService_GetEntityAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatServiceClient) GetCombatState(ctx context.Context, in *GetCombatStateRequest, opts ...grpc.CallOption) (*CombatStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombatStateResponse)
	err := c.cc.Invoke(ctx, CombatService_GetCombatState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatServiceClient) GetCombatReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, CombatService_GetCombatReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CombatServiceServer is the server API for CombatService service.
// All implementations must embed UnimplementedCombatServiceServer
// for forward compatibility.
//
// CombatService Combat服务gRPC接口，提供战斗相关查询。
type CombatServiceServer interface {
	// 现有接口
	GetEntityAttributes(context.Context, *GetAttributesRequest) (*AttributesResponse, error)
	GetCombatState(context.Context, *GetCombatStateRequest) (*CombatStateResponse, error)
	// 新增接口
	GetCombatReport(context.Context, *ReportRequest) (*ReportResponse, error)
	mustEmbedUnimplementedCombatServiceServer()
}

// UnimplementedCombatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCombatServiceServer struct{}

func (UnimplementedCombatServiceServer) GetEntityAttributes(context.Context, *GetAttributesRequest) (*AttributesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntityAttributes not implemented")
}
func (UnimplementedCombatServiceServer) GetCombatState(context.Context, *GetCombatStateRequest) (*CombatStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCombatState not implemented")
}
func (UnimplementedCombatServiceServer) GetCombatReport(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCombatReport not implemented")
}
func (UnimplementedCombatServiceServer) mustEmbedUnimplementedCombatServiceServer() {}
func (UnimplementedCombatServiceServer) testEmbeddedByValue()                       {}

// UnsafeCombatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CombatServiceServer will
// result in compilation errors.
type UnsafeCombatServiceServer interface {
	mustEmbedUnimplementedCombatServiceServer()
}

func RegisterCombatServiceServer(s grpc.ServiceRegistrar, srv CombatServiceServer) {
	// If the following call panics, it indicates UnimplementedCombatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CombatService_ServiceDesc, srv)
}

func _CombatService_GetEntityAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatServiceServer).GetEntityAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatService_GetEntityAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatServiceServer).GetEntityAttributes(ctx, req.(*GetAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatService_GetCombatState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCombatStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatServiceServer).GetCombatState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatService_GetCombatState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatServiceServer).GetCombatState(ctx, req.(*GetCombatStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatService_GetCombatReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatServiceServer).GetCombatReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatService_GetCombatReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatServiceServer).GetCombatReport(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CombatService_ServiceDesc is the grpc.ServiceDesc for CombatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CombatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insectworld.combat.CombatService",
	HandlerType: (*CombatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntityAttributes",
			Handler:    _CombatService_GetEntityAttributes_Handler,
		},
		{
			MethodName: "GetCombatState",
			Handler:    _CombatService_GetCombatState_Handler,
		},
		{
			MethodName: "GetCombatReport",
			Handler:    _CombatService_GetCombatReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/combat/combat.proto",
}
