// Combat Service gRPC接口定义，提供战斗/属性/战报相关查询与操作。
// 对应design.md 2.2.2.2节接口清单，保留现有接口并新增战报查询接口。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/combat/combat.proto

package combatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetAttributesRequest 查询参战方属性请求
type GetAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 实体ID（规范8用int64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributesRequest) Reset() {
	*x = GetAttributesRequest{}
	mi := &file_proto_combat_combat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributesRequest) ProtoMessage() {}

func (x *GetAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_combat_combat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributesRequest.ProtoReflect.Descriptor instead.
func (*GetAttributesRequest) Descriptor() ([]byte, []int) {
	return file_proto_combat_combat_proto_rawDescGZIP(), []int{0}
}

func (x *GetAttributesRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetAttributesRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

// AttributesResponse 属性快照响应
type AttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                               // 响应头
	Attack        int64                  `protobuf:"varint,2,opt,name=attack,proto3" json:"attack,omitempty"`                              // 攻击力（规范8用int64）
	Defense       int64                  `protobuf:"varint,3,opt,name=defense,proto3" json:"defense,omitempty"`                            // 防御力
	Hp            int64                  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`                                      // 当前血量
	MaxHp         int64                  `protobuf:"varint,5,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`                   // 最大血量
	UnitType      int32                  `protobuf:"varint,6,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`          // 兵种类型（规范8用int32枚举）
	FormationId   int32                  `protobuf:"varint,7,opt,name=formation_id,json=formationId,proto3" json:"formation_id,omitempty"` // 阵型ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributesResponse) Reset() {
	*x = AttributesResponse{}
	mi := &file_proto_combat_combat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributesResponse) ProtoMessage() {}

func (x *AttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_combat_combat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributesResponse.ProtoReflect.Descriptor instead.
func (*AttributesResponse) Descriptor() ([]byte, []int) {
	return file_proto_combat_combat_proto_rawDescGZIP(), []int{1}
}

func (x *AttributesResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AttributesResponse) GetAttack() int64 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *AttributesResponse) GetDefense() int64 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *AttributesResponse) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *AttributesResponse) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *AttributesResponse) GetUnitType() int32 {
	if x != nil {
		return x.UnitType
	}
	return 0
}

func (x *AttributesResponse) GetFormationId() int32 {
	if x != nil {
		return x.FormationId
	}
	return 0
}

// GetCombatStateRequest 查询战斗状态请求
type GetCombatStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	CombatId      int64                  `protobuf:"varint,2,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"` // 战斗ID（规范8用int64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCombatStateRequest) Reset() {
	*x = GetCombatStateRequest{}
	mi := &file_proto_combat_combat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCombatStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCombatStateRequest) ProtoMessage() {}

func (x *GetCombatStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_combat_combat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCombatStateRequest.ProtoReflect.Descriptor instead.
func (*GetCombatStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_combat_combat_proto_rawDescGZIP(), []int{2}
}

func (x *GetCombatStateRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetCombatStateRequest) GetCombatId() int64 {
	if x != nil {
		return x.CombatId
	}
	return 0
}

// CombatStateResponse 战斗状态响应
type CombatStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                      // 响应头
	State         int32                  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`                                       // 战斗状态：1=进行中 2=结束 3=撤退（规范8用int32）
	CurrentRound  int32                  `protobuf:"varint,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`     // 当前轮次
	MaxRounds     int32                  `protobuf:"varint,4,opt,name=max_rounds,json=maxRounds,proto3" json:"max_rounds,omitempty"`              // 最大轮次
	AttackerIds   []int64                `protobuf:"varint,5,rep,packed,name=attacker_ids,json=attackerIds,proto3" json:"attacker_ids,omitempty"` // 攻击方实体ID列表
	DefenderIds   []int64                `protobuf:"varint,6,rep,packed,name=defender_ids,json=defenderIds,proto3" json:"defender_ids,omitempty"` // 防守方实体ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatStateResponse) Reset() {
	*x = CombatStateResponse{}
	mi := &file_proto_combat_combat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatStateResponse) ProtoMessage() {}

func (x *CombatStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_combat_combat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatStateResponse.ProtoReflect.Descriptor instead.
func (*CombatStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_combat_combat_proto_rawDescGZIP(), []int{3}
}

func (x *CombatStateResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CombatStateResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CombatStateResponse) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *CombatStateResponse) GetMaxRounds() int32 {
	if x != nil {
		return x.MaxRounds
	}
	return 0
}

func (x *CombatStateResponse) GetAttackerIds() []int64 {
	if x != nil {
		return x.AttackerIds
	}
	return nil
}

func (x *CombatStateResponse) GetDefenderIds() []int64 {
	if x != nil {
		return x.DefenderIds
	}
	return nil
}

// ReportRequest 查询战报请求（新增接口）
type ReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                      // 请求头
	CombatId      int64                  `protobuf:"varint,2,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"` // 战斗ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_proto_combat_combat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_combat_combat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_combat_combat_proto_rawDescGZIP(), []int{4}
}

func (x *ReportRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReportRequest) GetCombatId() int64 {
	if x != nil {
		return x.CombatId
	}
	return 0
}

// ReportResponse 战报响应（新增接口）
type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                               // 响应头
	CombatId      int64                  `protobuf:"varint,2,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`          // 战斗ID
	Result        int32                  `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`                              // 战斗结果：1=攻击方胜 2=防守方胜 3=平局
	TotalRounds   int32                  `protobuf:"varint,4,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"` // 总轮次
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`       // 战斗开始时间戳（毫秒）
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`             // 战斗结束时间戳（毫秒）
	Rounds        []*RoundReport         `protobuf:"bytes,7,rep,name=rounds,proto3" json:"rounds,omitempty"`                               // 各轮次战报
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_proto_combat_combat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_combat_combat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_combat_combat_proto_rawDescGZIP(), []int{5}
}

func (x *ReportResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReportResponse) GetCombatId() int64 {
	if x != nil {
		return x.CombatId
	}
	return 0
}

func (x *ReportResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ReportResponse) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *ReportResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ReportResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ReportResponse) GetRounds() []*RoundReport {
	if x != nil {
		return x.Rounds
	}
	return nil
}

// RoundReport 单轮次战报
type RoundReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Round          int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`                                         // 轮次序号
	AttackerDamage int64                  `protobuf:"varint,2,opt,name=attacker_damage,json=attackerDamage,proto3" json:"attacker_damage,omitempty"` // 攻击方造成伤害（规范8用int64）
	DefenderDamage int64                  `protobuf:"varint,3,opt,name=defender_damage,json=defenderDamage,proto3" json:"defender_damage,omitempty"` // 防守方造成伤害
	Skills         []*SkillUsage          `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`                                        // 技能使用记录
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoundReport) Reset() {
	*x = RoundReport{}
	mi := &file_proto_combat_combat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundReport) ProtoMessage() {}

func (x *RoundReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_combat_combat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundReport.ProtoReflect.Descriptor instead.
func (*RoundReport) Descriptor() ([]byte, []int) {
	return file_proto_combat_combat_proto_rawDescGZIP(), []int{6}
}

func (x *RoundReport) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *RoundReport) GetAttackerDamage() int64 {
	if x != nil {
		return x.AttackerDamage
	}
	return 0
}

func (x *RoundReport) GetDefenderDamage() int64 {
	if x != nil {
		return x.DefenderDamage
	}
	return 0
}

func (x *RoundReport) GetSkills() []*SkillUsage {
	if x != nil {
		return x.Skills
	}
	return nil
}

// SkillUsage 技能使用记录
type SkillUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      int64                  `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`          // 使用技能的实体ID
	SkillId       int32                  `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`             // 技能ID（规范8用int32）
	EffectValue   int64                  `protobuf:"varint,3,opt,name=effect_value,json=effectValue,proto3" json:"effect_value,omitempty"` // 效果数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillUsage) Reset() {
	*x = SkillUsage{}
	mi := &file_proto_combat_combat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillUsage) ProtoMessage() {}

func (x *SkillUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_combat_combat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillUsage.ProtoReflect.Descriptor instead.
func (*SkillUsage) Descriptor() ([]byte, []int) {
	return file_proto_combat_combat_proto_rawDescGZIP(), []int{7}
}

func (x *SkillUsage) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *SkillUsage) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SkillUsage) GetEffectValue() int64 {
	if x != nil {
		return x.EffectValue
	}
	return 0
}

var File_proto_combat_combat_proto protoreflect.FileDescriptor

const file_proto_combat_combat_proto_rawDesc = "" +
	"\n" +
	"\x19proto/combat/combat.proto\x12\x12insectworld.combat\x1a\x19proto/common/common.proto\"n\n" +
	"\x14GetAttributesRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\"\xe9\x01\n" +
	"\x12AttributesResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x16\n" +
	"\x06attack\x18\x02 \x01(\x03R\x06attack\x12\x18\n" +
	"\adefense\x18\x03 \x01(\x03R\adefense\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\x03R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x05 \x01(\x03R\x05maxHp\x12\x1b\n" +
	"\tunit_type\x18\x06 \x01(\x05R\bunitType\x12!\n" +
	"\fformation_id\x18\a \x01(\x05R\vformationId\"o\n" +
	"\x15GetCombatStateRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1b\n" +
	"\tcombat_id\x18\x02 \x01(\x03R\bcombatId\"\xf1\x01\n" +
	"\x13CombatStateResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\x12#\n" +
	"\rcurrent_round\x18\x03 \x01(\x05R\fcurrentRound\x12\x1d\n" +
	"\n" +
	"max_rounds\x18\x04 \x01(\x05R\tmaxRounds\x12!\n" +
	"\fattacker_ids\x18\x05 \x03(\x03R\vattackerIds\x12!\n" +
	"\fdefender_ids\x18\x06 \x03(\x03R\vdefenderIds\"g\n" +
	"\rReportRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x1b\n" +
	"\tcombat_id\x18\x02 \x01(\x03R\bcombatId\"\x97\x02\n" +
	"\x0eReportResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12\x1b\n" +
	"\tcombat_id\x18\x02 \x01(\x03R\bcombatId\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x05R\x06result\x12!\n" +
	"\ftotal_rounds\x18\x04 \x01(\x05R\vtotalRounds\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x127\n" +
	"\x06rounds\x18\a \x03(\v2\x1f.insectworld.combat.RoundReportR\x06rounds\"\xad\x01\n" +
	"\vRoundReport\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x12'\n" +
	"\x0fattacker_damage\x18\x02 \x01(\x03R\x0eattackerDamage\x12'\n" +
	"\x0fdefender_damage\x18\x03 \x01(\x03R\x0edefenderDamage\x126\n" +
	"\x06skills\x18\x04 \x03(\v2\x1e.insectworld.combat.SkillUsageR\x06skills\"g\n" +
	"\n" +
	"SkillUsage\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x03R\bentityId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x05R\askillId\x12!\n" +
	"\feffect_value\x18\x03 \x01(\x03R\veffectValue2\xb8\x02\n" +
	"\rCombatService\x12g\n" +
	"\x13GetEntityAttributes\x12(.insectworld.combat.GetAttributesRequest\x1a&.insectworld.combat.AttributesResponse\x12d\n" +
	"\x0eGetCombatState\x12).insectworld.combat.GetCombatStateRequest\x1a'.insectworld.combat.CombatStateResponse\x12X\n" +
	"\x0fGetCombatReport\x12!.insectworld.combat.ReportRequest\x1a\".insectworld.combat.ReportResponseB#Z!insectworld/proto/combat;combatpbb\x06proto3"

var (
	file_proto_combat_combat_proto_rawDescOnce sync.Once
	file_proto_combat_combat_proto_rawDescData []byte
)

func file_proto_combat_combat_proto_rawDescGZIP() []byte {
	file_proto_combat_combat_proto_rawDescOnce.Do(func() {
		file_proto_combat_combat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_combat_combat_proto_rawDesc), len(file_proto_combat_combat_proto_rawDesc)))
	})
	return file_proto_combat_combat_proto_rawDescData
}

var file_proto_combat_combat_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_combat_combat_proto_goTypes = []any{
	(*GetAttributesRequest)(nil),  // 0: insectworld.combat.GetAttributesRequest
	(*AttributesResponse)(nil),    // 1: insectworld.combat.AttributesResponse
	(*GetCombatStateRequest)(nil), // 2: insectworld.combat.GetCombatStateRequest
	(*CombatStateResponse)(nil),   // 3: insectworld.combat.CombatStateResponse
	(*ReportRequest)(nil),         // 4: insectworld.combat.ReportRequest
	(*ReportResponse)(nil),        // 5: insectworld.combat.ReportResponse
	(*RoundReport)(nil),           // 6: insectworld.combat.RoundReport
	(*SkillUsage)(nil),            // 7: insectworld.combat.SkillUsage
	(*common.RequestHeader)(nil),  // 8: insectworld.common.RequestHeader
	(*common.ResponseHeader)(nil), // 9: insectworld.common.ResponseHeader
}
var file_proto_combat_combat_proto_depIdxs = []int32{
	8,  // 0: insectworld.combat.GetAttributesRequest.header:type_name -> insectworld.common.RequestHeader
	9,  // 1: insectworld.combat.AttributesResponse.header:type_name -> insectworld.common.ResponseHeader
	8,  // 2: insectworld.combat.GetCombatStateRequest.header:type_name -> insectworld.common.RequestHeader
	9,  // 3: insectworld.combat.CombatStateResponse.header:type_name -> insectworld.common.ResponseHeader
	8,  // 4: insectworld.combat.ReportRequest.header:type_name -> insectworld.common.RequestHeader
	9,  // 5: insectworld.combat.ReportResponse.header:type_name -> insectworld.common.ResponseHeader
	6,  // 6: insectworld.combat.ReportResponse.rounds:type_name -> insectworld.combat.RoundReport
	7,  // 7: insectworld.combat.RoundReport.skills:type_name -> insectworld.combat.SkillUsage
	0,  // 8: insectworld.combat.CombatService.GetEntityAttributes:input_type -> insectworld.combat.GetAttributesRequest
	2,  // 9: insectworld.combat.CombatService.GetCombatState:input_type -> insectworld.combat.GetCombatStateRequest
	4,  // 10: insectworld.combat.CombatService.GetCombatReport:input_type -> insectworld.combat.ReportRequest
	1,  // 11: insectworld.combat.CombatService.GetEntityAttributes:output_type -> insectworld.combat.AttributesResponse
	3,  // 12: insectworld.combat.CombatService.GetCombatState:output_type -> insectworld.combat.CombatStateResponse
	5,  // 13: insectworld.combat.CombatService.GetCombatReport:output_type -> insectworld.combat.ReportResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_combat_combat_proto_init() }
func file_proto_combat_combat_proto_init() {
	if File_proto_combat_combat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_combat_combat_proto_rawDesc), len(file_proto_combat_combat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_combat_combat_proto_goTypes,
		DependencyIndexes: file_proto_combat_combat_proto_depIdxs,
		MessageInfos:      file_proto_combat_combat_proto_msgTypes,
	}.Build()
	File_proto_combat_combat_proto = out.File
	file_proto_combat_combat_proto_goTypes = nil
	file_proto_combat_combat_proto_depIdxs = nil
}
