// Gathering Service gRPC接口定义，提供采集队分配/召回/状态查询相关操作。
// 对应《通用SLG框架共性抽离方案_终版》P0-3 采集调度骨头（#15）与《契约冻结草案》4.3 清单。
// 契约冻结规则：本包为P3新增包 v1 冻结，字段编号不重用、消息只增不改、服务只加不改。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: proto/gathering/gathering.proto

package gatheringpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	event "insectworld/server/shared/proto/event"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GatherState 采集队状态，采集调度的核心快照。
type GatherState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                   // 采集队ID，全局唯一，由雪花算法生成（规范8用int64）
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                                 // 采集状态：1=去程 2=采集中 3=返程
	Tile          *common.Position       `protobuf:"bytes,3,opt,name=tile,proto3" json:"tile,omitempty"`                                      // 目标地块坐标，返程中为最后一次采集的地块
	ResourceType  int32                  `protobuf:"varint,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // 采集资源类型，对应资源配置ID（规范8用int32）
	Load          int64                  `protobuf:"varint,5,opt,name=load,proto3" json:"load,omitempty"`                                     // 当前载荷，已采集资源量（规范8用int64）
	Capacity      int64                  `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`                             // 载荷上限，由采集队兵种与科技加成决定
	StartTime     int64                  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`          // 当前阶段开始时间戳（毫秒）
	EndTime       int64                  `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                // 当前阶段结束时间戳（毫秒），0表示进行中无固定结束
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatherState) Reset() {
	*x = GatherState{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatherState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatherState) ProtoMessage() {}

func (x *GatherState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatherState.ProtoReflect.Descriptor instead.
func (*GatherState) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{0}
}

func (x *GatherState) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GatherState) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GatherState) GetTile() *common.Position {
	if x != nil {
		return x.Tile
	}
	return nil
}

func (x *GatherState) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *GatherState) GetLoad() int64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *GatherState) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *GatherState) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GatherState) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// AssignGatherTeamRequest 分配采集队请求
type AssignGatherTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                  // 请求头
	TeamId        int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                   // 采集队ID，由玩家集结/编队产生
	Target        *common.Position       `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`                                  // 目标地块坐标，需通过世界服务校验资源地块
	ResourceType  int32                  `protobuf:"varint,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // 期望采集的资源类型，服务端与地块实际资源比对
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignGatherTeamRequest) Reset() {
	*x = AssignGatherTeamRequest{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignGatherTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignGatherTeamRequest) ProtoMessage() {}

func (x *AssignGatherTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignGatherTeamRequest.ProtoReflect.Descriptor instead.
func (*AssignGatherTeamRequest) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{1}
}

func (x *AssignGatherTeamRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AssignGatherTeamRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *AssignGatherTeamRequest) GetTarget() *common.Position {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AssignGatherTeamRequest) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

// AssignGatherTeamResponse 分配采集队响应
type AssignGatherTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	State         *GatherState           `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`   // 分配后的采集队状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignGatherTeamResponse) Reset() {
	*x = AssignGatherTeamResponse{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignGatherTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignGatherTeamResponse) ProtoMessage() {}

func (x *AssignGatherTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignGatherTeamResponse.ProtoReflect.Descriptor instead.
func (*AssignGatherTeamResponse) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{2}
}

func (x *AssignGatherTeamResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AssignGatherTeamResponse) GetState() *GatherState {
	if x != nil {
		return x.State
	}
	return nil
}

// RecallGatherTeamRequest 召回采集队请求
type RecallGatherTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                // 请求头
	TeamId        int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // 采集队ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallGatherTeamRequest) Reset() {
	*x = RecallGatherTeamRequest{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallGatherTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallGatherTeamRequest) ProtoMessage() {}

func (x *RecallGatherTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallGatherTeamRequest.ProtoReflect.Descriptor instead.
func (*RecallGatherTeamRequest) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{3}
}

func (x *RecallGatherTeamRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RecallGatherTeamRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

// RecallGatherTeamResponse 召回采集队响应
type RecallGatherTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	State         *GatherState           `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`   // 召回后的采集队状态，状态置为返程
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallGatherTeamResponse) Reset() {
	*x = RecallGatherTeamResponse{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallGatherTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallGatherTeamResponse) ProtoMessage() {}

func (x *RecallGatherTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallGatherTeamResponse.ProtoReflect.Descriptor instead.
func (*RecallGatherTeamResponse) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{4}
}

func (x *RecallGatherTeamResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RecallGatherTeamResponse) GetState() *GatherState {
	if x != nil {
		return x.State
	}
	return nil
}

// GetGatherStateRequest 查询采集队状态请求
type GetGatherStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                // 请求头
	TeamId        int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // 采集队ID，0表示查询该玩家全部采集队
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatherStateRequest) Reset() {
	*x = GetGatherStateRequest{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatherStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatherStateRequest) ProtoMessage() {}

func (x *GetGatherStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatherStateRequest.ProtoReflect.Descriptor instead.
func (*GetGatherStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{5}
}

func (x *GetGatherStateRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetGatherStateRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

// GetGatherStateResponse 查询采集队状态响应
type GetGatherStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 响应头
	States        []*GatherState         `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty"` // 采集队状态列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatherStateResponse) Reset() {
	*x = GetGatherStateResponse{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatherStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatherStateResponse) ProtoMessage() {}

func (x *GetGatherStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatherStateResponse.ProtoReflect.Descriptor instead.
func (*GetGatherStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{6}
}

func (x *GetGatherStateResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetGatherStateResponse) GetStates() []*GatherState {
	if x != nil {
		return x.States
	}
	return nil
}

// GatherStartedEvent 采集开始事件，采集队到达地块开始采集时发布。
// 主题命名 event.gathering.started，订阅方用于记录采集行为与地块占用。
type GatherStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                      // 基础事件信息
	TeamId        int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                   // 采集队ID
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`             // 归属玩家ID
	Tile          *common.Position       `protobuf:"bytes,4,opt,name=tile,proto3" json:"tile,omitempty"`                                      // 采集地块坐标
	ResourceType  int32                  `protobuf:"varint,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // 采集资源类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatherStartedEvent) Reset() {
	*x = GatherStartedEvent{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatherStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatherStartedEvent) ProtoMessage() {}

func (x *GatherStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatherStartedEvent.ProtoReflect.Descriptor instead.
func (*GatherStartedEvent) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{7}
}

func (x *GatherStartedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GatherStartedEvent) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GatherStartedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GatherStartedEvent) GetTile() *common.Position {
	if x != nil {
		return x.Tile
	}
	return nil
}

func (x *GatherStartedEvent) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

// GatherCompletedEvent 采集完成事件，采集队载荷满载或采集时间到后返回。
// 主题命名 event.gathering.completed，订阅方用于发放采集资源到玩家背包/仓库。
type GatherCompletedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Base           *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                            // 基础事件信息
	TeamId         int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                         // 采集队ID
	PlayerId       int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`                   // 归属玩家ID
	Tile           *common.Position       `protobuf:"bytes,4,opt,name=tile,proto3" json:"tile,omitempty"`                                            // 采集地块坐标
	GatheredAmount int64                  `protobuf:"varint,5,opt,name=gathered_amount,json=gatheredAmount,proto3" json:"gathered_amount,omitempty"` // 本次采集获得的资源量
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatherCompletedEvent) Reset() {
	*x = GatherCompletedEvent{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatherCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatherCompletedEvent) ProtoMessage() {}

func (x *GatherCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatherCompletedEvent.ProtoReflect.Descriptor instead.
func (*GatherCompletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{8}
}

func (x *GatherCompletedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GatherCompletedEvent) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GatherCompletedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GatherCompletedEvent) GetTile() *common.Position {
	if x != nil {
		return x.Tile
	}
	return nil
}

func (x *GatherCompletedEvent) GetGatheredAmount() int64 {
	if x != nil {
		return x.GatheredAmount
	}
	return 0
}

// GatherRecalledEvent 采集召回事件，玩家主动召回采集队时发布。
// 主题命名 event.gathering.recalled，订阅方用于结算召回时的部分载荷。
type GatherRecalledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                // 基础事件信息
	TeamId        int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`             // 采集队ID
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`       // 归属玩家ID
	RecalledAt    int64                  `protobuf:"varint,4,opt,name=recalled_at,json=recalledAt,proto3" json:"recalled_at,omitempty"` // 召回时间戳（毫秒）
	Load          int64                  `protobuf:"varint,5,opt,name=load,proto3" json:"load,omitempty"`                               // 召回时携带的载荷量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatherRecalledEvent) Reset() {
	*x = GatherRecalledEvent{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatherRecalledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatherRecalledEvent) ProtoMessage() {}

func (x *GatherRecalledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatherRecalledEvent.ProtoReflect.Descriptor instead.
func (*GatherRecalledEvent) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{9}
}

func (x *GatherRecalledEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GatherRecalledEvent) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GatherRecalledEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GatherRecalledEvent) GetRecalledAt() int64 {
	if x != nil {
		return x.RecalledAt
	}
	return 0
}

func (x *GatherRecalledEvent) GetLoad() int64 {
	if x != nil {
		return x.Load
	}
	return 0
}

// TileOccupiedEvent 地块被占事件，目标地块已被其他采集队/建筑占用时发布。
// 主题命名 event.gathering.tile_occupied，采集分配失败时通知客户端改派。
type TileOccupiedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Base           *event.DomainEvent     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                              // 基础事件信息
	TeamId         int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                           // 尝试分配的采集队ID
	PlayerId       int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`                     // 发起分配的玩家ID
	Tile           *common.Position       `protobuf:"bytes,4,opt,name=tile,proto3" json:"tile,omitempty"`                                              // 被占用的地块坐标
	OccupierTeamId int64                  `protobuf:"varint,5,opt,name=occupier_team_id,json=occupierTeamId,proto3" json:"occupier_team_id,omitempty"` // 占用该地块的采集队ID，0表示被建筑占用
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TileOccupiedEvent) Reset() {
	*x = TileOccupiedEvent{}
	mi := &file_proto_gathering_gathering_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TileOccupiedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileOccupiedEvent) ProtoMessage() {}

func (x *TileOccupiedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gathering_gathering_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileOccupiedEvent.ProtoReflect.Descriptor instead.
func (*TileOccupiedEvent) Descriptor() ([]byte, []int) {
	return file_proto_gathering_gathering_proto_rawDescGZIP(), []int{10}
}

func (x *TileOccupiedEvent) GetBase() *event.DomainEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *TileOccupiedEvent) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *TileOccupiedEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *TileOccupiedEvent) GetTile() *common.Position {
	if x != nil {
		return x.Tile
	}
	return nil
}

func (x *TileOccupiedEvent) GetOccupierTeamId() int64 {
	if x != nil {
		return x.OccupierTeamId
	}
	return 0
}

var File_proto_gathering_gathering_proto protoreflect.FileDescriptor

const file_proto_gathering_gathering_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/gathering/gathering.proto\x12\x15insectworld.gathering\x1a\x19proto/common/common.proto\x1a\x1eproto/event/domain_event.proto\"\xff\x01\n" +
	"\vGatherState\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x120\n" +
	"\x04tile\x18\x03 \x01(\v2\x1c.insectworld.common.PositionR\x04tile\x12#\n" +
	"\rresource_type\x18\x04 \x01(\x05R\fresourceType\x12\x12\n" +
	"\x04load\x18\x05 \x01(\x03R\x04load\x12\x1a\n" +
	"\bcapacity\x18\x06 \x01(\x03R\bcapacity\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\x03R\aendTime\"\xc8\x01\n" +
	"\x17AssignGatherTeamRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\x124\n" +
	"\x06target\x18\x03 \x01(\v2\x1c.insectworld.common.PositionR\x06target\x12#\n" +
	"\rresource_type\x18\x04 \x01(\x05R\fresourceType\"\x90\x01\n" +
	"\x18AssignGatherTeamResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x128\n" +
	"\x05state\x18\x02 \x01(\v2\".insectworld.gathering.GatherStateR\x05state\"m\n" +
	"\x17RecallGatherTeamRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\"\x90\x01\n" +
	"\x18RecallGatherTeamResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x128\n" +
	"\x05state\x18\x02 \x01(\v2\".insectworld.gathering.GatherStateR\x05state\"k\n" +
	"\x15GetGatherStateRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\"\x90\x01\n" +
	"\x16GetGatherStateResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12:\n" +
	"\x06states\x18\x02 \x03(\v2\".insectworld.gathering.GatherStateR\x06states\"\xd5\x01\n" +
	"\x12GatherStartedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\x120\n" +
	"\x04tile\x18\x04 \x01(\v2\x1c.insectworld.common.PositionR\x04tile\x12#\n" +
	"\rresource_type\x18\x05 \x01(\x05R\fresourceType\"\xdb\x01\n" +
	"\x14GatherCompletedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\x120\n" +
	"\x04tile\x18\x04 \x01(\v2\x1c.insectworld.common.PositionR\x04tile\x12'\n" +
	"\x0fgathered_amount\x18\x05 \x01(\x03R\x0egatheredAmount\"\xb4\x01\n" +
	"\x13GatherRecalledEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vrecalled_at\x18\x04 \x01(\x03R\n" +
	"recalledAt\x12\x12\n" +
	"\x04load\x18\x05 \x01(\x03R\x04load\"\xd9\x01\n" +
	"\x11TileOccupiedEvent\x122\n" +
	"\x04base\x18\x01 \x01(\v2\x1e.insectworld.event.DomainEventR\x04base\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\x120\n" +
	"\x04tile\x18\x04 \x01(\v2\x1c.insectworld.common.PositionR\x04tile\x12(\n" +
	"\x10occupier_team_id\x18\x05 \x01(\x03R\x0eoccupierTeamId2\xeb\x02\n" +
	"\x10GatheringService\x12s\n" +
	"\x10AssignGatherTeam\x12..insectworld.gathering.AssignGatherTeamRequest\x1a/.insectworld.gathering.AssignGatherTeamResponse\x12s\n" +
	"\x10RecallGatherTeam\x12..insectworld.gathering.RecallGatherTeamRequest\x1a/.insectworld.gathering.RecallGatherTeamResponse\x12m\n" +
	"\x0eGetGatherState\x12,.insectworld.gathering.GetGatherStateRequest\x1a-.insectworld.gathering.GetGatherStateResponseB)Z'insectworld/proto/gathering;gatheringpbb\x06proto3"

var (
	file_proto_gathering_gathering_proto_rawDescOnce sync.Once
	file_proto_gathering_gathering_proto_rawDescData []byte
)

func file_proto_gathering_gathering_proto_rawDescGZIP() []byte {
	file_proto_gathering_gathering_proto_rawDescOnce.Do(func() {
		file_proto_gathering_gathering_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gathering_gathering_proto_rawDesc), len(file_proto_gathering_gathering_proto_rawDesc)))
	})
	return file_proto_gathering_gathering_proto_rawDescData
}

var file_proto_gathering_gathering_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_gathering_gathering_proto_goTypes = []any{
	(*GatherState)(nil),              // 0: insectworld.gathering.GatherState
	(*AssignGatherTeamRequest)(nil),  // 1: insectworld.gathering.AssignGatherTeamRequest
	(*AssignGatherTeamResponse)(nil), // 2: insectworld.gathering.AssignGatherTeamResponse
	(*RecallGatherTeamRequest)(nil),  // 3: insectworld.gathering.RecallGatherTeamRequest
	(*RecallGatherTeamResponse)(nil), // 4: insectworld.gathering.RecallGatherTeamResponse
	(*GetGatherStateRequest)(nil),    // 5: insectworld.gathering.GetGatherStateRequest
	(*GetGatherStateResponse)(nil),   // 6: insectworld.gathering.GetGatherStateResponse
	(*GatherStartedEvent)(nil),       // 7: insectworld.gathering.GatherStartedEvent
	(*GatherCompletedEvent)(nil),     // 8: insectworld.gathering.GatherCompletedEvent
	(*GatherRecalledEvent)(nil),      // 9: insectworld.gathering.GatherRecalledEvent
	(*TileOccupiedEvent)(nil),        // 10: insectworld.gathering.TileOccupiedEvent
	(*common.Position)(nil),          // 11: insectworld.common.Position
	(*common.RequestHeader)(nil),     // 12: insectworld.common.RequestHeader
	(*common.ResponseHeader)(nil),    // 13: insectworld.common.ResponseHeader
	(*event.DomainEvent)(nil),        // 14: insectworld.event.DomainEvent
}
var file_proto_gathering_gathering_proto_depIdxs = []int32{
	11, // 0: insectworld.gathering.GatherState.tile:type_name -> insectworld.common.Position
	12, // 1: insectworld.gathering.AssignGatherTeamRequest.header:type_name -> insectworld.common.RequestHeader
	11, // 2: insectworld.gathering.AssignGatherTeamRequest.target:type_name -> insectworld.common.Position
	13, // 3: insectworld.gathering.AssignGatherTeamResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 4: insectworld.gathering.AssignGatherTeamResponse.state:type_name -> insectworld.gathering.GatherState
	12, // 5: insectworld.gathering.RecallGatherTeamRequest.header:type_name -> insectworld.common.RequestHeader
	13, // 6: insectworld.gathering.RecallGatherTeamResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 7: insectworld.gathering.RecallGatherTeamResponse.state:type_name -> insectworld.gathering.GatherState
	12, // 8: insectworld.gathering.GetGatherStateRequest.header:type_name -> insectworld.common.RequestHeader
	13, // 9: insectworld.gathering.GetGatherStateResponse.header:type_name -> insectworld.common.ResponseHeader
	0,  // 10: insectworld.gathering.GetGatherStateResponse.states:type_name -> insectworld.gathering.GatherState
	14, // 11: insectworld.gathering.GatherStartedEvent.base:type_name -> insectworld.event.DomainEvent
	11, // 12: insectworld.gathering.GatherStartedEvent.tile:type_name -> insectworld.common.Position
	14, // 13: insectworld.gathering.GatherCompletedEvent.base:type_name -> insectworld.event.DomainEvent
	11, // 14: insectworld.gathering.GatherCompletedEvent.tile:type_name -> insectworld.common.Position
	14, // 15: insectworld.gathering.GatherRecalledEvent.base:type_name -> insectworld.event.DomainEvent
	14, // 16: insectworld.gathering.TileOccupiedEvent.base:type_name -> insectworld.event.DomainEvent
	11, // 17: insectworld.gathering.TileOccupiedEvent.tile:type_name -> insectworld.common.Position
	1,  // 18: insectworld.gathering.GatheringService.AssignGatherTeam:input_type -> insectworld.gathering.AssignGatherTeamRequest
	3,  // 19: insectworld.gathering.GatheringService.RecallGatherTeam:input_type -> insectworld.gathering.RecallGatherTeamRequest
	5,  // 20: insectworld.gathering.GatheringService.GetGatherState:input_type -> insectworld.gathering.GetGatherStateRequest
	2,  // 21: insectworld.gathering.GatheringService.AssignGatherTeam:output_type -> insectworld.gathering.AssignGatherTeamResponse
	4,  // 22: insectworld.gathering.GatheringService.RecallGatherTeam:output_type -> insectworld.gathering.RecallGatherTeamResponse
	6,  // 23: insectworld.gathering.GatheringService.GetGatherState:output_type -> insectworld.gathering.GetGatherStateResponse
	21, // [21:24] is the sub-list for method output_type
	18, // [18:21] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_gathering_gathering_proto_init() }
func file_proto_gathering_gathering_proto_init() {
	if File_proto_gathering_gathering_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gathering_gathering_proto_rawDesc), len(file_proto_gathering_gathering_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gathering_gathering_proto_goTypes,
		DependencyIndexes: file_proto_gathering_gathering_proto_depIdxs,
		MessageInfos:      file_proto_gathering_gathering_proto_msgTypes,
	}.Build()
	File_proto_gathering_gathering_proto = out.File
	file_proto_gathering_gathering_proto_goTypes = nil
	file_proto_gathering_gathering_proto_depIdxs = nil
}
