// Gathering Service gRPC接口定义，提供采集队分配/召回/状态查询相关操作。
// 对应《通用SLG框架共性抽离方案_终版》P0-3 采集调度骨头（#15）与《契约冻结草案》4.3 清单。
// 契约冻结规则：本包为P3新增包 v1 冻结，字段编号不重用、消息只增不改、服务只加不改。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/gathering/gathering.proto

package gatheringpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatheringService_AssignGatherTeam_FullMethodName = "/insectworld.gathering.GatheringService/AssignGatherTeam"
	GatheringService_RecallGatherTeam_FullMethodName = "/insectworld.gathering.GatheringService/RecallGatherTeam"
	GatheringService_GetGatherState_FullMethodName   = "/insectworld.gathering.GatheringService/GetGatherState"
)

// GatheringServiceClient is the client API for GatheringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatheringService 采集调度服务gRPC接口，提供采集队分配、召回与状态查询。
// 采集状态机（去程→采集中→返程）由服务端驱动，客户端通过状态查询轮询或订阅事件感知。
type GatheringServiceClient interface {
	// 分配采集队前往目标地块，地块被占用时返回异常并发布 TileOccupiedEvent
	AssignGatherTeam(ctx context.Context, in *AssignGatherTeamRequest, opts ...grpc.CallOption) (*AssignGatherTeamResponse, error)
	// 召回采集队，采集队携带当前载荷返程
	RecallGatherTeam(ctx context.Context, in *RecallGatherTeamRequest, opts ...grpc.CallOption) (*RecallGatherTeamResponse, error)
	// 查询采集队状态，team_id 传 0 时返回该玩家全部采集队
	GetGatherState(ctx context.Context, in *GetGatherStateRequest, opts ...grpc.CallOption) (*GetGatherStateResponse, error)
}

type gatheringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatheringServiceClient(cc grpc.ClientConnInterface) GatheringServiceClient {
	return &gatheringServiceClient{cc}
}

func (c *gatheringServiceClient) AssignGatherTeam(ctx context.Context, in *AssignGatherTeamRequest, opts ...grpc.CallOption) (*AssignGatherTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignGatherTeamResponse)
	err := c.cc.Invoke(ctx, GatheringService_AssignGatherTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatheringServiceClient) RecallGatherTeam(ctx context.Context, in *RecallGatherTeamRequest, opts ...grpc.CallOption) (*RecallGatherTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallGatherTeamResponse)
	err := c.cc.Invoke(ctx, GatheringService_RecallGatherTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatheringServiceClient) GetGatherState(ctx context.Context, in *GetGatherStateRequest, opts ...grpc.CallOption) (*GetGatherStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatherStateResponse)
	err := c.cc.Invoke(ctx, GatheringService_GetGatherState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatheringServiceServer is the server API for GatheringService service.
// All implementations must embed UnimplementedGatheringServiceServer
// for forward compatibility.
//
// GatheringService 采集调度服务gRPC接口，提供采集队分配、召回与状态查询。
// 采集状态机（去程→采集中→返程）由服务端驱动，客户端通过状态查询轮询或订阅事件感知。
type GatheringServiceServer interface {
	// 分配采集队前往目标地块，地块被占用时返回异常并发布 TileOccupiedEvent
	AssignGatherTeam(context.Context, *AssignGatherTeamRequest) (*AssignGatherTeamResponse, error)
	// 召回采集队，采集队携带当前载荷返程
	RecallGatherTeam(context.Context, *RecallGatherTeamRequest) (*RecallGatherTeamResponse, error)
	// 查询采集队状态，team_id 传 0 时返回该玩家全部采集队
	GetGatherState(context.Context, *GetGatherStateRequest) (*GetGatherStateResponse, error)
	mustEmbedUnimplementedGatheringServiceServer()
}

// UnimplementedGatheringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatheringServiceServer struct{}

func (UnimplementedGatheringServiceServer) AssignGatherTeam(context.Context, *AssignGatherTeamRequest) (*AssignGatherTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignGatherTeam not implemented")
}
func (UnimplementedGatheringServiceServer) RecallGatherTeam(context.Context, *RecallGatherTeamRequest) (*RecallGatherTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecallGatherTeam not implemented")
}
func (UnimplementedGatheringServiceServer) GetGatherState(context.Context, *GetGatherStateRequest) (*GetGatherStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGatherState not implemented")
}
func (UnimplementedGatheringServiceServer) mustEmbedUnimplementedGatheringServiceServer() {}
func (UnimplementedGatheringServiceServer) testEmbeddedByValue()                          {}

// UnsafeGatheringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatheringServiceServer will
// result in compilation errors.
type UnsafeGatheringServiceServer interface {
	mustEmbedUnimplementedGatheringServiceServer()
}

func RegisterGatheringServiceServer(s grpc.ServiceRegistrar, srv GatheringServiceServer) {
	// If the following call panics, it indicates UnimplementedGatheringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatheringService_ServiceDesc, srv)
}

func _GatheringService_AssignGatherTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignGatherTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatheringServiceServer).AssignGatherTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatheringService_AssignGatherTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatheringServiceServer).AssignGatherTeam(ctx, req.(*AssignGatherTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatheringService_RecallGatherTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallGatherTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatheringServiceServer).RecallGatherTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatheringService_RecallGatherTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatheringServiceServer).RecallGatherTeam(ctx, req.(*RecallGatherTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatheringService_GetGatherState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatherStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatheringServiceServer).GetGatherState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatheringService_GetGatherState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatheringServiceServer).GetGatherState(ctx, req.(*GetGatherStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatheringService_ServiceDesc is the grpc.ServiceDesc for GatheringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatheringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insectworld.gathering.GatheringService",
	HandlerType: (*GatheringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignGatherTeam",
			Handler:    _GatheringService_AssignGatherTeam_Handler,
		},
		{
			MethodName: "RecallGatherTeam",
			Handler:    _GatheringService_RecallGatherTeam_Handler,
		},
		{
			MethodName: "GetGatherState",
			Handler:    _GatheringService_GetGatherState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gathering/gathering.proto",
}
