// Config Service gRPC接口定义，提供配置包提交/回滚/版本历史查询。
// 对应design.md 2.2.2.6节接口清单，为运营管理面提供配置管理能力。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/config/config.proto

package configpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigService_SubmitConfigPack_FullMethodName        = "/insectworld.config.ConfigService/SubmitConfigPack"
	ConfigService_RollbackConfig_FullMethodName          = "/insectworld.config.ConfigService/RollbackConfig"
	ConfigService_GetConfigVersionHistory_FullMethodName = "/insectworld.config.ConfigService/GetConfigVersionHistory"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigService Config服务gRPC接口，提供配置包管理。
type ConfigServiceClient interface {
	SubmitConfigPack(ctx context.Context, in *SubmitConfigRequest, opts ...grpc.CallOption) (*SubmitConfigResponse, error)
	RollbackConfig(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	GetConfigVersionHistory(ctx context.Context, in *VersionHistoryRequest, opts ...grpc.CallOption) (*VersionHistoryResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) SubmitConfigPack(ctx context.Context, in *SubmitConfigRequest, opts ...grpc.CallOption) (*SubmitConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_SubmitConfigPack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) RollbackConfig(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, ConfigService_RollbackConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetConfigVersionHistory(ctx context.Context, in *VersionHistoryRequest, opts ...grpc.CallOption) (*VersionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionHistoryResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetConfigVersionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
//
// ConfigService Config服务gRPC接口，提供配置包管理。
type ConfigServiceServer interface {
	SubmitConfigPack(context.Context, *SubmitConfigRequest) (*SubmitConfigResponse, error)
	RollbackConfig(context.Context, *RollbackRequest) (*RollbackResponse, error)
	GetConfigVersionHistory(context.Context, *VersionHistoryRequest) (*VersionHistoryResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) SubmitConfigPack(context.Context, *SubmitConfigRequest) (*SubmitConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitConfigPack not implemented")
}
func (UnimplementedConfigServiceServer) RollbackConfig(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetConfigVersionHistory(context.Context, *VersionHistoryRequest) (*VersionHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigVersionHistory not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_SubmitConfigPack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).SubmitConfigPack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_SubmitConfigPack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).SubmitConfigPack(ctx, req.(*SubmitConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_RollbackConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).RollbackConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_RollbackConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).RollbackConfig(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetConfigVersionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetConfigVersionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetConfigVersionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetConfigVersionHistory(ctx, req.(*VersionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insectworld.config.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitConfigPack",
			Handler:    _ConfigService_SubmitConfigPack_Handler,
		},
		{
			MethodName: "RollbackConfig",
			Handler:    _ConfigService_RollbackConfig_Handler,
		},
		{
			MethodName: "GetConfigVersionHistory",
			Handler:    _ConfigService_GetConfigVersionHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/config/config.proto",
}
