// Config Service gRPC接口定义，提供配置包提交/回滚/版本历史查询。
// 对应design.md 2.2.2.6节接口清单，为运营管理面提供配置管理能力。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/config/config.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "insectworld/server/shared/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubmitConfigRequest 提交配置包请求
type SubmitConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                   // 请求头
	ConfigPackId  string                 `protobuf:"bytes,2,opt,name=config_pack_id,json=configPackId,proto3" json:"config_pack_id,omitempty"` // 配置包ID，标识本次提交的配置包
	ConfigData    []byte                 `protobuf:"bytes,3,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`         // 配置包数据（zip压缩后的二进制）
	Md5           string                 `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`                                         // 配置包MD5校验值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitConfigRequest) Reset() {
	*x = SubmitConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitConfigRequest) ProtoMessage() {}

func (x *SubmitConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitConfigRequest.ProtoReflect.Descriptor instead.
func (*SubmitConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitConfigRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubmitConfigRequest) GetConfigPackId() string {
	if x != nil {
		return x.ConfigPackId
	}
	return ""
}

func (x *SubmitConfigRequest) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

func (x *SubmitConfigRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

// SubmitConfigResponse 提交配置包响应
type SubmitConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                     // 响应头
	ConfigVersion int64                  `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // 分配的配置版本号（规范8用int64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitConfigResponse) Reset() {
	*x = SubmitConfigResponse{}
	mi := &file_proto_config_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitConfigResponse) ProtoMessage() {}

func (x *SubmitConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitConfigResponse.ProtoReflect.Descriptor instead.
func (*SubmitConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitConfigResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubmitConfigResponse) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// RollbackRequest 回滚配置请求
type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                     // 请求头
	TargetVersion int64                  `protobuf:"varint,2,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"` // 目标回滚版本号（规范8用int64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_proto_config_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RollbackRequest) GetTargetVersion() int64 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

// RollbackResponse 回滚配置响应
type RollbackResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Header         *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                        // 响应头
	CurrentVersion int64                  `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // 回滚后的当前版本号
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_proto_config_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RollbackResponse) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

// VersionHistoryRequest 查询版本历史请求
type VersionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.RequestHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`         // 请求头
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionHistoryRequest) Reset() {
	*x = VersionHistoryRequest{}
	mi := &file_proto_config_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionHistoryRequest) ProtoMessage() {}

func (x *VersionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionHistoryRequest.ProtoReflect.Descriptor instead.
func (*VersionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{4}
}

func (x *VersionHistoryRequest) GetHeader() *common.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *VersionHistoryRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// VersionHistoryResponse 版本历史响应
type VersionHistoryResponse struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Header           *common.ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                             // 响应头
	Versions         []*ConfigVersion         `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`                                         // 版本历史列表
	PaginationResult *common.PaginationResult `protobuf:"bytes,3,opt,name=pagination_result,json=paginationResult,proto3" json:"pagination_result,omitempty"` // 分页结果
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VersionHistoryResponse) Reset() {
	*x = VersionHistoryResponse{}
	mi := &file_proto_config_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionHistoryResponse) ProtoMessage() {}

func (x *VersionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionHistoryResponse.ProtoReflect.Descriptor instead.
func (*VersionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{5}
}

func (x *VersionHistoryResponse) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *VersionHistoryResponse) GetVersions() []*ConfigVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *VersionHistoryResponse) GetPaginationResult() *common.PaginationResult {
	if x != nil {
		return x.PaginationResult
	}
	return nil
}

// ConfigVersion 配置版本信息
type ConfigVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                 // 版本号（规范8用int64）
	ConfigPackId  string                 `protobuf:"bytes,2,opt,name=config_pack_id,json=configPackId,proto3" json:"config_pack_id,omitempty"`  // 配置包ID
	SubmitTime    int64                  `protobuf:"varint,3,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`         // 提交时间戳（毫秒）
	Submitter     string                 `protobuf:"bytes,4,opt,name=submitter,proto3" json:"submitter,omitempty"`                              // 提交人
	IsRolledBack  bool                   `protobuf:"varint,5,opt,name=is_rolled_back,json=isRolledBack,proto3" json:"is_rolled_back,omitempty"` // 是否已回滚
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigVersion) Reset() {
	*x = ConfigVersion{}
	mi := &file_proto_config_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVersion) ProtoMessage() {}

func (x *ConfigVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVersion.ProtoReflect.Descriptor instead.
func (*ConfigVersion) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigVersion) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigVersion) GetConfigPackId() string {
	if x != nil {
		return x.ConfigPackId
	}
	return ""
}

func (x *ConfigVersion) GetSubmitTime() int64 {
	if x != nil {
		return x.SubmitTime
	}
	return 0
}

func (x *ConfigVersion) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *ConfigVersion) GetIsRolledBack() bool {
	if x != nil {
		return x.IsRolledBack
	}
	return false
}

var File_proto_config_config_proto protoreflect.FileDescriptor

const file_proto_config_config_proto_rawDesc = "" +
	"\n" +
	"\x19proto/config/config.proto\x12\x12insectworld.config\x1a\x19proto/common/common.proto\"\xa9\x01\n" +
	"\x13SubmitConfigRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12$\n" +
	"\x0econfig_pack_id\x18\x02 \x01(\tR\fconfigPackId\x12\x1f\n" +
	"\vconfig_data\x18\x03 \x01(\fR\n" +
	"configData\x12\x10\n" +
	"\x03md5\x18\x04 \x01(\tR\x03md5\"y\n" +
	"\x14SubmitConfigResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\x03R\rconfigVersion\"s\n" +
	"\x0fRollbackRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12%\n" +
	"\x0etarget_version\x18\x02 \x01(\x03R\rtargetVersion\"w\n" +
	"\x10RollbackResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x03R\x0ecurrentVersion\"\x92\x01\n" +
	"\x15VersionHistoryRequest\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.insectworld.common.RequestHeaderR\x06header\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.insectworld.common.PaginationR\n" +
	"pagination\"\xe6\x01\n" +
	"\x16VersionHistoryResponse\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".insectworld.common.ResponseHeaderR\x06header\x12=\n" +
	"\bversions\x18\x02 \x03(\v2!.insectworld.config.ConfigVersionR\bversions\x12Q\n" +
	"\x11pagination_result\x18\x03 \x01(\v2$.insectworld.common.PaginationResultR\x10paginationResult\"\xb4\x01\n" +
	"\rConfigVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12$\n" +
	"\x0econfig_pack_id\x18\x02 \x01(\tR\fconfigPackId\x12\x1f\n" +
	"\vsubmit_time\x18\x03 \x01(\x03R\n" +
	"submitTime\x12\x1c\n" +
	"\tsubmitter\x18\x04 \x01(\tR\tsubmitter\x12$\n" +
	"\x0eis_rolled_back\x18\x05 \x01(\bR\fisRolledBack2\xc5\x02\n" +
	"\rConfigService\x12e\n" +
	"\x10SubmitConfigPack\x12'.insectworld.config.SubmitConfigRequest\x1a(.insectworld.config.SubmitConfigResponse\x12[\n" +
	"\x0eRollbackConfig\x12#.insectworld.config.RollbackRequest\x1a$.insectworld.config.RollbackResponse\x12p\n" +
	"\x17GetConfigVersionHistory\x12).insectworld.config.VersionHistoryRequest\x1a*.insectworld.config.VersionHistoryResponseB#Z!insectworld/server/shared/proto/config;configpbb\x06proto3"

var (
	file_proto_config_config_proto_rawDescOnce sync.Once
	file_proto_config_config_proto_rawDescData []byte
)

func file_proto_config_config_proto_rawDescGZIP() []byte {
	file_proto_config_config_proto_rawDescOnce.Do(func() {
		file_proto_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_config_proto_rawDesc), len(file_proto_config_config_proto_rawDesc)))
	})
	return file_proto_config_config_proto_rawDescData
}

var file_proto_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_config_config_proto_goTypes = []any{
	(*SubmitConfigRequest)(nil),     // 0: insectworld.config.SubmitConfigRequest
	(*SubmitConfigResponse)(nil),    // 1: insectworld.config.SubmitConfigResponse
	(*RollbackRequest)(nil),         // 2: insectworld.config.RollbackRequest
	(*RollbackResponse)(nil),        // 3: insectworld.config.RollbackResponse
	(*VersionHistoryRequest)(nil),   // 4: insectworld.config.VersionHistoryRequest
	(*VersionHistoryResponse)(nil),  // 5: insectworld.config.VersionHistoryResponse
	(*ConfigVersion)(nil),           // 6: insectworld.config.ConfigVersion
	(*common.RequestHeader)(nil),    // 7: insectworld.common.RequestHeader
	(*common.ResponseHeader)(nil),   // 8: insectworld.common.ResponseHeader
	(*common.Pagination)(nil),       // 9: insectworld.common.Pagination
	(*common.PaginationResult)(nil), // 10: insectworld.common.PaginationResult
}
var file_proto_config_config_proto_depIdxs = []int32{
	7,  // 0: insectworld.config.SubmitConfigRequest.header:type_name -> insectworld.common.RequestHeader
	8,  // 1: insectworld.config.SubmitConfigResponse.header:type_name -> insectworld.common.ResponseHeader
	7,  // 2: insectworld.config.RollbackRequest.header:type_name -> insectworld.common.RequestHeader
	8,  // 3: insectworld.config.RollbackResponse.header:type_name -> insectworld.common.ResponseHeader
	7,  // 4: insectworld.config.VersionHistoryRequest.header:type_name -> insectworld.common.RequestHeader
	9,  // 5: insectworld.config.VersionHistoryRequest.pagination:type_name -> insectworld.common.Pagination
	8,  // 6: insectworld.config.VersionHistoryResponse.header:type_name -> insectworld.common.ResponseHeader
	6,  // 7: insectworld.config.VersionHistoryResponse.versions:type_name -> insectworld.config.ConfigVersion
	10, // 8: insectworld.config.VersionHistoryResponse.pagination_result:type_name -> insectworld.common.PaginationResult
	0,  // 9: insectworld.config.ConfigService.SubmitConfigPack:input_type -> insectworld.config.SubmitConfigRequest
	2,  // 10: insectworld.config.ConfigService.RollbackConfig:input_type -> insectworld.config.RollbackRequest
	4,  // 11: insectworld.config.ConfigService.GetConfigVersionHistory:input_type -> insectworld.config.VersionHistoryRequest
	1,  // 12: insectworld.config.ConfigService.SubmitConfigPack:output_type -> insectworld.config.SubmitConfigResponse
	3,  // 13: insectworld.config.ConfigService.RollbackConfig:output_type -> insectworld.config.RollbackResponse
	5,  // 14: insectworld.config.ConfigService.GetConfigVersionHistory:output_type -> insectworld.config.VersionHistoryResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_config_config_proto_init() }
func file_proto_config_config_proto_init() {
	if File_proto_config_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_config_proto_rawDesc), len(file_proto_config_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_config_proto_goTypes,
		DependencyIndexes: file_proto_config_config_proto_depIdxs,
		MessageInfos:      file_proto_config_config_proto_msgTypes,
	}.Build()
	File_proto_config_config_proto = out.File
	file_proto_config_config_proto_goTypes = nil
	file_proto_config_config_proto_depIdxs = nil
}
